; AnimationTypePointerTable indexes (see engine/battle/animations.asm)
	const_def 1
	const ANIMATIONTYPE_SHAKE_SCREEN_VERTICALLY          ; 1
	const ANIMATIONTYPE_SHAKE_SCREEN_HORIZONTALLY_HEAVY  ; 2
	const ANIMATIONTYPE_SHAKE_SCREEN_HORIZONTALLY_SLOW   ; 3
	const ANIMATIONTYPE_BLINK_ENEMY_MON_SPRITE           ; 4
	const ANIMATIONTYPE_SHAKE_SCREEN_HORIZONTALLY_LIGHT  ; 5
	const ANIMATIONTYPE_SHAKE_SCREEN_HORIZONTALLY_SLOW_2 ; 6
