 ; PureRGBnote: ADDED: use this constant for quick warping to various places from red's house's door in debug build
DEF PALLET_DEBUG_WARP_MAP EQU POKEMON_MANSION_B1F
DEF PALLET_DEBUG_WARP_WHICH EQU 2
DEF REDS_HOUSE_1F_DEBUG_WARP_MAP EQU BILLS_GARDEN
DEF REDS_HOUSE_1F_DEBUG_WARP_WHICH EQU 1
