; PureRGBnote: ADDED: use this constant for quick warping to various places from red's house's door in debug build
DEF PALLET_DEBUG_WARP_MAP EQU SS_ANNE_B1F
DEF PALLET_DEBUG_WARP_WHICH EQU 5
; SS Anne b1f is used for a bunch of quick warps
DEF DEBUG_WARP1_MAP EQU SS_ANNE_B1F
DEF DEBUG_WARP1_WHICH EQU 5
DEF DEBUG_WARP2_MAP EQU SAFFRON_GYM
DEF DEBUG_WARP2_WHICH EQU 1
DEF DEBUG_WARP3_MAP EQU SILPH_CO_2F
DEF DEBUG_WARP3_WHICH EQU 1
DEF DEBUG_WARP4_MAP EQU SECRET_LAB
DEF DEBUG_WARP4_WHICH EQU 4
DEF DEBUG_WARP5_MAP EQU SEAFOAM_ISLANDS_1F
DEF DEBUG_WARP5_WHICH EQU 3
DEF DEBUG_WARP6_MAP EQU POWER_PLANT
DEF DEBUG_WARP6_WHICH EQU 1


; PureRGBnote: These decide what pokemon appears on route 1, and what moves it has. 
; Also decides what team and mvoes the jr trainer just above vermillion city has.
DEF DEBUG_OPPONENT_TEST_MOVE_1 EQU SELFDESTRUCT
DEF DEBUG_OPPONENT_TEST_MOVE_2 EQU EXPLOSION
DEF DEBUG_OPPONENT_LEVEL EQU 20
DEF DEBUG_OPPONENT_SPECIES EQU BULBASAUR
