 ; PureRGBnote: ADDED: use this constant for quick warping to various places from red's house's door in debug build
DEF PALLET_DEBUG_WARP_MAP EQU POKEMON_TOWER_B1F
DEF PALLET_DEBUG_WARP_WHICH EQU 2
DEF BLUES_HOUSE_1F_DEBUG_WARP_MAP EQU CERULEAN_ROCKET_HOUSE_B1F
DEF BLUES_HOUSE_1F_DEBUG_WARP_WHICH EQU 1
DEF DEBUG_OPPONENT_TEST_MOVE_1 EQU SELFDESTRUCT
DEF DEBUG_OPPONENT_TEST_MOVE_2 EQU EXPLOSION
DEF DEBUG_OPPONENT_LEVEL EQU 20
DEF DEBUG_OPPONENT_SPECIES EQU BULBASAUR
