; wEventFlags bit flags

; Pallet Town events
	const_def
	const EVENT_FOLLOWED_OAK_INTO_LAB
	const_skip 2
	const EVENT_HALL_OF_FAME_DEX_RATING
	const_skip 2
	const EVENT_PALLET_AFTER_GETTING_POKEBALLS
	const_skip 17
	const EVENT_GOT_TOWN_MAP
	const EVENT_ENTERED_BLUES_HOUSE
	const EVENT_DAISY_WALKING
	const_skip 5
	const EVENT_FOLLOWED_OAK_INTO_LAB_2
	const EVENT_OAK_ASKED_TO_CHOOSE_MON
	const EVENT_GOT_STARTER
	const EVENT_BATTLED_RIVAL_IN_OAKS_LAB
	const EVENT_GOT_POKEBALLS_FROM_OAK
	const EVENT_GOT_POKEDEX
	const EVENT_PALLET_AFTER_GETTING_POKEBALLS_2
	const EVENT_OAK_APPEARED_IN_PALLET

; Viridian City events
	const_next $28
	const EVENT_VIRIDIAN_GYM_OPEN
	const EVENT_GOT_TM42
	const_skip 14
	const EVENT_OAK_GOT_PARCEL
	const EVENT_GOT_OAKS_PARCEL
	const_skip 22
	const EVENT_GOT_TM27
	const EVENT_BEAT_VIRIDIAN_GYM_GIOVANNI
	const EVENT_BEAT_VIRIDIAN_GYM_TRAINER_0
	const EVENT_BEAT_VIRIDIAN_GYM_TRAINER_1
	const EVENT_BEAT_VIRIDIAN_GYM_TRAINER_2
	const EVENT_BEAT_VIRIDIAN_GYM_TRAINER_3
	const EVENT_BEAT_VIRIDIAN_GYM_TRAINER_4
	const EVENT_BEAT_VIRIDIAN_GYM_TRAINER_5
	const EVENT_BEAT_VIRIDIAN_GYM_TRAINER_6
	const EVENT_BEAT_VIRIDIAN_GYM_TRAINER_7

; Pewter City events
	const_next $68
	const EVENT_BOUGHT_MUSEUM_TICKET
	const EVENT_GOT_OLD_AMBER
	const_skip 8
	const EVENT_BEAT_PEWTER_GYM_TRAINER_0
	const_skip 3
	const EVENT_GOT_TM34
	const EVENT_BEAT_BROCK

; Cerulean City events
	const_next $98
	const EVENT_BEAT_CERULEAN_RIVAL
	const_skip 14
	const EVENT_BEAT_CERULEAN_ROCKET_THIEF
	const_skip 18
	const EVENT_BEAT_CERULEAN_GYM_TRAINER_0
	const EVENT_BEAT_CERULEAN_GYM_TRAINER_1
	const_skip 2
	const EVENT_GOT_TM11
	const EVENT_BEAT_MISTY
	const EVENT_GOT_BICYCLE

; Lavender Town events
	const_next $F0 - 2
	const EVENT_POKEMON_TOWER_RIVAL_ON_LEFT
	const EVENT_BEAT_POKEMON_TOWER_RIVAL
	const_skip
	const EVENT_BEAT_POKEMONTOWER_3_TRAINER_0
	const EVENT_BEAT_POKEMONTOWER_3_TRAINER_1
	const EVENT_BEAT_POKEMONTOWER_3_TRAINER_2
	const_skip 5
	const EVENT_BEAT_POKEMONTOWER_4_TRAINER_0
	const EVENT_BEAT_POKEMONTOWER_4_TRAINER_1
	const EVENT_BEAT_POKEMONTOWER_4_TRAINER_2
	const_skip 6
	const EVENT_BEAT_POKEMONTOWER_5_TRAINER_0
	const EVENT_BEAT_POKEMONTOWER_5_TRAINER_1
	const EVENT_BEAT_POKEMONTOWER_5_TRAINER_2
	const EVENT_BEAT_POKEMONTOWER_5_TRAINER_3
	const_skip
	const EVENT_IN_PURIFIED_ZONE
	const_skip
	const EVENT_BEAT_POKEMONTOWER_6_TRAINER_0
	const EVENT_BEAT_POKEMONTOWER_6_TRAINER_1
	const EVENT_BEAT_POKEMONTOWER_6_TRAINER_2
	const_skip 3
	const EVENT_BEAT_GHOST_MAROWAK
	const_skip
	const EVENT_BEAT_POKEMONTOWER_7_TRAINER_0
	const EVENT_BEAT_POKEMONTOWER_7_TRAINER_1
	const EVENT_BEAT_POKEMONTOWER_7_TRAINER_2
	const_skip 3
	const EVENT_RESCUED_MR_FUJI_2
	const_skip 16
	const EVENT_GOT_POKE_FLUTE

; Vermilion City events
	const_next $150
	const_skip
	const EVENT_GOT_BIKE_VOUCHER
	const_skip 4
	const EVENT_SEEL_FAN_BOAST
	const EVENT_PIKACHU_FAN_BOAST
	const_skip 8
	const EVENT_2ND_LOCK_OPENED
	const EVENT_1ST_LOCK_OPENED
	const EVENT_BEAT_VERMILION_GYM_TRAINER_0
	const EVENT_BEAT_VERMILION_GYM_TRAINER_1
	const EVENT_BEAT_VERMILION_GYM_TRAINER_2
	const_skip
	const EVENT_GOT_TM24
	const EVENT_BEAT_LT_SURGE

; Celadon City events
	const_next $180
	const EVENT_GOT_TM41
	const_skip 11
	const EVENT_GOT_TM13
	const EVENT_GOT_TM48
	const EVENT_GOT_TM49
	const EVENT_GOT_TM18
	const_skip 24
	const EVENT_GOT_TM21
	const EVENT_BEAT_ERIKA
	const EVENT_BEAT_CELADON_GYM_TRAINER_0
	const EVENT_BEAT_CELADON_GYM_TRAINER_1
	const EVENT_BEAT_CELADON_GYM_TRAINER_2
	const EVENT_BEAT_CELADON_GYM_TRAINER_3
	const EVENT_BEAT_CELADON_GYM_TRAINER_4
	const EVENT_BEAT_CELADON_GYM_TRAINER_5
	const EVENT_BEAT_CELADON_GYM_TRAINER_6
	const_skip 7
	const EVENT_1B8 ; ???
	const EVENT_FOUND_ROCKET_HIDEOUT
	const EVENT_GOT_10_COINS
	const EVENT_GOT_20_COINS
	const EVENT_GOT_20_COINS_2
	const_skip 2
	const EVENT_1BF ; ???
	const_skip 32
	const EVENT_GOT_COIN_CASE

; Fuchsia City events
	const_next $238
	const EVENT_GOT_HM04
	const EVENT_GAVE_GOLD_TEETH
	const_skip 20
	const EVENT_SAFARI_GAME_OVER
	const EVENT_IN_SAFARI_ZONE
	const_skip 8
	const EVENT_GOT_TM06
	const EVENT_BEAT_KOGA
	const EVENT_BEAT_FUCHSIA_GYM_TRAINER_0
	const EVENT_BEAT_FUCHSIA_GYM_TRAINER_1
	const EVENT_BEAT_FUCHSIA_GYM_TRAINER_2
	const EVENT_BEAT_FUCHSIA_GYM_TRAINER_3
	const EVENT_BEAT_FUCHSIA_GYM_TRAINER_4
	const EVENT_BEAT_FUCHSIA_GYM_TRAINER_5

; Cinnabar Island events
	const_next $278
	const EVENT_MANSION_SWITCH_ON
	const_skip 16
	const EVENT_BEAT_MANSION_1_TRAINER_0
	const_skip 14
	const EVENT_GOT_TM38
	const EVENT_BEAT_BLAINE
	const EVENT_BEAT_CINNABAR_GYM_TRAINER_0
	const EVENT_BEAT_CINNABAR_GYM_TRAINER_1
	const EVENT_BEAT_CINNABAR_GYM_TRAINER_2
	const EVENT_BEAT_CINNABAR_GYM_TRAINER_3
	const EVENT_BEAT_CINNABAR_GYM_TRAINER_4
	const EVENT_BEAT_CINNABAR_GYM_TRAINER_5
	const EVENT_BEAT_CINNABAR_GYM_TRAINER_6
	const_skip 6
	const EVENT_2A7 ; ???
	const EVENT_CINNABAR_GYM_GATE0_UNLOCKED
	const EVENT_CINNABAR_GYM_GATE1_UNLOCKED
	const EVENT_CINNABAR_GYM_GATE2_UNLOCKED
	const EVENT_CINNABAR_GYM_GATE3_UNLOCKED
	const EVENT_CINNABAR_GYM_GATE4_UNLOCKED
	const EVENT_CINNABAR_GYM_GATE5_UNLOCKED
	const EVENT_CINNABAR_GYM_GATE6_UNLOCKED
	const_skip 40
	const EVENT_GOT_TM35
	const_skip 8
	const EVENT_GAVE_FOSSIL_TO_LAB
	const EVENT_LAB_STILL_REVIVING_FOSSIL
	const EVENT_LAB_HANDING_OVER_FOSSIL_MON

; Saffron City events
	const_next $340
	const EVENT_GOT_TM31
	const_skip 15
	const EVENT_DEFEATED_FIGHTING_DOJO
	const EVENT_BEAT_KARATE_MASTER
	const EVENT_BEAT_FIGHTING_DOJO_TRAINER_0
	const EVENT_BEAT_FIGHTING_DOJO_TRAINER_1
	const EVENT_BEAT_FIGHTING_DOJO_TRAINER_2
	const EVENT_BEAT_FIGHTING_DOJO_TRAINER_3
	const EVENT_GOT_HITMONLEE
	const EVENT_GOT_HITMONCHAN
	const_skip 8
	const EVENT_GOT_TM46
	const EVENT_BEAT_SABRINA
	const EVENT_BEAT_SAFFRON_GYM_TRAINER_0
	const EVENT_BEAT_SAFFRON_GYM_TRAINER_1
	const EVENT_BEAT_SAFFRON_GYM_TRAINER_2
	const EVENT_BEAT_SAFFRON_GYM_TRAINER_3
	const EVENT_BEAT_SAFFRON_GYM_TRAINER_4
	const EVENT_BEAT_SAFFRON_GYM_TRAINER_5
	const EVENT_BEAT_SAFFRON_GYM_TRAINER_6
	const_skip 46
	const EVENT_SILPH_CO_RECEPTIONIST_AT_DESK
	const_skip 24
	const EVENT_GOT_TM29

; Route 1 events
	const_next $3C0
	const EVENT_GOT_POTION_SAMPLE

; Route 2 events
	const_next $3D8
	const EVENT_GOT_HM05

; Route 3 events
	const_next $3E0
	const_skip 2
	const EVENT_BEAT_ROUTE_3_TRAINER_0
	const EVENT_BEAT_ROUTE_3_TRAINER_1
	const EVENT_BEAT_ROUTE_3_TRAINER_2
	const EVENT_BEAT_ROUTE_3_TRAINER_3
	const EVENT_BEAT_ROUTE_3_TRAINER_4
	const EVENT_BEAT_ROUTE_3_TRAINER_5
	const EVENT_BEAT_ROUTE_3_TRAINER_6
	const EVENT_BEAT_ROUTE_3_TRAINER_7

; Route 4 events
	const_next $3F0
	const_skip 2
	const EVENT_BEAT_ROUTE_4_TRAINER_0
	const_skip 12
	const EVENT_BOUGHT_MAGIKARP

; Route 6 events
	const_next $410
	const_skip
	const EVENT_BEAT_ROUTE_6_TRAINER_0
	const EVENT_BEAT_ROUTE_6_TRAINER_1
	const EVENT_BEAT_ROUTE_6_TRAINER_2
	const EVENT_BEAT_ROUTE_6_TRAINER_3
	const EVENT_BEAT_ROUTE_6_TRAINER_4
	const EVENT_BEAT_ROUTE_6_TRAINER_5

; Route 8 events
	const_next $430
	const_skip
	const EVENT_BEAT_ROUTE_8_TRAINER_0
	const EVENT_BEAT_ROUTE_8_TRAINER_1
	const EVENT_BEAT_ROUTE_8_TRAINER_2
	const EVENT_BEAT_ROUTE_8_TRAINER_3
	const EVENT_BEAT_ROUTE_8_TRAINER_4
	const EVENT_BEAT_ROUTE_8_TRAINER_5
	const EVENT_BEAT_ROUTE_8_TRAINER_6
	const EVENT_BEAT_ROUTE_8_TRAINER_7
	const EVENT_BEAT_ROUTE_8_TRAINER_8

; Route 9 events
	const_next $440
	const_skip
	const EVENT_BEAT_ROUTE_9_TRAINER_0
	const EVENT_BEAT_ROUTE_9_TRAINER_1
	const EVENT_BEAT_ROUTE_9_TRAINER_2
	const EVENT_BEAT_ROUTE_9_TRAINER_3
	const EVENT_BEAT_ROUTE_9_TRAINER_4
	const EVENT_BEAT_ROUTE_9_TRAINER_5
	const EVENT_BEAT_ROUTE_9_TRAINER_6
	const EVENT_BEAT_ROUTE_9_TRAINER_7
	const EVENT_BEAT_ROUTE_9_TRAINER_8

; Route 10 events
	const_next $450
	const_skip
	const EVENT_BEAT_ROUTE_10_TRAINER_0
	const EVENT_BEAT_ROUTE_10_TRAINER_1
	const EVENT_BEAT_ROUTE_10_TRAINER_2
	const EVENT_BEAT_ROUTE_10_TRAINER_3
	const EVENT_BEAT_ROUTE_10_TRAINER_4
	const EVENT_BEAT_ROUTE_10_TRAINER_5
	const_skip 2
	const EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_0
	const EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_1
	const EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_2
	const EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_3
	const EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_4
	const EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_5
	const EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_6
	const_skip
	const EVENT_BEAT_POWER_PLANT_VOLTORB_0
	const EVENT_BEAT_POWER_PLANT_VOLTORB_1
	const EVENT_BEAT_POWER_PLANT_VOLTORB_2
	const EVENT_BEAT_POWER_PLANT_VOLTORB_3
	const EVENT_BEAT_POWER_PLANT_VOLTORB_4
	const EVENT_BEAT_POWER_PLANT_VOLTORB_5
	const EVENT_BEAT_POWER_PLANT_VOLTORB_6
	const EVENT_BEAT_POWER_PLANT_VOLTORB_7
	const EVENT_BEAT_ZAPDOS

; Route 11 events
	const_next $470
	const_skip
	const EVENT_BEAT_ROUTE_11_TRAINER_0
	const EVENT_BEAT_ROUTE_11_TRAINER_1
	const EVENT_BEAT_ROUTE_11_TRAINER_2
	const EVENT_BEAT_ROUTE_11_TRAINER_3
	const EVENT_BEAT_ROUTE_11_TRAINER_4
	const EVENT_BEAT_ROUTE_11_TRAINER_5
	const EVENT_BEAT_ROUTE_11_TRAINER_6
	const EVENT_BEAT_ROUTE_11_TRAINER_7
	const EVENT_BEAT_ROUTE_11_TRAINER_8
	const EVENT_BEAT_ROUTE_11_TRAINER_9
	const_skip 4
	const EVENT_GOT_ITEMFINDER

; Route 12 events
	const_next $480
	const EVENT_GOT_TM39
	const_skip
	const EVENT_BEAT_ROUTE_12_TRAINER_0
	const EVENT_BEAT_ROUTE_12_TRAINER_1
	const EVENT_BEAT_ROUTE_12_TRAINER_2
	const EVENT_BEAT_ROUTE_12_TRAINER_3
	const EVENT_BEAT_ROUTE_12_TRAINER_4
	const EVENT_BEAT_ROUTE_12_TRAINER_5
	const EVENT_BEAT_ROUTE_12_TRAINER_6
	const_skip 5
	const EVENT_FIGHT_ROUTE12_SNORLAX
	const EVENT_BEAT_ROUTE12_SNORLAX

; Route 13 events
	const_next $490
	const_skip
	const EVENT_BEAT_ROUTE_13_TRAINER_0
	const EVENT_BEAT_ROUTE_13_TRAINER_1
	const EVENT_BEAT_ROUTE_13_TRAINER_2
	const EVENT_BEAT_ROUTE_13_TRAINER_3
	const EVENT_BEAT_ROUTE_13_TRAINER_4
	const EVENT_BEAT_ROUTE_13_TRAINER_5
	const EVENT_BEAT_ROUTE_13_TRAINER_6
	const EVENT_BEAT_ROUTE_13_TRAINER_7
	const EVENT_BEAT_ROUTE_13_TRAINER_8
	const EVENT_BEAT_ROUTE_13_TRAINER_9

; Route 14 events
	const_next $4A0
	const_skip
	const EVENT_BEAT_ROUTE_14_TRAINER_0
	const EVENT_BEAT_ROUTE_14_TRAINER_1
	const EVENT_BEAT_ROUTE_14_TRAINER_2
	const EVENT_BEAT_ROUTE_14_TRAINER_3
	const EVENT_BEAT_ROUTE_14_TRAINER_4
	const EVENT_BEAT_ROUTE_14_TRAINER_5
	const EVENT_BEAT_ROUTE_14_TRAINER_6
	const EVENT_BEAT_ROUTE_14_TRAINER_7
	const EVENT_BEAT_ROUTE_14_TRAINER_8
	const EVENT_BEAT_ROUTE_14_TRAINER_9

; Route 15 events
	const_next $4B0
	const EVENT_GOT_EXP_ALL
	const EVENT_BEAT_ROUTE_15_TRAINER_0
	const EVENT_BEAT_ROUTE_15_TRAINER_1
	const EVENT_BEAT_ROUTE_15_TRAINER_2
	const EVENT_BEAT_ROUTE_15_TRAINER_3
	const EVENT_BEAT_ROUTE_15_TRAINER_4
	const EVENT_BEAT_ROUTE_15_TRAINER_5
	const EVENT_BEAT_ROUTE_15_TRAINER_6
	const EVENT_BEAT_ROUTE_15_TRAINER_7
	const EVENT_BEAT_ROUTE_15_TRAINER_8
	const EVENT_BEAT_ROUTE_15_TRAINER_9

; Route 16 events
	const_next $4C0
	const_skip
	const EVENT_BEAT_ROUTE_16_TRAINER_0
	const EVENT_BEAT_ROUTE_16_TRAINER_1
	const EVENT_BEAT_ROUTE_16_TRAINER_2
	const EVENT_BEAT_ROUTE_16_TRAINER_3
	const EVENT_BEAT_ROUTE_16_TRAINER_4
	const EVENT_BEAT_ROUTE_16_TRAINER_5
	const_skip
	const EVENT_FIGHT_ROUTE16_SNORLAX
	const EVENT_BEAT_ROUTE16_SNORLAX
	const_skip 4
	const EVENT_GOT_HM02
	const EVENT_RESCUED_MR_FUJI

; Route 17 events
	const_next $4D0
	const_skip
	const EVENT_BEAT_ROUTE_17_TRAINER_0
	const EVENT_BEAT_ROUTE_17_TRAINER_1
	const EVENT_BEAT_ROUTE_17_TRAINER_2
	const EVENT_BEAT_ROUTE_17_TRAINER_3
	const EVENT_BEAT_ROUTE_17_TRAINER_4
	const EVENT_BEAT_ROUTE_17_TRAINER_5
	const EVENT_BEAT_ROUTE_17_TRAINER_6
	const EVENT_BEAT_ROUTE_17_TRAINER_7
	const EVENT_BEAT_ROUTE_17_TRAINER_8
	const EVENT_BEAT_ROUTE_17_TRAINER_9

; Route 18 events
	const_next $4E0
	const_skip
	const EVENT_BEAT_ROUTE_18_TRAINER_0
	const EVENT_BEAT_ROUTE_18_TRAINER_1
	const EVENT_BEAT_ROUTE_18_TRAINER_2

; Route 19 events
	const_next $4F0
	const_skip
	const EVENT_BEAT_ROUTE_19_TRAINER_0
	const EVENT_BEAT_ROUTE_19_TRAINER_1
	const EVENT_BEAT_ROUTE_19_TRAINER_2
	const EVENT_BEAT_ROUTE_19_TRAINER_3
	const EVENT_BEAT_ROUTE_19_TRAINER_4
	const EVENT_BEAT_ROUTE_19_TRAINER_5
	const EVENT_BEAT_ROUTE_19_TRAINER_6
	const EVENT_BEAT_ROUTE_19_TRAINER_7
	const EVENT_BEAT_ROUTE_19_TRAINER_8
	const EVENT_BEAT_ROUTE_19_TRAINER_9

; Route 20 events
	const_next $500
	const EVENT_IN_SEAFOAM_ISLANDS
	const EVENT_BEAT_ROUTE_20_TRAINER_0
	const EVENT_BEAT_ROUTE_20_TRAINER_1
	const EVENT_BEAT_ROUTE_20_TRAINER_2
	const EVENT_BEAT_ROUTE_20_TRAINER_3
	const EVENT_BEAT_ROUTE_20_TRAINER_4
	const EVENT_BEAT_ROUTE_20_TRAINER_5
	const EVENT_BEAT_ROUTE_20_TRAINER_6
	const EVENT_BEAT_ROUTE_20_TRAINER_7
	const EVENT_BEAT_ROUTE_20_TRAINER_8
	const EVENT_BEAT_ROUTE_20_TRAINER_9
	const_skip 3
	const EVENT_SEAFOAM1_BOULDER1_DOWN_HOLE
	const EVENT_SEAFOAM1_BOULDER2_DOWN_HOLE

; Route 21 events
	const_next $510
	const_skip
	const EVENT_BEAT_ROUTE_21_TRAINER_0
	const EVENT_BEAT_ROUTE_21_TRAINER_1
	const EVENT_BEAT_ROUTE_21_TRAINER_2
	const EVENT_BEAT_ROUTE_21_TRAINER_3
	const EVENT_BEAT_ROUTE_21_TRAINER_4
	const EVENT_BEAT_ROUTE_21_TRAINER_5
	const EVENT_BEAT_ROUTE_21_TRAINER_6
	const EVENT_BEAT_ROUTE_21_TRAINER_7
	const EVENT_BEAT_ROUTE_21_TRAINER_8

; Route 22 events
	const_next $520
	const EVENT_1ST_ROUTE22_RIVAL_BATTLE
	const EVENT_2ND_ROUTE22_RIVAL_BATTLE
	const_skip 3
	const EVENT_BEAT_ROUTE22_RIVAL_1ST_BATTLE
	const EVENT_BEAT_ROUTE22_RIVAL_2ND_BATTLE
	const EVENT_ROUTE22_RIVAL_WANTS_BATTLE

; Route 23 events
	const_next $530
	const EVENT_PASSED_CASCADEBADGE_CHECK
	const EVENT_PASSED_THUNDERBADGE_CHECK
	const EVENT_PASSED_RAINBOWBADGE_CHECK
	const EVENT_PASSED_SOULBADGE_CHECK
	const EVENT_PASSED_MARSHBADGE_CHECK
	const EVENT_PASSED_VOLCANOBADGE_CHECK
	const EVENT_PASSED_EARTHBADGE_CHECK
	const_skip
	const EVENT_VICTORY_ROAD_2_BOULDER_ON_SWITCH1
	const EVENT_BEAT_VICTORY_ROAD_2_TRAINER_0
	const EVENT_BEAT_VICTORY_ROAD_2_TRAINER_1
	const EVENT_BEAT_VICTORY_ROAD_2_TRAINER_2
	const EVENT_BEAT_VICTORY_ROAD_2_TRAINER_3
	const EVENT_BEAT_VICTORY_ROAD_2_TRAINER_4
	const EVENT_BEAT_MOLTRES
	const EVENT_VICTORY_ROAD_2_BOULDER_ON_SWITCH2

; Route 24 events
	const_next $540
	const EVENT_GOT_NUGGET
	const EVENT_BEAT_ROUTE24_ROCKET
	const EVENT_BEAT_ROUTE_24_TRAINER_0
	const EVENT_BEAT_ROUTE_24_TRAINER_1
	const EVENT_BEAT_ROUTE_24_TRAINER_2
	const EVENT_BEAT_ROUTE_24_TRAINER_3
	const EVENT_BEAT_ROUTE_24_TRAINER_4
	const EVENT_BEAT_ROUTE_24_TRAINER_5
	const_skip
	const EVENT_NUGGET_REWARD_AVAILABLE

; Route 25 events
	const_next $550
	const EVENT_MET_BILL
	const EVENT_BEAT_ROUTE_25_TRAINER_0
	const EVENT_BEAT_ROUTE_25_TRAINER_1
	const EVENT_BEAT_ROUTE_25_TRAINER_2
	const EVENT_BEAT_ROUTE_25_TRAINER_3
	const EVENT_BEAT_ROUTE_25_TRAINER_4
	const EVENT_BEAT_ROUTE_25_TRAINER_5
	const EVENT_BEAT_ROUTE_25_TRAINER_6
	const EVENT_BEAT_ROUTE_25_TRAINER_7
	const EVENT_BEAT_ROUTE_25_TRAINER_8
	const_skip
	const EVENT_USED_CELL_SEPARATOR_ON_BILL
	const EVENT_GOT_SS_TICKET
	const EVENT_MET_BILL_2
	const EVENT_BILL_SAID_USE_CELL_SEPARATOR
	const EVENT_LEFT_BILLS_HOUSE_AFTER_HELPING

; Viridian Forest events
	const_next $560
	const_skip 2
	const EVENT_BEAT_VIRIDIAN_FOREST_TRAINER_0
	const EVENT_BEAT_VIRIDIAN_FOREST_TRAINER_1
	const EVENT_BEAT_VIRIDIAN_FOREST_TRAINER_2

; Mt. Moon events
	const_next $570
	const_skip
	const EVENT_BEAT_MT_MOON_1_TRAINER_0
	const EVENT_BEAT_MT_MOON_1_TRAINER_1
	const EVENT_BEAT_MT_MOON_1_TRAINER_2
	const EVENT_BEAT_MT_MOON_1_TRAINER_3
	const EVENT_BEAT_MT_MOON_1_TRAINER_4
	const EVENT_BEAT_MT_MOON_1_TRAINER_5
	const EVENT_BEAT_MT_MOON_1_TRAINER_6
	const_skip
	const EVENT_BEAT_MT_MOON_EXIT_SUPER_NERD
	const EVENT_BEAT_MT_MOON_3_TRAINER_0
	const EVENT_BEAT_MT_MOON_3_TRAINER_1
	const EVENT_BEAT_MT_MOON_3_TRAINER_2
	const EVENT_BEAT_MT_MOON_3_TRAINER_3
	const EVENT_GOT_DOME_FOSSIL
	const EVENT_GOT_HELIX_FOSSIL

; S.S. Anne events
	const_next $5C0
	const_skip 4
	const EVENT_BEAT_SS_ANNE_5_TRAINER_0
	const EVENT_BEAT_SS_ANNE_5_TRAINER_1
	const_skip 26
	const EVENT_GOT_HM01
	const EVENT_RUBBED_CAPTAINS_BACK
	const EVENT_SS_ANNE_LEFT
	const EVENT_WALKED_PAST_GUARD_AFTER_SS_ANNE_LEFT
	const EVENT_STARTED_WALKING_OUT_OF_DOCK
	const EVENT_WALKED_OUT_OF_DOCK
	const_skip 11
	const EVENT_BEAT_SS_ANNE_8_TRAINER_0
	const EVENT_BEAT_SS_ANNE_8_TRAINER_1
	const EVENT_BEAT_SS_ANNE_8_TRAINER_2
	const EVENT_BEAT_SS_ANNE_8_TRAINER_3
	const_skip 12
	const EVENT_BEAT_SS_ANNE_9_TRAINER_0
	const EVENT_BEAT_SS_ANNE_9_TRAINER_1
	const EVENT_BEAT_SS_ANNE_9_TRAINER_2
	const EVENT_BEAT_SS_ANNE_9_TRAINER_3
	const_skip 12
	const EVENT_BEAT_SS_ANNE_10_TRAINER_0
	const EVENT_BEAT_SS_ANNE_10_TRAINER_1
	const EVENT_BEAT_SS_ANNE_10_TRAINER_2
	const EVENT_BEAT_SS_ANNE_10_TRAINER_3
	const EVENT_BEAT_SS_ANNE_10_TRAINER_4
	const EVENT_BEAT_SS_ANNE_10_TRAINER_5

; Victory Road 3F events
	const_next $660
	const EVENT_VICTORY_ROAD_3_BOULDER_ON_SWITCH1
	const EVENT_BEAT_VICTORY_ROAD_3_TRAINER_0
	const EVENT_BEAT_VICTORY_ROAD_3_TRAINER_1
	const EVENT_BEAT_VICTORY_ROAD_3_TRAINER_2
	const EVENT_BEAT_VICTORY_ROAD_3_TRAINER_3
	const_skip
	const EVENT_VICTORY_ROAD_3_BOULDER_ON_SWITCH2

; Rocket Hideout events
	const_next $670
	const_skip
	const EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_0
	const EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_1
	const EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_2
	const EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_3
	const EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_4
	const_skip
	const EVENT_677 ; ???
	const_skip 7
	const EVENT_67F ; ???
	const_skip
	const EVENT_BEAT_ROCKET_HIDEOUT_2_TRAINER_0
	const_skip 15
	const EVENT_BEAT_ROCKET_HIDEOUT_3_TRAINER_0
	const EVENT_BEAT_ROCKET_HIDEOUT_3_TRAINER_1
	const_skip 15
	const EVENT_BEAT_ROCKET_HIDEOUT_4_TRAINER_0
	const EVENT_BEAT_ROCKET_HIDEOUT_4_TRAINER_1
	const EVENT_BEAT_ROCKET_HIDEOUT_4_TRAINER_2
	const EVENT_ROCKET_HIDEOUT_4_DOOR_UNLOCKED
	const EVENT_ROCKET_DROPPED_LIFT_KEY
	const EVENT_BEAT_ROCKET_HIDEOUT_GIOVANNI

; Silph Co. events
	const_next $6F0
	const_skip 2
	const EVENT_BEAT_SILPH_CO_2F_TRAINER_0
	const EVENT_BEAT_SILPH_CO_2F_TRAINER_1
	const EVENT_BEAT_SILPH_CO_2F_TRAINER_2
	const EVENT_BEAT_SILPH_CO_2F_TRAINER_3
	const_skip 7
	const EVENT_SILPH_CO_2_UNLOCKED_DOOR1
	const EVENT_SILPH_CO_2_UNLOCKED_DOOR2
	const EVENT_GOT_TM36
	const_skip 2
	const EVENT_BEAT_SILPH_CO_3F_TRAINER_0
	const EVENT_BEAT_SILPH_CO_3F_TRAINER_1
	const_skip 4
	const EVENT_SILPH_CO_3_UNLOCKED_DOOR1
	const EVENT_SILPH_CO_3_UNLOCKED_DOOR2
	const_skip 8
	const EVENT_BEAT_SILPH_CO_4F_TRAINER_0
	const EVENT_BEAT_SILPH_CO_4F_TRAINER_1
	const EVENT_BEAT_SILPH_CO_4F_TRAINER_2
	const_skip 3
	const EVENT_SILPH_CO_4_UNLOCKED_DOOR1
	const EVENT_SILPH_CO_4_UNLOCKED_DOOR2
	const_skip 8
	const EVENT_BEAT_SILPH_CO_5F_TRAINER_0
	const EVENT_BEAT_SILPH_CO_5F_TRAINER_1
	const EVENT_BEAT_SILPH_CO_5F_TRAINER_2
	const EVENT_BEAT_SILPH_CO_5F_TRAINER_3
	const_skip 2
	const EVENT_SILPH_CO_5_UNLOCKED_DOOR1
	const EVENT_SILPH_CO_5_UNLOCKED_DOOR2
	const EVENT_SILPH_CO_5_UNLOCKED_DOOR3
	const_skip 11
	const EVENT_BEAT_SILPH_CO_6F_TRAINER_0
	const EVENT_BEAT_SILPH_CO_6F_TRAINER_1
	const EVENT_BEAT_SILPH_CO_6F_TRAINER_2
	const_skip 6
	const EVENT_SILPH_CO_6_UNLOCKED_DOOR
	const EVENT_BEAT_SILPH_CO_RIVAL
	const_skip 4
	const EVENT_BEAT_SILPH_CO_7F_TRAINER_0
	const EVENT_BEAT_SILPH_CO_7F_TRAINER_1
	const EVENT_BEAT_SILPH_CO_7F_TRAINER_2
	const EVENT_BEAT_SILPH_CO_7F_TRAINER_3
	const_skip 3
	const EVENT_SILPH_CO_7_UNLOCKED_DOOR1
	const EVENT_SILPH_CO_7_UNLOCKED_DOOR2
	const EVENT_SILPH_CO_7_UNLOCKED_DOOR3
	const_skip 3
	const EVENT_BEAT_SILPH_CO_8F_TRAINER_0
	const EVENT_BEAT_SILPH_CO_8F_TRAINER_1
	const EVENT_BEAT_SILPH_CO_8F_TRAINER_2
	const_skip 3
	const EVENT_SILPH_CO_8_UNLOCKED_DOOR
	const_skip 9
	const EVENT_BEAT_SILPH_CO_9F_TRAINER_0
	const EVENT_BEAT_SILPH_CO_9F_TRAINER_1
	const EVENT_BEAT_SILPH_CO_9F_TRAINER_2
	const_skip 3
	const EVENT_SILPH_CO_9_UNLOCKED_DOOR1
	const EVENT_SILPH_CO_9_UNLOCKED_DOOR2
	const EVENT_SILPH_CO_9_UNLOCKED_DOOR3
	const EVENT_SILPH_CO_9_UNLOCKED_DOOR4
	const_skip 5
	const EVENT_BEAT_SILPH_CO_10F_TRAINER_0
	const EVENT_BEAT_SILPH_CO_10F_TRAINER_1
	const_skip 5
	const EVENT_SILPH_CO_10_UNLOCKED_DOOR
	const_skip 11
	const EVENT_BEAT_SILPH_CO_11F_TRAINER_0
	const EVENT_BEAT_SILPH_CO_11F_TRAINER_1
	const_skip 2
	const EVENT_SILPH_CO_11_UNLOCKED_DOOR
	const_skip 4
	const EVENT_GOT_MASTER_BALL
	const_skip
	const EVENT_BEAT_SILPH_CO_GIOVANNI

; Pokémon Mansion events
	const_next $800
	const_skip
	const EVENT_BEAT_MANSION_2_TRAINER_0
	const_skip 15
	const EVENT_BEAT_MANSION_3_TRAINER_0
	const EVENT_BEAT_MANSION_3_TRAINER_1
	const_skip 14
	const EVENT_BEAT_MANSION_4_TRAINER_0
	const EVENT_BEAT_MANSION_4_TRAINER_1

; Safari Zone events
	const_next $880
	const EVENT_GOT_HM03

; Cerulean Cave events
	const_next $8C0
	const_skip
	const EVENT_BEAT_MEWTWO

; Indigo Plateau events
	const_next $8E0
DEF INDIGO_PLATEAU_EVENTS_START EQU const_value
	const_skip
	const EVENT_BEAT_LORELEIS_ROOM_TRAINER_0
	const_skip 4
	const EVENT_AUTOWALKED_INTO_LORELEIS_ROOM
	const_skip 2
	const EVENT_BEAT_BRUNOS_ROOM_TRAINER_0
	const_skip 4
	const EVENT_AUTOWALKED_INTO_BRUNOS_ROOM
	const_skip 2
	const EVENT_BEAT_AGATHAS_ROOM_TRAINER_0
	const_skip 4
	const EVENT_AUTOWALKED_INTO_AGATHAS_ROOM
	const_skip 2
	const EVENT_BEAT_LANCES_ROOM_TRAINER_0
	const_skip 4
	const EVENT_BEAT_LANCE
	const EVENT_LANCES_ROOM_LOCK_DOOR
	const_skip
	const EVENT_BEAT_CHAMPION_RIVAL
	const_skip 5
	const_skip
DEF INDIGO_PLATEAU_EVENTS_END EQU const_value - 1

; Victory Road 1F events
	const_next $910
	const_skip
	const EVENT_BEAT_VICTORY_ROAD_1_TRAINER_0
	const EVENT_BEAT_VICTORY_ROAD_1_TRAINER_1
	const_skip 4
	const EVENT_VICTORY_ROAD_1_BOULDER_ON_SWITCH

; Rock Tunnel events
	const_next $9B0
	const_skip
	const EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_0
	const EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_1
	const EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_2
	const EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_3
	const EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_4
	const EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_5
	const EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_6
	const EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_7

; Seafoam Islands events
	const_next $9C0
	const EVENT_SEAFOAM2_BOULDER1_DOWN_HOLE
	const EVENT_SEAFOAM2_BOULDER2_DOWN_HOLE
	const_skip 6
	const EVENT_SEAFOAM3_BOULDER1_DOWN_HOLE
	const EVENT_SEAFOAM3_BOULDER2_DOWN_HOLE
	const_skip 6
	const EVENT_SEAFOAM4_BOULDER1_DOWN_HOLE
	const EVENT_SEAFOAM4_BOULDER2_DOWN_HOLE
	const_skip 8
	const EVENT_BEAT_ARTICUNO

; End of events
	const_next $A00
DEF NUM_EVENTS EQU const_value
