; joypad buttons
	const_def
	const BIT_A_BUTTON
	const BIT_B_BUTTON
	const BIT_SELECT
	const BIT_START
	const BIT_D_RIGHT
	const BIT_D_LEFT
	const BIT_D_UP
	const BIT_D_DOWN

DEF NO_INPUT EQU 0
DEF A_BUTTON EQU 1 << BIT_A_BUTTON
DEF B_BUTTON EQU 1 << BIT_B_BUTTON
DEF SELECT   EQU 1 << BIT_SELECT
DEF START    EQU 1 << BIT_START
DEF D_RIGHT  EQU 1 << BIT_D_RIGHT
DEF D_LEFT   EQU 1 << BIT_D_LEFT
DEF D_UP     EQU 1 << BIT_D_UP
DEF D_DOWN   EQU 1 << BIT_D_DOWN
