const_value = 1

	const RHYDON       ; $01
	const KANGASKHAN   ; $02
	const NIDORAN_M    ; $03
	const CLEFAIRY     ; $04
	const SPEAROW      ; $05
	const VOLTORB      ; $06
	const NIDOKING     ; $07
	const SLOWBRO      ; $08
	const IVYSAUR      ; $09
	const EXEGGUTOR    ; $0A
	const LICKITUNG    ; $0B
	const EXEGGCUTE    ; $0C
	const GRIMER       ; $0D
	const GENGAR       ; $0E
	const NIDORAN_F    ; $0F
	const NIDOQUEEN    ; $10
	const CUBONE       ; $11
	const RHYHORN      ; $12
	const LAPRAS       ; $13
	const ARCANINE     ; $14
	const MEW          ; $15
	const GYARADOS     ; $16
	const SHELLDER     ; $17
	const TENTACOOL    ; $18
	const GASTLY       ; $19
	const SCYTHER      ; $1A
	const STARYU       ; $1B
	const BLASTOISE    ; $1C
	const PINSIR       ; $1D
	const TANGELA      ; $1E
	const CHIKORITA    ; $1F
	const BAYLEEF      ; $20
	const GROWLITHE    ; $21
	const ONIX         ; $22
	const FEAROW       ; $23
	const PIDGEY       ; $24
	const SLOWPOKE     ; $25
	const KADABRA      ; $26
	const GRAVELER     ; $27
	const CHANSEY      ; $28
	const MACHOKE      ; $29
	const MR_MIME      ; $2A
	const HITMONLEE    ; $2B
	const HITMONCHAN   ; $2C
	const ARBOK        ; $2D
	const PARASECT     ; $2E
	const PSYDUCK      ; $2F
	const DROWZEE      ; $30
	const GOLEM        ; $31
	const MEGANIUM     ; $32
	const MAGMAR       ; $33
	const CYNDAQUIL    ; $34
	const ELECTABUZZ   ; $35
	const MAGNETON     ; $36
	const KOFFING      ; $37
	const QUILAVA      ; $38
	const MANKEY       ; $39
	const SEEL         ; $3A
	const DIGLETT      ; $3B
	const TAUROS       ; $3C
	const TYPHLOSION   ; $3D
	const TOTODILE     ; $3E
	const CROCONAW     ; $3F
	const FARFETCHD    ; $40
	const VENONAT      ; $41
	const DRAGONITE    ; $42
	const FERALIGATR   ; $43
	const SENTRET      ; $44
	const FURRET       ; $45
	const DODUO        ; $46
	const POLIWAG      ; $47
	const JYNX         ; $48
	const MOLTRES      ; $49
	const ARTICUNO     ; $4A
	const ZAPDOS       ; $4B
	const DITTO        ; $4C
	const MEOWTH       ; $4D
	const KRABBY       ; $4E
	const HOOTHOOT     ; $4F
	const NOCTOWL      ; $50
	const LEDYBA       ; $51
	const VULPIX       ; $52
	const NINETALES    ; $53
	const PIKACHU      ; $54
	const RAICHU       ; $55
	const LEDIAN       ; $56
	const SPINARAK     ; $57
	const DRATINI      ; $58
	const DRAGONAIR    ; $59
	const KABUTO       ; $5A
	const KABUTOPS     ; $5B
	const HORSEA       ; $5C
	const SEADRA       ; $5D
	const ARIADOS      ; $5E
	const CROBAT       ; $5F
	const SANDSHREW    ; $60
	const SANDSLASH    ; $61
	const OMANYTE      ; $62
	const OMASTAR      ; $63
	const JIGGLYPUFF   ; $64
	const WIGGLYTUFF   ; $65
	const EEVEE        ; $66
	const FLAREON      ; $67
	const JOLTEON      ; $68
	const VAPOREON     ; $69
	const MACHOP       ; $6A
	const ZUBAT        ; $6B
	const EKANS        ; $6C
	const PARAS        ; $6D
	const POLIWHIRL    ; $6E
	const POLIWRATH    ; $6F
	const WEEDLE       ; $70
	const KAKUNA       ; $71
	const BEEDRILL     ; $72
	const CHINCHOU     ; $73
	const DODRIO       ; $74
	const PRIMEAPE     ; $75
	const DUGTRIO      ; $76
	const VENOMOTH     ; $77
	const DEWGONG      ; $78
	const LANTURN      ; $79
	const PICHU        ; $7A
	const CATERPIE     ; $7B
	const METAPOD      ; $7C
	const BUTTERFREE   ; $7D
	const MACHAMP      ; $7E
	const CLEFFA       ; $7F
	const GOLDUCK      ; $80
	const HYPNO        ; $81
	const GOLBAT       ; $82
	const MEWTWO       ; $83
	const SNORLAX      ; $84
	const MAGIKARP     ; $85
	const IGGLYBUFF    ; $86
	const TOGEPI       ; $87
	const MUK          ; $88
	const TOGETIC      ; $8A
	const KINGLER      ; $8A
	const CLOYSTER     ; $8B
	const NATU         ; $8C
	const ELECTRODE    ; $8D
	const CLEFABLE     ; $8E
	const WEEZING      ; $8F
	const PERSIAN      ; $90
	const MAROWAK      ; $91
	const XATU         ; $92
	const HAUNTER      ; $93
	const ABRA         ; $94
	const ALAKAZAM     ; $95
	const PIDGEOTTO    ; $96
	const PIDGEOT      ; $97
	const STARMIE      ; $98
	const BULBASAUR    ; $99
	const VENUSAUR     ; $9A
	const TENTACRUEL   ; $9B
	const MAREEP       ; $9C
	const GOLDEEN      ; $9D
	const SEAKING      ; $9E
	const FLAAFFY      ; $9F
	const AMPHAROS     ; $A0
	const BELLOSSOM    ; $A1
	const MARILL       ; $A2
	const PONYTA       ; $A3
	const RAPIDASH     ; $A4
	const RATTATA      ; $A5
	const RATICATE     ; $A6
	const NIDORINO     ; $A7
	const NIDORINA     ; $A8
	const GEODUDE      ; $A9
	const PORYGON      ; $AA
	const AERODACTYL   ; $AB
	const AZUMARILL    ; $AC
	const MAGNEMITE    ; $AD
	const SUDOWOODO    ; $AE
	const POLITOED     ; $AF
	const CHARMANDER   ; $B0
	const SQUIRTLE     ; $B1
	const CHARMELEON   ; $B2
	const WARTORTLE    ; $B3
	const CHARIZARD    ; $B4
	const HOPPIP       ; $B5
	const FOSSIL_KABUTOPS   ; $B6
	const FOSSIL_AERODACTYL ; $B7
	const MON_GHOST    ; $B8
	const ODDISH       ; $B9
	const GLOOM        ; $BA
	const VILEPLUME    ; $BB
	const BELLSPROUT   ; $BC
	const WEEPINBELL   ; $BD
	const VICTREEBEL   ; $BE
	const SKIPLOOM     ; $BF
	const JUMPLUFF     ; $C0
	const AIPOM        ; $C1
	const SUNKERN      ; $C2
	const SUNFLORA     ; $C3
	const YANMA        ; $C4
	const WOOPER       ; $C5
	const QUAGSIRE     ; $C6
	const ESPEON       ; $C7
	const UMBREON      ; $C8
	const MURKROW      ; $C9
	const SLOWKING     ; $CA
	const MISDREAVUS   ; $CB
	const UNOWN        ; $CC
	const WOBBUFFET    ; $CD
	const GIRAFARIG    ; $CE
	const PINECO       ; $CF
	const FORRETRESS   ; $D0
	const DUNSPARCE    ; $D1
	const GLIGAR       ; $D2
	const STEELIX      ; $D3
	const SNUBBULL     ; $D4
	const GRANBULL     ; $D5
	const QWILFISH     ; $D6
	const SCIZOR       ; $D7
	const SHUCKLE      ; $D8
	const HERACROSS    ; $D9
	const SNEASEL      ; $DA
	const TEDDIURSA    ; $DB
	const URSARING     ; $DC
	const SLUGMA       ; $DD
	const MAGCARGO     ; $DE
	const SWINUB       ; $DF
	const PILOSWINE    ; $E0
	const CORSOLA      ; $E1
	const REMORAID     ; $E2
	const OCTILLERY    ; $E3
	const DELIBIRD     ; $E4
	const MANTINE      ; $E5
	const SKARMORY     ; $E6
	const HOUNDOUR     ; $E7
	const HOUNDOOM     ; $E8
	const KINGDRA      ; $E9
	const PHANPY       ; $EA
	const DONPHAN      ; $EB
	const PORYGON2     ; $EC
	const STANTLER     ; $ED
	const SMEARGLE     ; $EE
	const TYROGUE      ; $EF
	const HITMONTOP    ; $F0
	const SMOOCHUM     ; $F1
	const ELEKID       ; $F2
	const MAGBY        ; $F3
	const MILTANK      ; $F4
	const BLISSEY      ; $F5
	const RAIKOU       ; $F6
	const ENTEI        ; $F7
	const SUICUNE      ; $F8
	const LARVITAR     ; $F9
	const PUPITAR      ; $FA
	const TYRANITAR    ; $FB
	const LUGIA        ; $FC
	const HO_OH        ; $FD
	const CELEBI       ; $FE
	const TREECKO      ; $FF
	const GROVYLE      ; $100
	const SCEPTILE     ; $101
	const TORCHIC      ; $102
	const COMBUSKEN    ; $103
	const BLAZIKEN     ; $104
	const MUDKIP       ; $105
	const MARSHTOMP    ; $106
	const SWAMPERT     ; $107

