; pokemon ids
; indexes for:
; - MonsterNames (see data/pokemon/names.asm)
; - EvosMovesPointerTable (see data/pokemon/evos_moves.asm)
; - CryData (see data/pokemon/cries.asm)
; - PokedexOrder (see data/pokemon/dex_order.asm)
; - PokedexEntryPointers (see data/pokemon/dex_entries.asm)
	const_def
	const NO_MON             
	const BULBASAUR          
	const IVYSAUR            
	const VENUSAUR        
	const MVENUSAUR   
	const CHARMANDER         
	const CHARMELEON         
	const CHARIZARD
	const MCHARIZARDX
	const MCHARIZARDY          
	const SQUIRTLE           
	const WARTORTLE          
	const BLASTOISE
	const MBLASTOISE          
	const CATERPIE           
	const METAPOD            
	const BUTTERFREE         
	const WEEDLE             
	const KAKUNA             
	const BEEDRILL 
	const MBEEDRILL          
	const PIDGEY             
	const PIDGEOTTO          
	const PIDGEOT
	const MPIDGEOT            
	const RATTATA            
	const RATICATE 
	const A_RATTATA
	const A_RATICATE          
	const SPEAROW            
	const FEAROW             
	const EKANS              
	const ARBOK
	const PICHU              
	const PIKACHU            
	const RAICHU
	const A_RAICHU             
	const SANDSHREW          
	const SANDSLASH
	const A_SANDSHREW
	const A_SANDSLASH          
	const NIDORAN_F          
	const NIDORINA           
	const NIDOQUEEN          
	const NIDORAN_M          
	const NIDORINO           
	const NIDOKING
	const CLEFFA           
	const CLEFAIRY           
	const CLEFABLE
	const MCLEFABLE           
	const VULPIX             
	const NINETALES
	const AVULPIX
	const ANINETALES
	const IGGLYBUFF          
	const JIGGLYPUFF         
	const WIGGLYTUFF         
	const ZUBAT              
	const GOLBAT
	const CROBAT             
	const ODDISH             
	const GLOOM              
	const VILEPLUME
	const BELLOSSOM          
	const PARAS              
	const PARASECT           
	const VENONAT            
	const VENOMOTH           
	const DIGLETT            
	const DUGTRIO
	const A_DIGLETT
	const A_DUGTRIO
	const WIGLETT
	const WUGTRIO            
	const MEOWTH             
	const PERSIAN
	const A_MEOWTH
	const A_PERSIAN
	const G_MEOWTH
	const PERRSERKER            
	const PSYDUCK            
	const GOLDUCK            
	const MANKEY             
	const PRIMEAPE
	const ANNIHILAPE           
	const GROWLITHE          
	const ARCANINE
	const H_GROWLITHE
	const H_ARCANINE           
	const POLIWAG            
	const POLIWHIRL          
	const POLIWRATH
	const POLITOED          
	const ABRA               
	const KADABRA            
	const ALAKAZAM
	const MALAKAZAM           
	const MACHOP             
	const MACHOKE            
	const MACHAMP            
	const BELLSPROUT         
	const WEEPINBELL         
	const VICTREEBEL
	const MVICTREEBEL         
	const TENTACOOL          
	const TENTACRUEL
	const TOEDSCOOL
	const TOEDSCRUEL         
	const GEODUDE            
	const GRAVELER           
	const GOLEM
	const A_GEODUDE            
	const A_GRAVELER           
	const A_GOLEM                   
	const PONYTA             
	const RAPIDASH
	const G_PONYTA             
	const G_RAPIDASH            
	const SLOWPOKE           
	const SLOWBRO
	const SLOWKING
	const G_SLOWPOKE           
	const G_SLOWBRO
	const G_SLOWKING
	const MSLOWBRO            
	const MAGNEMITE          
	const MAGNETON
	const MAGNEZONE           
	const FARFETCHD
	const G_FARFETCHD
	const SIRFETCHD         
	const DODUO              
	const DODRIO             
	const SEEL               
	const DEWGONG            
	const GRIMER             
	const MUK
	const A_GRIMER
	const A_MUK                
	const SHELLDER           
	const CLOYSTER           
	const GASTLY             
	const HAUNTER            
	const GENGAR
	const MGENGAR             
	const ONIX
	const STEELIX
	const MSTEELIX             
	const DROWZEE            
	const HYPNO              
	const KRABBY             
	const KINGLER            
	const VOLTORB            
	const ELECTRODE
	const H_VOLTORB            
	const H_ELECTRODE       
	const EXEGGCUTE          
	const EXEGGUTOR
	const A_EXEGGUTOR       
	const CUBONE             
	const MAROWAK
	const A_MAROWAK         
	const HITMONLEE          
	const HITMONCHAN
	const HITMONTOP         
	const LICKITUNG
	const LICKILICKY          
	const KOFFING            
	const WEEZING
	const G_WEEZING            
	const RHYHORN            
	const RHYDON
	const RHYPERIOR
	const HAPPINY             
	const CHANSEY
	const BLISSEY            
	const TANGELA
	const TANGROWTH            
	const KANGASKHAN
	const MKANGASKHAN         
	const HORSEA             
	const SEADRA
	const KINGDRA             
	const GOLDEEN            
	const SEAKING            
	const STARYU             
	const STARMIE
	const MSTARMIE
	const MIME_JR            
	const MR_MIME
	const G_MR_MIME
	const MR_RIME           
	const SCYTHER
	const SCIZOR
	const MSCIZOR
	const KLEAVOR
	const SMOOCHUM            
	const JYNX    
	const ELEKID           
	const ELECTABUZZ
	const ELECTIVIRE
	const MAGBY         
	const MAGMAR
	const MAGMORTAR             
	const PINSIR
	const MPINSIR             
	const TAUROS 
	const P_TAUROSC
	const P_TAUROSA
	const P_TAUROSB            
	const MAGIKARP           
	const GYARADOS
	const MGYARADOS           
	const LAPRAS             
	const DITTO              
	const EEVEE              
	const VAPOREON           
	const JOLTEON            
	const FLAREON
	const ESPEON           
	const UMBREON            
	const LEAFEON             
	const GLACEON           
	const SYLVEON             
	const PORYGON
	const PORYGON2            
	const PORYGONZ
	const OMANYTE            
	const OMASTAR            
	const KABUTO             
	const KABUTOPS           
	const AERODACTYL    
	const MAERODACTYL
	const MUNCHLAX     
	const SNORLAX            
	const ARTICUNO
	const GARTICUNO           
	const ZAPDOS   
	const GZAPDOS          
	const MOLTRES
	const GMOLTRES            
	const DRATINI            
	const DRAGONAIR          
	const DRAGONITE
	const MDRAGONITE
	const MELTAN
	const MELMETAL
	const SCREAMTAIL
	const SANDYSHOCKS          
	const MEWTWO  
	const MMEWTWOX
	const MMEWTWOY           
	const MEW                
	const FOSSIL_KABUTOPS    
	const FOSSIL_AERODACTYL  
;	const MON_GHOST          

DEF NUM_POKEMON_INDEXES EQU const_value - 1

; starters
DEF STARTER1 EQU CHARMANDER
DEF STARTER2 EQU SQUIRTLE
DEF STARTER3 EQU BULBASAUR

; ghost Marowak in Pokémon Tower
DEF RESTLESS_SOUL EQU MAROWAK
