; special text IDs
TEXT_MON_FAINTED      EQU $d0
TEXT_BLACKED_OUT      EQU $d1
TEXT_REPEL_WORE_OFF   EQU $d2
TEXT_SAFARI_GAME_OVER EQU $d3

; PrintNumber
BIT_MONEY_SIGN     EQU 5
BIT_LEFT_ALIGN     EQU 6
BIT_LEADING_ZEROES EQU 7

MONEY_SIGN EQU     (1 << BIT_MONEY_SIGN)
LEFT_ALIGN EQU     (1 << BIT_LEFT_ALIGN)
LEADING_ZEROES EQU (1 << BIT_LEADING_ZEROES)
