; trainer data structure fields (see macros/scripts/maps.asm)
rsreset
DEF TRAINER_EVENT_FLAG_BIT     rb ;  0
DEF TRAINER_VIEW_RANGE         rb ;  1
DEF TRAINER_EVENT_FLAG_POINTER rw ;  2
DEF TRAINER_BEFORE_BATTLE_TEXT rw ;  4
DEF TRAINER_AFTER_BATTLE_TEXT  rw ;  6
DEF TRAINER_WON_BATTLE_TEXT    rw ;  8
DEF TRAINER_LOST_BATTLE_TEXT   rw ; 10
DEF TRAINER_STRUCT_SIZE EQU _RS   ; 12
