DEF OPP_ID_OFFSET EQU 200 ; pokemon and trainer constants use the same series

MACRO trainer_const
	const OPP_\1
	DEF \1 EQU OPP_\1 - OPP_ID_OFFSET
ENDM

; trainer class ids
; indexes for:
; - TrainerNames (see data/trainers/names.asm)
; - TrainerNamePointers (see data/trainers/name_pointers.asm)
; - TrainerDataPointers (see data/trainers/parties.asm)
; - TrainerPicAndMoneyPointers (see data/trainers/pic_pointers_money.asm)
; - TrainerAIPointers (see data/trainers/ai_pointers.asm)
; - TrainerClassMoveChoiceModifications (see data/trainers/move_choices.asm)
	listable_const_def OPP_ID_OFFSET
	trainer_const NOBODY         ; $00 (opp $C8)
	trainer_const YOUNGSTER      ; $01 (opp $C9)
	trainer_const BUG_CATCHER    ; $02 (opp $CA)
	trainer_const LASS           ; $03 (opp $CB)
	trainer_const SAILOR         ; $04 (opp $CC)
	trainer_const JR_TRAINER_M   ; $05 (opp $CD)
	trainer_const JR_TRAINER_F   ; $06 (opp $CE)
	trainer_const POKEMANIAC     ; $07 (opp $CF)
	trainer_const SUPER_NERD     ; $08 (opp $D0)
	trainer_const HIKER          ; $09 (opp $D1)
	trainer_const BIKER          ; $0A (opp $D2)
	trainer_const BURGLAR        ; $0B (opp $D3)
	trainer_const ENGINEER       ; $0C (opp $D4)
	trainer_const UNUSED_JUGGLER ; $0D (opp $D5)
	trainer_const FISHER         ; $0E (opp $D6)
	trainer_const SWIMMER        ; $0F (opp $D7)
	trainer_const CUE_BALL       ; $10 (opp $D8)
	trainer_const GAMBLER        ; $11 (opp $D9)
	trainer_const BEAUTY         ; $12 (opp $DA)
	trainer_const PSYCHIC_TR     ; $13 (opp $DB)
	trainer_const ROCKER         ; $14 (opp $DC)
	trainer_const JUGGLER        ; $15 (opp $DD)
	trainer_const TAMER          ; $16 (opp $DE)
	trainer_const BIRD_KEEPER    ; $17 (opp $DF)
	trainer_const BLACKBELT      ; $18 (opp $E0)
	trainer_const RIVAL1         ; $19 (opp $E1)
	trainer_const PROF_OAK       ; $1A (opp $E2)
	trainer_const CHIEF          ; $1B (opp $E3)
	trainer_const SCIENTIST      ; $1C (opp $E4)
	trainer_const GIOVANNI       ; $1D (opp $E5)
	trainer_const ROCKET         ; $1E (opp $E6)
	trainer_const COOLTRAINER_M  ; $1F (opp $E7)
	trainer_const COOLTRAINER_F  ; $20 (opp $E8)
	trainer_const BRUNO          ; $21 (opp $E9)
	trainer_const BROCK          ; $22 (opp $EA)
	trainer_const MISTY          ; $23 (opp $EB)
	trainer_const LT_SURGE       ; $24 (opp $EC)
	trainer_const ERIKA          ; $25 (opp $ED)
	trainer_const KOGA           ; $26 (opp $EE)
	trainer_const BLAINE         ; $27 (opp $EF)
	trainer_const SABRINA        ; $28 (opp $F0)
	trainer_const GENTLEMAN      ; $29 (opp $F1)
	trainer_const RIVAL2         ; $2A (opp $F2)
	trainer_const RIVAL3         ; $2B (opp $F3)
	trainer_const LORELEI        ; $2C (opp $F4)
	trainer_const CHANNELER      ; $2D (opp $F5)
	trainer_const AGATHA         ; $2E (opp $F6)
	trainer_const LANCE          ; $2F (opp $F7)
DEF NUM_TRAINERS EQU const_value - 1 - OPP_ID_OFFSET
