SECTION "Sprite Buffers", SRAM, BANK[0]

S_SPRITEBUFFER0:: ds SPRITEBUFFERSIZE ; a000
S_SPRITEBUFFER1:: ds SPRITEBUFFERSIZE ; a188
S_SPRITEBUFFER2:: ds SPRITEBUFFERSIZE ; a310

	ds $100

sHallOfFame:: ds HOF_TEAM * NUM_HOF_TEAMS ; a598

S_SAVEDBOX1 EQU $A000
S_SAVEDBOX2 EQU S_SAVEDBOX1 + (wBoxMonNicksEnd - W_NUMINBOX) ; $A462
S_SAVEDBOX3 EQU S_SAVEDBOX2 + (wBoxMonNicksEnd - W_NUMINBOX) ; $A8C4
S_SAVEDBOX4 EQU S_SAVEDBOX3 + (wBoxMonNicksEnd - W_NUMINBOX) ; $AD26
S_SAVEDBOX5 EQU S_SAVEDBOX4 + (wBoxMonNicksEnd - W_NUMINBOX) ; $B188
S_SAVEDBOX6 EQU S_SAVEDBOX5 + (wBoxMonNicksEnd - W_NUMINBOX) ; $B5EA
S_SAVEDBOXESCHECKSUM EQU S_SAVEDBOX6 + (wBoxMonNicksEnd - W_NUMINBOX) ; $BA4C
S_SAVEDBOXESCHECKSUM2 EQU S_SAVEDBOXESCHECKSUM + 1 ; $BA4D

S_SAVEDPLAYERNAME EQU $A598
S_SAVEDMAINDATA EQU S_SAVEDPLAYERNAME + (wPartyCount - wPlayerName) ; $A5A3
S_SAVEDSPRITEDATA EQU S_SAVEDMAINDATA + (W_NUMINBOX - wPokedexOwned) ; $AD2C
S_SAVEDPARTYDATA EQU S_SAVEDSPRITEDATA + (wOAMBuffer - wSpriteStateData1) ; $AF2C
S_SAVEDCURBOXDATA EQU S_SAVEDPARTYDATA + (wPokedexOwned - wPartyCount) ; $B0C0
S_SAVEDhTilesetType EQU S_SAVEDCURBOXDATA + (wBoxMonNicksEnd - W_NUMINBOX) ; $B522
S_SAVEDMAINDATACHECKSUM EQU S_SAVEDhTilesetType + 1 ; $B523
