; Generated from data/moves/names.asm by convert_move_names.py.
.STRINGMAPTABLE pokemon "wla/pokemon.tbl"

MoveNames::
	.STRINGMAP pokemon, "POUND@"
	.STRINGMAP pokemon, "KARATE CHOP@"
	.STRINGMAP pokemon, "DOUBLESLAP@"
	.STRINGMAP pokemon, "COMET PUNCH@"
	.STRINGMAP pokemon, "MEGA PUNCH@"
	.STRINGMAP pokemon, "PAY DAY@"
	.STRINGMAP pokemon, "FIRE PUNCH@"
	.STRINGMAP pokemon, "ICE PUNCH@"
	.STRINGMAP pokemon, "THUNDERPUNCH@"
	.STRINGMAP pokemon, "SCRATCH@"
	.STRINGMAP pokemon, "VICEGRIP@"
	.STRINGMAP pokemon, "GUILLOTINE@"
	.STRINGMAP pokemon, "RAZOR WIND@"
	.STRINGMAP pokemon, "SWORDS DANCE@"
	.STRINGMAP pokemon, "CUT@"
	.STRINGMAP pokemon, "GUST@"
	.STRINGMAP pokemon, "WING ATTACK@"
	.STRINGMAP pokemon, "WHIRLWIND@"
	.STRINGMAP pokemon, "FLY@"
	.STRINGMAP pokemon, "BIND@"
	.STRINGMAP pokemon, "SLAM@"
	.STRINGMAP pokemon, "VINE WHIP@"
	.STRINGMAP pokemon, "STOMP@"
	.STRINGMAP pokemon, "DOUBLE KICK@"
	.STRINGMAP pokemon, "MEGA KICK@"
	.STRINGMAP pokemon, "JUMP KICK@"
	.STRINGMAP pokemon, "ROLLING KICK@"
	.STRINGMAP pokemon, "SAND-ATTACK@"
	.STRINGMAP pokemon, "HEADBUTT@"
	.STRINGMAP pokemon, "HORN ATTACK@"
	.STRINGMAP pokemon, "FURY ATTACK@"
	.STRINGMAP pokemon, "HORN DRILL@"
	.STRINGMAP pokemon, "TACKLE@"
	.STRINGMAP pokemon, "BODY SLAM@"
	.STRINGMAP pokemon, "WRAP@"
	.STRINGMAP pokemon, "TAKE DOWN@"
	.STRINGMAP pokemon, "THRASH@"
	.STRINGMAP pokemon, "DOUBLE-EDGE@"
	.STRINGMAP pokemon, "TAIL WHIP@"
	.STRINGMAP pokemon, "POISON STING@"
	.STRINGMAP pokemon, "TWINEEDLE@"
	.STRINGMAP pokemon, "PIN MISSILE@"
	.STRINGMAP pokemon, "LEER@"
	.STRINGMAP pokemon, "BITE@"
	.STRINGMAP pokemon, "GROWL@"
	.STRINGMAP pokemon, "ROAR@"
	.STRINGMAP pokemon, "SING@"
	.STRINGMAP pokemon, "SUPERSONIC@"
	.STRINGMAP pokemon, "SONICBOOM@"
	.STRINGMAP pokemon, "DISABLE@"
	.STRINGMAP pokemon, "ACID@"
	.STRINGMAP pokemon, "EMBER@"
	.STRINGMAP pokemon, "FLAMETHROWER@"
	.STRINGMAP pokemon, "MIST@"
	.STRINGMAP pokemon, "WATER GUN@"
	.STRINGMAP pokemon, "HYDRO PUMP@"
	.STRINGMAP pokemon, "SURF@"
	.STRINGMAP pokemon, "ICE BEAM@"
	.STRINGMAP pokemon, "BLIZZARD@"
	.STRINGMAP pokemon, "PSYBEAM@"
	.STRINGMAP pokemon, "BUBBLEBEAM@"
	.STRINGMAP pokemon, "AURORA BEAM@"
	.STRINGMAP pokemon, "HYPER BEAM@"
	.STRINGMAP pokemon, "PECK@"
	.STRINGMAP pokemon, "DRILL PECK@"
	.STRINGMAP pokemon, "SUBMISSION@"
	.STRINGMAP pokemon, "LOW KICK@"
	.STRINGMAP pokemon, "COUNTER@"
	.STRINGMAP pokemon, "SEISMIC TOSS@"
	.STRINGMAP pokemon, "STRENGTH@"
	.STRINGMAP pokemon, "ABSORB@"
	.STRINGMAP pokemon, "MEGA DRAIN@"
	.STRINGMAP pokemon, "LEECH SEED@"
	.STRINGMAP pokemon, "GROWTH@"
	.STRINGMAP pokemon, "RAZOR LEAF@"
	.STRINGMAP pokemon, "SOLARBEAM@"
	.STRINGMAP pokemon, "POISONPOWDER@"
	.STRINGMAP pokemon, "STUN SPORE@"
	.STRINGMAP pokemon, "SLEEP POWDER@"
	.STRINGMAP pokemon, "PETAL DANCE@"
	.STRINGMAP pokemon, "STRING SHOT@"
	.STRINGMAP pokemon, "DRAGON RAGE@"
	.STRINGMAP pokemon, "FIRE SPIN@"
	.STRINGMAP pokemon, "THUNDERSHOCK@"
	.STRINGMAP pokemon, "THUNDERBOLT@"
	.STRINGMAP pokemon, "THUNDER WAVE@"
	.STRINGMAP pokemon, "THUNDER@"
	.STRINGMAP pokemon, "ROCK THROW@"
	.STRINGMAP pokemon, "EARTHQUAKE@"
	.STRINGMAP pokemon, "FISSURE@"
	.STRINGMAP pokemon, "DIG@"
	.STRINGMAP pokemon, "TOXIC@"
	.STRINGMAP pokemon, "CONFUSION@"
	.STRINGMAP pokemon, "PSYCHIC@"
	.STRINGMAP pokemon, "HYPNOSIS@"
	.STRINGMAP pokemon, "MEDITATE@"
	.STRINGMAP pokemon, "AGILITY@"
	.STRINGMAP pokemon, "QUICK ATTACK@"
	.STRINGMAP pokemon, "RAGE@"
	.STRINGMAP pokemon, "TELEPORT@"
	.STRINGMAP pokemon, "NIGHT SHADE@"
	.STRINGMAP pokemon, "MIMIC@"
	.STRINGMAP pokemon, "SCREECH@"
	.STRINGMAP pokemon, "DOUBLE TEAM@"
	.STRINGMAP pokemon, "RECOVER@"
	.STRINGMAP pokemon, "HARDEN@"
	.STRINGMAP pokemon, "MINIMIZE@"
	.STRINGMAP pokemon, "SMOKESCREEN@"
	.STRINGMAP pokemon, "CONFUSE RAY@"
	.STRINGMAP pokemon, "WITHDRAW@"
	.STRINGMAP pokemon, "DEFENSE CURL@"
	.STRINGMAP pokemon, "BARRIER@"
	.STRINGMAP pokemon, "LIGHT SCREEN@"
	.STRINGMAP pokemon, "HAZE@"
	.STRINGMAP pokemon, "REFLECT@"
	.STRINGMAP pokemon, "FOCUS ENERGY@"
	.STRINGMAP pokemon, "BIDE@"
	.STRINGMAP pokemon, "METRONOME@"
	.STRINGMAP pokemon, "MIRROR MOVE@"
	.STRINGMAP pokemon, "SELFDESTRUCT@"
	.STRINGMAP pokemon, "EGG BOMB@"
	.STRINGMAP pokemon, "LICK@"
	.STRINGMAP pokemon, "SMOG@"
	.STRINGMAP pokemon, "SLUDGE@"
	.STRINGMAP pokemon, "BONE CLUB@"
	.STRINGMAP pokemon, "FIRE BLAST@"
	.STRINGMAP pokemon, "WATERFALL@"
	.STRINGMAP pokemon, "CLAMP@"
	.STRINGMAP pokemon, "SWIFT@"
	.STRINGMAP pokemon, "SKULL BASH@"
	.STRINGMAP pokemon, "SPIKE CANNON@"
	.STRINGMAP pokemon, "CONSTRICT@"
	.STRINGMAP pokemon, "AMNESIA@"
	.STRINGMAP pokemon, "KINESIS@"
	.STRINGMAP pokemon, "SOFTBOILED@"
	.STRINGMAP pokemon, "HI JUMP KICK@"
	.STRINGMAP pokemon, "GLARE@"
	.STRINGMAP pokemon, "DREAM EATER@"
	.STRINGMAP pokemon, "POISON GAS@"
	.STRINGMAP pokemon, "BARRAGE@"
	.STRINGMAP pokemon, "LEECH LIFE@"
	.STRINGMAP pokemon, "LOVELY KISS@"
	.STRINGMAP pokemon, "SKY ATTACK@"
	.STRINGMAP pokemon, "TRANSFORM@"
	.STRINGMAP pokemon, "BUBBLE@"
	.STRINGMAP pokemon, "DIZZY PUNCH@"
	.STRINGMAP pokemon, "SPORE@"
	.STRINGMAP pokemon, "FLASH@"
	.STRINGMAP pokemon, "PSYWAVE@"
	.STRINGMAP pokemon, "SPLASH@"
	.STRINGMAP pokemon, "ACID ARMOR@"
	.STRINGMAP pokemon, "CRABHAMMER@"
	.STRINGMAP pokemon, "EXPLOSION@"
	.STRINGMAP pokemon, "FURY SWIPES@"
	.STRINGMAP pokemon, "BONEMERANG@"
	.STRINGMAP pokemon, "REST@"
	.STRINGMAP pokemon, "ROCK SLIDE@"
	.STRINGMAP pokemon, "HYPER FANG@"
	.STRINGMAP pokemon, "SHARPEN@"
	.STRINGMAP pokemon, "CONVERSION@"
	.STRINGMAP pokemon, "TRI ATTACK@"
	.STRINGMAP pokemon, "SUPER FANG@"
	.STRINGMAP pokemon, "SLASH@"
	.STRINGMAP pokemon, "SUBSTITUTE@"
	.STRINGMAP pokemon, "STRUGGLE@"

Bank44MoveNamesEnd::
