; Generated by convert_text_bank.py from:
;   text/VermilionGym_2.asm
;   text/VermilionPidgeyHouse.asm
;   text/VermilionDock.asm
;   text/VermilionOldRodHouse.asm
;   text/CeladonMart1F.asm
;   text/CeladonMart2F.asm
;   text/CeladonMart3F.asm
;   text/CeladonMart4F.asm
;   text/CeladonMartRoof.asm
;   text/CeladonMansion1F.asm
;   text/CeladonMansion2F.asm
;   text/CeladonMansion3F.asm
;   text/CeladonMansionRoof.asm
;   text/CeladonMansionRoofHouse.asm
;   text/CeladonPokecenter.asm
;   text/CeladonGym.asm
;   text/GameCorner.asm
;   text/CeladonMart5F.asm
;   text/GameCornerPrizeRoom.asm
;   text/CeladonDiner.asm
;   text/CeladonChiefHouse.asm
;   text/CeladonHotel.asm
;   text/FuchsiaMart.asm
;   text/FuchsiaBillsGrandpasHouse.asm
;   text/FuchsiaPokecenter.asm
;   text/WardensHouse.asm
;   text/SafariZoneGate.asm
;   text/FuchsiaGym.asm
.STRINGMAPTABLE pokemon "wla/pokemon.tbl"

; text/VermilionGym_2.asm
_VermilionGymLTSurgePostBattleAdviceText::
	.DB $00
	.STRINGMAP pokemon, "A little word of"
	.DB $4f
	.STRINGMAP pokemon, "advice, kid!"
	.DB $51
	.STRINGMAP pokemon, "Electricity is"
	.DB $4f
	.STRINGMAP pokemon, "sure powerful!"
	.DB $51
	.STRINGMAP pokemon, "But, it's useless"
	.DB $4f
	.STRINGMAP pokemon, "against ground-"
	.DB $55
	.STRINGMAP pokemon, "type #MON!"
	.DB $57
_VermilionGymLTSurgeThunderBadgeInfoText::
	.DB $00
	.STRINGMAP pokemon, "The THUNDERBADGE"
	.DB $4f
	.STRINGMAP pokemon, "cranks up your"
	.DB $55
	.STRINGMAP pokemon, "#MON's SPEED!"
	.DB $51
	.STRINGMAP pokemon, "It also lets your"
	.DB $4f
	.STRINGMAP pokemon, "#MON FLY any"
	.DB $55
	.STRINGMAP pokemon, "time, kid!"
	.DB $51
	.STRINGMAP pokemon, "You're special,"
	.DB $4f
	.STRINGMAP pokemon, "kid! Take this!"
	.DB $57
_VermilionGymLTSurgeReceivedTM24Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received "
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_TM24ExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "TM24 contains"
	.DB $4f
	.STRINGMAP pokemon, "THUNDERBOLT!"
	.DB $51
	.STRINGMAP pokemon, "Teach it to an"
	.DB $4f
	.STRINGMAP pokemon, "electric #MON!"
	.DB $57
_VermilionGymLTSurgeTM24NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Yo kid, make room"
	.DB $4f
	.STRINGMAP pokemon, "in your pack!"
	.DB $57
_VermilionGymLTSurgeReceivedThunderBadgeText::
	.DB $00
	.STRINGMAP pokemon, "Whoa!"
	.DB $51
	.STRINGMAP pokemon, "You're the real"
	.DB $4f
	.STRINGMAP pokemon, "deal, kid!"
	.DB $51
	.STRINGMAP pokemon, "Fine then, take"
	.DB $4f
	.STRINGMAP pokemon, "the THUNDERBADGE!"
	.DB $58
_VermilionGymGentlemanBattleText::
	.DB $00
	.STRINGMAP pokemon, "When I was in the"
	.DB $4f
	.STRINGMAP pokemon, "Army, LT.SURGE"
	.DB $55
	.STRINGMAP pokemon, "was my strict CO!"
	.DB $57
_VermilionGymGentlemanEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Stop!"
	.DB $4f
	.STRINGMAP pokemon, "You're very good!"
	.DB $58
_VermilionGymGentlemanAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The door won't"
	.DB $4f
	.STRINGMAP pokemon, "open?"
	.DB $51
	.STRINGMAP pokemon, "LT.SURGE always"
	.DB $4f
	.STRINGMAP pokemon, "was cautious!"
	.DB $57
_VermilionGymSuperNerdBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm a lightweight,"
	.DB $4f
	.STRINGMAP pokemon, "but I'm good with"
	.DB $55
	.STRINGMAP pokemon, "electricity!"
	.DB $57
_VermilionGymSuperNerdEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Fried!"
	.DB $58
_VermilionGymSuperNerdAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "OK, I'll talk!"
	.DB $51
	.STRINGMAP pokemon, "LT.SURGE said he"
	.DB $4f
	.STRINGMAP pokemon, "hid door switches"
	.DB $55
	.STRINGMAP pokemon, "inside something!"
	.DB $57
_VermilionGymSailorBattleText::
	.DB $00
	.STRINGMAP pokemon, "This is no place"
	.DB $4f
	.STRINGMAP pokemon, "for kids!"
	.DB $57
_VermilionGymSailorEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Wow!"
	.DB $4f
	.STRINGMAP pokemon, "Surprised me!"
	.DB $58
_VermilionGymSailorAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "LT.SURGE set up"
	.DB $4f
	.STRINGMAP pokemon, "double locks!"
	.DB $55
	.STRINGMAP pokemon, "Here's a hint!"
	.DB $51
	.STRINGMAP pokemon, "When you open the"
	.DB $4f
	.STRINGMAP pokemon, "1st lock, the 2nd"
	.DB $55
	.STRINGMAP pokemon, "lock is right"
	.DB $55
	.STRINGMAP pokemon, "next to it!"
	.DB $57
_VermilionGymGymGuideChampInMakingText::
	.DB $00
	.STRINGMAP pokemon, "Yo! Champ in"
	.DB $4f
	.STRINGMAP pokemon, "making!"
	.DB $51
	.STRINGMAP pokemon, "LT.SURGE has a"
	.DB $4f
	.STRINGMAP pokemon, "nickname. People"
	.DB $55
	.STRINGMAP pokemon, "refer to him as"
	.DB $55
	.STRINGMAP pokemon, "the Lightning"
	.DB $55
	.STRINGMAP pokemon, "American!"
	.DB $51
	.STRINGMAP pokemon, "He's an expert on"
	.DB $4f
	.STRINGMAP pokemon, "electric #MON!"
	.DB $51
	.STRINGMAP pokemon, "Birds and water"
	.DB $4f
	.STRINGMAP pokemon, "#MON are at"
	.DB $55
	.STRINGMAP pokemon, "risk! Beware of"
	.DB $55
	.STRINGMAP pokemon, "paralysis too!"
	.DB $51
	.STRINGMAP pokemon, "LT.SURGE is very"
	.DB $4f
	.STRINGMAP pokemon, "cautious!"
	.DB $51
	.STRINGMAP pokemon, "You'll have to"
	.DB $4f
	.STRINGMAP pokemon, "break a code to"
	.DB $55
	.STRINGMAP pokemon, "get to him!"
	.DB $57
_VermilionGymGymGuideBeatLTSurgeText::
	.DB $00
	.STRINGMAP pokemon, "Whew! That match"
	.DB $4f
	.STRINGMAP pokemon, "was electric!"
	.DB $57

; text/VermilionPidgeyHouse.asm
_VermilionPidgeyHouseYoungsterText::
	.DB $00
	.STRINGMAP pokemon, "I'm getting my"
	.DB $4f
	.STRINGMAP pokemon, "PIDGEY to fly a"
	.DB $55
	.STRINGMAP pokemon, "letter to SAFFRON"
	.DB $55
	.STRINGMAP pokemon, "in the north!"
	.DB $57
_VermilionPidgeyHousePidgeyText::
	.DB $00
	.STRINGMAP pokemon, "PIDGEY: Kurukkoo!@"
	.DB $50
_VermilionPidgeyHouseLetterText::
	.DB $00
	.STRINGMAP pokemon, "Dear PIPPI, I hope"
	.DB $4f
	.STRINGMAP pokemon, "to see you soon."
	.DB $51
	.STRINGMAP pokemon, "I heard SAFFRON"
	.DB $4f
	.STRINGMAP pokemon, "has problems with"
	.DB $55
	.STRINGMAP pokemon, "TEAM ROCKET."
	.DB $51
	.STRINGMAP pokemon, "VERMILION appears"
	.DB $4f
	.STRINGMAP pokemon, "to be safe."
	.DB $57

; text/VermilionDock.asm
_VermilionDockUnusedText::
	.DB $00
	.DB $57

; text/VermilionOldRodHouse.asm
_VermilionOldRodHouseFishingGuruDoYouLikeToFishText::
	.DB $00
	.STRINGMAP pokemon, "I'm the FISHING"
	.DB $4f
	.STRINGMAP pokemon, "GURU!"
	.DB $51
	.STRINGMAP pokemon, "I simply Looove"
	.DB $4f
	.STRINGMAP pokemon, "fishing!"
	.DB $51
	.STRINGMAP pokemon, "Do you like to"
	.DB $4f
	.STRINGMAP pokemon, "fish?"
	.DB $57
_VermilionOldRodHouseFishingGuruTakeThisText::
	.DB $00
	.STRINGMAP pokemon, "Grand! I like"
	.DB $4f
	.STRINGMAP pokemon, "your style!"
	.DB $51
	.STRINGMAP pokemon, "Take this and"
	.DB $4f
	.STRINGMAP pokemon, "fish, young one!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "an @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_VermilionOldRodHouseFishingGuruFishingIsAWayOfLifeText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "Fishing is a way"
	.DB $4f
	.STRINGMAP pokemon, "of life!"
	.DB $51
	.STRINGMAP pokemon, "From the seas to"
	.DB $4f
	.STRINGMAP pokemon, "rivers, go out"
	.DB $55
	.STRINGMAP pokemon, "and land the big"
	.DB $55
	.STRINGMAP pokemon, "one, young one!"
	.DB $57
_VermilionOldRodHouseFishingGuruThatsSoDisappointingText::
	.DB $00
	.STRINGMAP pokemon, "Oh... That's so"
	.DB $4f
	.STRINGMAP pokemon, "disappointing..."
	.DB $57
_VermilionOldRodHouseFishingGuruHowAreTheFishBitingText::
	.DB $00
	.STRINGMAP pokemon, "Hello there,"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "How are the fish"
	.DB $4f
	.STRINGMAP pokemon, "biting?"
	.DB $57
_VermilionOldRodHouseFishingGuruNoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Oh no!"
	.DB $51
	.STRINGMAP pokemon, "You have no room"
	.DB $4f
	.STRINGMAP pokemon, "for my gift!"
	.DB $57

; text/CeladonMart1F.asm
_CeladonMart1FReceptionistText::
	.DB $00
	.STRINGMAP pokemon, "Hello! Welcome to"
	.DB $4f
	.STRINGMAP pokemon, "CELADON DEPT."
	.DB $55
	.STRINGMAP pokemon, "STORE."
	.DB $51
	.STRINGMAP pokemon, "The board on the"
	.DB $4f
	.STRINGMAP pokemon, "right describes"
	.DB $55
	.STRINGMAP pokemon, "the store layout."
	.DB $57
_CeladonMart1FDirectorySignText::
	.DB $00
	.STRINGMAP pokemon, "1F: SERVICE"
	.DB $4f
	.STRINGMAP pokemon, "    COUNTER"
	.DB $51
	.STRINGMAP pokemon, "2F: TRAINER'S"
	.DB $4f
	.STRINGMAP pokemon, "    MARKET"
	.DB $51
	.STRINGMAP pokemon, "3F: TV GAME SHOP"
	.DB $51
	.STRINGMAP pokemon, "4F: WISEMAN GIFTS"
	.DB $51
	.STRINGMAP pokemon, "5F: DRUG STORE"
	.DB $51
	.STRINGMAP pokemon, "ROOFTOP SQUARE:"
	.DB $4f
	.STRINGMAP pokemon, "VENDING MACHINES"
	.DB $57
_CeladonMart1FCurrentFloorSignText::
	.DB $00
	.STRINGMAP pokemon, "1F: SERVICE"
	.DB $4f
	.STRINGMAP pokemon, "    COUNTER"
	.DB $57

; text/CeladonMart2F.asm
_CeladonMart2FMiddleAgedManText::
	.DB $00
	.STRINGMAP pokemon, "SUPER REPEL keeps"
	.DB $4f
	.STRINGMAP pokemon, "weak #MON at"
	.DB $55
	.STRINGMAP pokemon, "bay..."
	.DB $51
	.STRINGMAP pokemon, "Hmm, it's a more"
	.DB $4f
	.STRINGMAP pokemon, "powerful REPEL!"
	.DB $57
_CeladonMart2FGirlText::
	.DB $00
	.STRINGMAP pokemon, "For long outings,"
	.DB $4f
	.STRINGMAP pokemon, "you should buy"
	.DB $55
	.STRINGMAP pokemon, "REVIVE."
	.DB $57
_CeladonMart2FCurrentFloorSignText::
	.DB $00
	.STRINGMAP pokemon, "Top Grade Items"
	.DB $4f
	.STRINGMAP pokemon, "for Trainers!"
	.DB $51
	.STRINGMAP pokemon, "2F: TRAINER'S"
	.DB $4f
	.STRINGMAP pokemon, "    MARKET"
	.DB $57

; text/CeladonMart3F.asm
_CeladonMart3FClerkTM18PreReceiveText::
	.DB $00
	.STRINGMAP pokemon, "Oh, hi! I finally"
	.DB $4f
	.STRINGMAP pokemon, "finished #MON!"
	.DB $51
	.STRINGMAP pokemon, "Not done yet?"
	.DB $4f
	.STRINGMAP pokemon, "This might be"
	.DB $55
	.STRINGMAP pokemon, "useful!"
	.DB $58
_CeladonMart3FClerkReceivedTM18Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_CeladonMart3FClerkTM18ExplanationText::
	.DB $00
	.STRINGMAP pokemon, "TM18 is COUNTER!"
	.DB $4f
	.STRINGMAP pokemon, "Not like the one"
	.DB $55
	.STRINGMAP pokemon, "I'm leaning on,"
	.DB $55
	.STRINGMAP pokemon, "mind you!"
	.DB $57
_CeladonMart3FClerkTM18NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Your pack is full"
	.DB $4f
	.STRINGMAP pokemon, "of items!"
	.DB $57
_CeladonMart3FGameBoyKid1Text::
	.DB $00
	.STRINGMAP pokemon, "Captured #MON"
	.DB $4f
	.STRINGMAP pokemon, "are registered"
	.DB $55
	.STRINGMAP pokemon, "with an ID No."
	.DB $55
	.STRINGMAP pokemon, "and OT, the name"
	.DB $55
	.STRINGMAP pokemon, "of the Original"
	.DB $55
	.STRINGMAP pokemon, "Trainer that"
	.DB $55
	.STRINGMAP pokemon, "caught it!"
	.DB $57
_CeladonMart3FGameBoyKid2Text::
	.DB $00
	.STRINGMAP pokemon, "All right!"
	.DB $51
	.STRINGMAP pokemon, "My buddy's going"
	.DB $4f
	.STRINGMAP pokemon, "to trade me his"
	.DB $55
	.STRINGMAP pokemon, "KANGASKHAN for my"
	.DB $55
	.STRINGMAP pokemon, "GRAVELER!"
	.DB $57
_CeladonMart3FGameBoyKid3Text::
	.DB $00
	.STRINGMAP pokemon, "Come on GRAVELER!"
	.DB $51
	.STRINGMAP pokemon, "I love GRAVELER!"
	.DB $4f
	.STRINGMAP pokemon, "I collect them!"
	.DB $51
	.STRINGMAP pokemon, "Huh?"
	.DB $51
	.STRINGMAP pokemon, "GRAVELER turned"
	.DB $4f
	.STRINGMAP pokemon, "into a different"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $57
_CeladonMart3FLittleBoyText::
	.DB $00
	.STRINGMAP pokemon, "You can identify"
	.DB $4f
	.STRINGMAP pokemon, "#MON you got"
	.DB $55
	.STRINGMAP pokemon, "in trades by"
	.DB $55
	.STRINGMAP pokemon, "their ID Numbers!"
	.DB $57
_CeladonMart3FSNESText::
	.DB $00
	.STRINGMAP pokemon, "It's an SNES!"
	.DB $57
_CeladonMart3FRPGText::
	.DB $00
	.STRINGMAP pokemon, "An RPG! There's"
	.DB $4f
	.STRINGMAP pokemon, "no time for that!"
	.DB $57
_CeladonMart3FSportsGameText::
	.DB $00
	.STRINGMAP pokemon, "A sports game!"
	.DB $4f
	.STRINGMAP pokemon, "Dad'll like that!"
	.DB $57
_CeladonMart3FPuzzleGameText::
	.DB $00
	.STRINGMAP pokemon, "A puzzle game!"
	.DB $4f
	.STRINGMAP pokemon, "Looks addictive!"
	.DB $57
_CeladonMart3FFightingGameText::
	.DB $00
	.STRINGMAP pokemon, "A fighting game!"
	.DB $4f
	.STRINGMAP pokemon, "Looks tough!"
	.DB $57
_CeladonMart3FCurrentFloorSignText::
	.DB $00
	.STRINGMAP pokemon, "3F: TV GAME SHOP"
	.DB $57
_CeladonMart3FPokemonPosterText::
	.DB $00
	.STRINGMAP pokemon, "Red and Blue!"
	.DB $4f
	.STRINGMAP pokemon, "Both are #MON!"
	.DB $57

; text/CeladonMart4F.asm
_CeladonMart4FSuperNerdText::
	.DB $00
	.STRINGMAP pokemon, "I'm getting a"
	.DB $4f
	.STRINGMAP pokemon, "# DOLL for my"
	.DB $55
	.STRINGMAP pokemon, "girl friend!"
	.DB $57
_CeladonMart4FYoungsterText::
	.DB $00
	.STRINGMAP pokemon, "I heard something"
	.DB $4f
	.STRINGMAP pokemon, "useful."
	.DB $51
	.STRINGMAP pokemon, "You can run from"
	.DB $4f
	.STRINGMAP pokemon, "wild #MON by"
	.DB $55
	.STRINGMAP pokemon, "distracting them"
	.DB $55
	.STRINGMAP pokemon, "with a # DOLL!"
	.DB $57
_CeladonMart4FCurrentFloorSignText::
	.DB $00
	.STRINGMAP pokemon, "Express yourself"
	.DB $4f
	.STRINGMAP pokemon, "with gifts!"
	.DB $51
	.STRINGMAP pokemon, "4F: WISEMAN GIFTS"
	.DB $51
	.STRINGMAP pokemon, "Evolution Special!"
	.DB $4f
	.STRINGMAP pokemon, "Element STONEs on"
	.DB $55
	.STRINGMAP pokemon, "sale now!"
	.DB $57

; text/CeladonMartRoof.asm
_CeladonMartRoofLittleGirlGiveHerWhichDrinkText::
	.DB $00
	.STRINGMAP pokemon, "Give her which"
	.DB $4f
	.STRINGMAP pokemon, "drink?"
	.DB $57
_CeladonMartRoofLittleGirlYayFreshWaterText::
	.DB $00
	.STRINGMAP pokemon, "Yay!"
	.DB $51
	.STRINGMAP pokemon, "FRESH WATER!"
	.DB $51
	.STRINGMAP pokemon, "Thank you!"
	.DB $51
	.STRINGMAP pokemon, "You can have this"
	.DB $4f
	.STRINGMAP pokemon, "from me!@"
	.DB $50
_CeladonMartRoofLittleGirlReceivedTM13Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_CeladonMartRoofLittleGirlTM13ExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, " contains"
	.DB $4f
	.STRINGMAP pokemon, "ICE BEAM!"
	.DB $51
	.STRINGMAP pokemon, "It can freeze the"
	.DB $4f
	.STRINGMAP pokemon, "target sometimes!@"
	.DB $50
_CeladonMartRoofLittleGirlYaySodaPopText::
	.DB $00
	.STRINGMAP pokemon, "Yay!"
	.DB $51
	.STRINGMAP pokemon, "SODA POP!"
	.DB $51
	.STRINGMAP pokemon, "Thank you!"
	.DB $51
	.STRINGMAP pokemon, "You can have this"
	.DB $4f
	.STRINGMAP pokemon, "from me!@"
	.DB $50
_CeladonMartRoofLittleGirlReceivedTM48Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_CeladonMartRoofLittleGirlTM48ExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, " contains"
	.DB $4f
	.STRINGMAP pokemon, "ROCK SLIDE!"
	.DB $51
	.STRINGMAP pokemon, "It can spook the"
	.DB $4f
	.STRINGMAP pokemon, "target sometimes!@"
	.DB $50
_CeladonMartRoofLittleGirlYayLemonadeText::
	.DB $00
	.STRINGMAP pokemon, "Yay!"
	.DB $51
	.STRINGMAP pokemon, "LEMONADE!"
	.DB $51
	.STRINGMAP pokemon, "Thank you!"
	.DB $51
	.STRINGMAP pokemon, "You can have this"
	.DB $4f
	.STRINGMAP pokemon, "from me!@"
	.DB $50
_CeladonMartRoofLittleGirlReceivedTM49Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "TM49!@"
	.DB $50
_CeladonMartRoofLittleGirlTM49ExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "TM49 contains"
	.DB $4f
	.STRINGMAP pokemon, "TRI ATTACK!@"
	.DB $50
_CeladonMartRoofLittleGirlNoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You don't have"
	.DB $4f
	.STRINGMAP pokemon, "space for this!@"
	.DB $50
_CeladonMartRoofLittleGirlImNotThirstyText::
	.DB $00
	.STRINGMAP pokemon, "No thank you!"
	.DB $4f
	.STRINGMAP pokemon, "I'm not thirsty"
	.DB $55
	.STRINGMAP pokemon, "after all!@"
	.DB $50
_CeladonMartRoofSuperNerdText::
	.DB $00
	.STRINGMAP pokemon, "My sister is a"
	.DB $4f
	.STRINGMAP pokemon, "trainer, believe"
	.DB $55
	.STRINGMAP pokemon, "it or not."
	.DB $51
	.STRINGMAP pokemon, "But, she's so"
	.DB $4f
	.STRINGMAP pokemon, "immature, she"
	.DB $55
	.STRINGMAP pokemon, "drives me nuts!"
	.DB $57
_CeladonMartRoofLittleGirlImThirstyText::
	.DB $00
	.STRINGMAP pokemon, "I'm thirsty!"
	.DB $4f
	.STRINGMAP pokemon, "I want something"
	.DB $55
	.STRINGMAP pokemon, "to drink!"
	.DB $57
_CeladonMartRoofLittleGirlGiveHerADrinkText::
	.DB $00
	.STRINGMAP pokemon, "I'm thirsty!"
	.DB $4f
	.STRINGMAP pokemon, "I want something"
	.DB $55
	.STRINGMAP pokemon, "to drink!"
	.DB $51
	.STRINGMAP pokemon, "Give her a drink?"
	.DB $57
_CeladonMartRoofCurrentFloorSignText::
	.DB $00
	.STRINGMAP pokemon, "ROOFTOP SQUARE:"
	.DB $4f
	.STRINGMAP pokemon, "VENDING MACHINES"
	.DB $57
_VendingMachineText1::
	.DB $00
	.STRINGMAP pokemon, "A vending machine!"
	.DB $4f
	.STRINGMAP pokemon, "Here's the menu!"
	.DB $58
_VendingMachineText4::
	.DB $00
	.STRINGMAP pokemon, "Oops, not enough"
	.DB $4f
	.STRINGMAP pokemon, "money!"
	.DB $57
_VendingMachineText5::
	.DB $01
	.DW wStringBuffer
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "popped out!"
	.DB $57
_VendingMachineText6::
	.DB $00
	.STRINGMAP pokemon, "There's no more"
	.DB $4f
	.STRINGMAP pokemon, "room for stuff!"
	.DB $57
_VendingMachineText7::
	.DB $00
	.STRINGMAP pokemon, "Not thirsty!"
	.DB $57

; text/CeladonMansion1F.asm
_CeladonMansion1FMeowthText::
	.DB $00
	.STRINGMAP pokemon, "MEOWTH: Meow!@"
	.DB $50
_CeladonMansion1FGrannyText::
	.DB $00
	.STRINGMAP pokemon, "My dear #MON"
	.DB $4f
	.STRINGMAP pokemon, "keep me company."
	.DB $51
	.STRINGMAP pokemon, "MEOWTH even brings"
	.DB $4f
	.STRINGMAP pokemon, "money home!"
	.DB $57
_CeladonMansion1FClefairyText::
	.DB $00
	.STRINGMAP pokemon, "CLEFAIRY: Pi"
	.DB $4f
	.STRINGMAP pokemon, "pippippi!@"
	.DB $50
_CeladonMansion1FNidoranFText::
	.DB $00
	.STRINGMAP pokemon, "NIDORAN: Kya"
	.DB $4f
	.STRINGMAP pokemon, "kyaoo!@"
	.DB $50
_CeladonMansion1FManagersSuiteSignText::
	.DB $00
	.STRINGMAP pokemon, "CELADON MANSION"
	.DB $4f
	.STRINGMAP pokemon, "Manager's Suite"
	.DB $57

; text/CeladonMansion2F.asm
_CeladonMansion2FMeetingRoomSignText::
	.DB $00
	.STRINGMAP pokemon, "GAME FREAK"
	.DB $4f
	.STRINGMAP pokemon, "Meeting Room"
	.DB $57

; text/CeladonMansion3F.asm
_CeladonMansion3FProgrammerText::
	.DB $00
	.STRINGMAP pokemon, "Me? I'm the"
	.DB $4f
	.STRINGMAP pokemon, "programmer!"
	.DB $57
_CeladonMansion3FGraphicArtistText::
	.DB $00
	.STRINGMAP pokemon, "I'm the graphic"
	.DB $4f
	.STRINGMAP pokemon, "artist!"
	.DB $55
	.STRINGMAP pokemon, "I drew you!"
	.DB $57
_CeladonMansion3FWriterText::
	.DB $00
	.STRINGMAP pokemon, "I wrote the story!"
	.DB $4f
	.STRINGMAP pokemon, "Isn't ERIKA cute?"
	.DB $51
	.STRINGMAP pokemon, "I like MISTY a"
	.DB $4f
	.STRINGMAP pokemon, "lot too!"
	.DB $51
	.STRINGMAP pokemon, "Oh, and SABRINA,"
	.DB $4f
	.STRINGMAP pokemon, "I like her!"
	.DB $57
_CeladonMansion3FGameDesignerText::
	.DB $00
	.STRINGMAP pokemon, "Is that right?"
	.DB $51
	.STRINGMAP pokemon, "I'm the game"
	.DB $4f
	.STRINGMAP pokemon, "designer!"
	.DB $51
	.STRINGMAP pokemon, "Filling up your"
	.DB $4f
	.STRINGMAP pokemon, "#DEX is tough,"
	.DB $55
	.STRINGMAP pokemon, "but don't quit!"
	.DB $51
	.STRINGMAP pokemon, "When you finish,"
	.DB $4f
	.STRINGMAP pokemon, "come tell me!"
	.DB $57
_CeladonMansion3FGameDesignerCompletedDexText::
	.DB $00
	.STRINGMAP pokemon, "Wow! Excellent!"
	.DB $4f
	.STRINGMAP pokemon, "You completed"
	.DB $55
	.STRINGMAP pokemon, "your #DEX!"
	.DB $55
	.STRINGMAP pokemon, "Congratulations!"
	.DB $55
	.STRINGMAP pokemon, "...@"
	.DB $50
_CeladonMansion3FGameProgramPCText::
	.DB $00
	.STRINGMAP pokemon, "It's the game"
	.DB $4f
	.STRINGMAP pokemon, "program! Messing"
	.DB $55
	.STRINGMAP pokemon, "with it could bug"
	.DB $55
	.STRINGMAP pokemon, "out the game!"
	.DB $57
_CeladonMansion3FPlayingGamePCText::
	.DB $00
	.STRINGMAP pokemon, "Someone's playing"
	.DB $4f
	.STRINGMAP pokemon, "a game instead of"
	.DB $55
	.STRINGMAP pokemon, "working!"
	.DB $57
_CeladonMansion3FGameScriptPCText::
	.DB $00
	.STRINGMAP pokemon, "It's the script!"
	.DB $4f
	.STRINGMAP pokemon, "Better not look"
	.DB $55
	.STRINGMAP pokemon, "at the ending!"
	.DB $57
_CeladonMansion3FDevRoomSignText::
	.DB $00
	.STRINGMAP pokemon, "GAME FREAK"
	.DB $4f
	.STRINGMAP pokemon, "Development Room"
	.DB $57

; text/CeladonMansionRoof.asm
_CeladonMansionRoofHouseSignText::
	.DB $00
	.STRINGMAP pokemon, "I KNOW EVERYTHING!"
	.DB $57

; text/CeladonMansionRoofHouse.asm
_CeladonMansionRoofHouseHikerText::
	.DB $00
	.STRINGMAP pokemon, "I know everything"
	.DB $4f
	.STRINGMAP pokemon, "about the world"
	.DB $55
	.STRINGMAP pokemon, "of #MON in"
	.DB $55
	.STRINGMAP pokemon, "your GAME BOY!"
	.DB $51
	.STRINGMAP pokemon, "Get together with"
	.DB $4f
	.STRINGMAP pokemon, "your friends and"
	.DB $55
	.STRINGMAP pokemon, "trade #MON!"
	.DB $57

; text/CeladonPokecenter.asm
_CeladonPokecenterGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "# FLUTE awakens"
	.DB $4f
	.STRINGMAP pokemon, "#MON with a"
	.DB $55
	.STRINGMAP pokemon, "sound that only"
	.DB $55
	.STRINGMAP pokemon, "they can hear!"
	.DB $57
_CeladonPokecenterBeautyText::
	.DB $00
	.STRINGMAP pokemon, "I rode uphill on"
	.DB $4f
	.STRINGMAP pokemon, "CYCLING ROAD from"
	.DB $55
	.STRINGMAP pokemon, "FUCHSIA!"
	.DB $57

; text/CeladonGym.asm
_CeladonGymErikaPreBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hello. Lovely"
	.DB $4f
	.STRINGMAP pokemon, "weather isn't it?"
	.DB $55
	.STRINGMAP pokemon, "It's so pleasant."
	.DB $51
	.STRINGMAP pokemon, "...Oh dear..."
	.DB $4f
	.STRINGMAP pokemon, "I must have dozed"
	.DB $55
	.STRINGMAP pokemon, "off. Welcome."
	.DB $51
	.STRINGMAP pokemon, "My name is ERIKA."
	.DB $4f
	.STRINGMAP pokemon, "I am the LEADER"
	.DB $55
	.STRINGMAP pokemon, "of CELADON GYM."
	.DB $51
	.STRINGMAP pokemon, "I teach the art of"
	.DB $4f
	.STRINGMAP pokemon, "flower arranging."
	.DB $55
	.STRINGMAP pokemon, "My #MON are of"
	.DB $55
	.STRINGMAP pokemon, "the grass-type."
	.DB $51
	.STRINGMAP pokemon, "Oh, I'm sorry, I"
	.DB $4f
	.STRINGMAP pokemon, "had no idea that"
	.DB $55
	.STRINGMAP pokemon, "you wished to"
	.DB $55
	.STRINGMAP pokemon, "challenge me."
	.DB $51
	.STRINGMAP pokemon, "Very well, but I"
	.DB $4f
	.STRINGMAP pokemon, "shall not lose."
	.DB $57
_CeladonGymErikaReceivedRainbowBadgeText::
	.DB $00
	.STRINGMAP pokemon, "Oh!"
	.DB $4f
	.STRINGMAP pokemon, "I concede defeat."
	.DB $51
	.STRINGMAP pokemon, "You are remarkably"
	.DB $4f
	.STRINGMAP pokemon, "strong."
	.DB $51
	.STRINGMAP pokemon, "I must confer you"
	.DB $4f
	.STRINGMAP pokemon, "the RAINBOWBADGE."
	.DB $58
_CeladonGymErikaPostBattleAdviceText::
	.DB $00
	.STRINGMAP pokemon, "You are cataloging"
	.DB $4f
	.STRINGMAP pokemon, "#MON? I must"
	.DB $55
	.STRINGMAP pokemon, "say I'm impressed."
	.DB $51
	.STRINGMAP pokemon, "I would never"
	.DB $4f
	.STRINGMAP pokemon, "collect #MON"
	.DB $55
	.STRINGMAP pokemon, "if they were"
	.DB $55
	.STRINGMAP pokemon, "unattractive."
	.DB $57
_CeladonGymRainbowBadgeInfoText::
	.DB $00
	.STRINGMAP pokemon, "The RAINBOWBADGE"
	.DB $4f
	.STRINGMAP pokemon, "will make #MON"
	.DB $55
	.STRINGMAP pokemon, "up to L50 obey."
	.DB $51
	.STRINGMAP pokemon, "It also allows"
	.DB $4f
	.STRINGMAP pokemon, "#MON to use"
	.DB $55
	.STRINGMAP pokemon, "STRENGTH in and"
	.DB $55
	.STRINGMAP pokemon, "out of battle."
	.DB $51
	.STRINGMAP pokemon, "Please also take"
	.DB $4f
	.STRINGMAP pokemon, "this with you."
	.DB $57
_CeladonGymReceivedTM21Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_TM21ExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "TM21 contains"
	.DB $4f
	.STRINGMAP pokemon, "MEGA DRAIN."
	.DB $51
	.STRINGMAP pokemon, "Half the damage"
	.DB $4f
	.STRINGMAP pokemon, "it inflicts is"
	.DB $55
	.STRINGMAP pokemon, "drained to heal"
	.DB $55
	.STRINGMAP pokemon, "your #MON!"
	.DB $57
_CeladonGymTM21NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You should make"
	.DB $4f
	.STRINGMAP pokemon, "room for this."
	.DB $57
_CeladonGymBattleText2::
	.DB $00
	.STRINGMAP pokemon, "Hey!"
	.DB $51
	.STRINGMAP pokemon, "You are not"
	.DB $4f
	.STRINGMAP pokemon, "allowed in here!"
	.DB $57
_CeladonGymEndBattleText2::
	.DB $00
	.STRINGMAP pokemon, "You're"
	.DB $4f
	.STRINGMAP pokemon, "too rough!"
	.DB $58
_CeladonGymAfterBattleText2::
	.DB $00
	.STRINGMAP pokemon, "Bleaah!"
	.DB $4f
	.STRINGMAP pokemon, "I hope ERIKA"
	.DB $55
	.STRINGMAP pokemon, "wipes you out!"
	.DB $57
_CeladonGymBattleText3::
	.DB $00
	.STRINGMAP pokemon, "I was getting"
	.DB $4f
	.STRINGMAP pokemon, "bored."
	.DB $57
_CeladonGymEndBattleText3::
	.DB $00
	.STRINGMAP pokemon, "My"
	.DB $4f
	.STRINGMAP pokemon, "makeup!"
	.DB $58
_CeladonGymAfterBattleText3::
	.DB $00
	.STRINGMAP pokemon, "Grass-type #MON"
	.DB $4f
	.STRINGMAP pokemon, "are tough against"
	.DB $55
	.STRINGMAP pokemon, "the water-type!"
	.DB $51
	.STRINGMAP pokemon, "They also have an"
	.DB $4f
	.STRINGMAP pokemon, "edge on rock and"
	.DB $55
	.STRINGMAP pokemon, "ground #MON!"
	.DB $57
_CeladonGymBattleText4::
	.DB $00
	.STRINGMAP pokemon, "Aren't you the"
	.DB $4f
	.STRINGMAP pokemon, "peeping Tom?"
	.DB $57
_CeladonGymEndBattleText4::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "in shock!"
	.DB $58
_CeladonGymAfterBattleText4::
	.DB $00
	.STRINGMAP pokemon, "Oh, you weren't"
	.DB $4f
	.STRINGMAP pokemon, "peeping? We get a"
	.DB $55
	.STRINGMAP pokemon, "lot of gawkers!"
	.DB $57
_CeladonGymBattleText5::
	.DB $00
	.STRINGMAP pokemon, "Look at my grass"
	.DB $4f
	.STRINGMAP pokemon, "#MON!"
	.DB $51
	.STRINGMAP pokemon, "They're so easy"
	.DB $4f
	.STRINGMAP pokemon, "to raise!"
	.DB $57
_CeladonGymEndBattleText5::
	.DB $00
	.STRINGMAP pokemon, "No!"
	.DB $58
_CeladonGymAfterBattleText5::
	.DB $00
	.STRINGMAP pokemon, "We only use grass-"
	.DB $4f
	.STRINGMAP pokemon, "type #MON at"
	.DB $55
	.STRINGMAP pokemon, "our GYM!"
	.DB $51
	.STRINGMAP pokemon, "We also use them"
	.DB $4f
	.STRINGMAP pokemon, "for making flower"
	.DB $55
	.STRINGMAP pokemon, "arrangements!"
	.DB $57
_CeladonGymBattleText6::
	.DB $00
	.STRINGMAP pokemon, "Don't bring any"
	.DB $4f
	.STRINGMAP pokemon, "bugs or fire"
	.DB $55
	.STRINGMAP pokemon, "#MON in here!"
	.DB $57
_CeladonGymEndBattleText6::
	.DB $00
	.STRINGMAP pokemon, "Oh!"
	.DB $4f
	.STRINGMAP pokemon, "You!"
	.DB $58
_CeladonGymAfterBattleText6::
	.DB $00
	.STRINGMAP pokemon, "Our LEADER, ERIKA,"
	.DB $4f
	.STRINGMAP pokemon, "might be quiet,"
	.DB $55
	.STRINGMAP pokemon, "but she's also"
	.DB $55
	.STRINGMAP pokemon, "very skilled!"
	.DB $57
_CeladonGymBattleText7::
	.DB $00
	.STRINGMAP pokemon, "Pleased to meet"
	.DB $4f
	.STRINGMAP pokemon, "you. My hobby is"
	.DB $55
	.STRINGMAP pokemon, "#MON training."
	.DB $57
_CeladonGymEndBattleText7::
	.DB $00
	.STRINGMAP pokemon, "Oh!"
	.DB $4f
	.STRINGMAP pokemon, "Splendid!"
	.DB $58
_CeladonGymAfterBattleText7::
	.DB $00
	.STRINGMAP pokemon, "I have a blind"
	.DB $4f
	.STRINGMAP pokemon, "date coming up."
	.DB $55
	.STRINGMAP pokemon, "I have to learn"
	.DB $55
	.STRINGMAP pokemon, "to be polite."
	.DB $57
_CeladonGymBattleText8::
	.DB $00
	.STRINGMAP pokemon, "Welcome to"
	.DB $4f
	.STRINGMAP pokemon, "CELADON GYM!"
	.DB $51
	.STRINGMAP pokemon, "You better not"
	.DB $4f
	.STRINGMAP pokemon, "underestimate"
	.DB $55
	.STRINGMAP pokemon, "girl power!"
	.DB $57
_CeladonGymEndBattleText8::
	.DB $00
	.STRINGMAP pokemon, "Oh!"
	.DB $4f
	.STRINGMAP pokemon, "Beaten!"
	.DB $58
_CeladonGymAfterBattleText8::
	.DB $00
	.STRINGMAP pokemon, "I didn't bring my"
	.DB $4f
	.STRINGMAP pokemon, "best #MON!"
	.DB $51
	.STRINGMAP pokemon, "Wait 'til next"
	.DB $4f
	.STRINGMAP pokemon, "time!"
	.DB $57

; text/GameCorner.asm
_GameCornerBeauty1Text::
	.DB $00
	.STRINGMAP pokemon, "Welcome!"
	.DB $51
	.STRINGMAP pokemon, "You can exchange"
	.DB $4f
	.STRINGMAP pokemon, "your coins for"
	.DB $55
	.STRINGMAP pokemon, "fabulous prizes"
	.DB $55
	.STRINGMAP pokemon, "next door."
	.DB $57
_GameCornerClerk1DoYouNeedSomeGameCoinsText::
	.DB $00
	.STRINGMAP pokemon, "Welcome to ROCKET"
	.DB $4f
	.STRINGMAP pokemon, "GAME CORNER!"
	.DB $51
	.STRINGMAP pokemon, "Do you need some"
	.DB $4f
	.STRINGMAP pokemon, "game coins?"
	.DB $51
	.STRINGMAP pokemon, "It's ¥1000 for 50"
	.DB $4f
	.STRINGMAP pokemon, "coins. Would you"
	.DB $55
	.STRINGMAP pokemon, "like some?"
	.DB $57
_GameCornerClerk1ThanksHereAre50CoinsText::
	.DB $00
	.STRINGMAP pokemon, "Thanks! Here are"
	.DB $4f
	.STRINGMAP pokemon, "your 50 coins!"
	.DB $57
_GameCornerClerk1PleaseComePlaySometimeText::
	.DB $00
	.STRINGMAP pokemon, "No? Please come"
	.DB $4f
	.STRINGMAP pokemon, "play sometime!"
	.DB $57
_GameCornerClerk1CantAffordTheCoinsText::
	.DB $00
	.STRINGMAP pokemon, "You can't afford"
	.DB $4f
	.STRINGMAP pokemon, "the coins!"
	.DB $57
_GameCornerClerk1CoinCaseIsFullText::
	.DB $00
	.STRINGMAP pokemon, "Oops! Your COIN"
	.DB $4f
	.STRINGMAP pokemon, "CASE is full."
	.DB $57
_GameCornerClerk1DontHaveCoinCaseText::
	.DB $00
	.STRINGMAP pokemon, "You don't have a"
	.DB $4f
	.STRINGMAP pokemon, "COIN CASE!"
	.DB $57
_GameCornerMiddleAgedMan1Text::
	.DB $00
	.STRINGMAP pokemon, "Keep this quiet."
	.DB $51
	.STRINGMAP pokemon, "It's rumored that"
	.DB $4f
	.STRINGMAP pokemon, "this place is run"
	.DB $55
	.STRINGMAP pokemon, "by TEAM ROCKET."
	.DB $57
_GameCornerBeauty2Text::
	.DB $00
	.STRINGMAP pokemon, "I think these"
	.DB $4f
	.STRINGMAP pokemon, "machines have"
	.DB $55
	.STRINGMAP pokemon, "different odds."
	.DB $57
_GameCornerFishingGuruWantToPlayText::
	.DB $00
	.STRINGMAP pokemon, "Kid, do you want"
	.DB $4f
	.STRINGMAP pokemon, "to play?"
	.DB $58
_GameCornerFishingGuruReceived10CoinsText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "10 coins!@"
	.DB $50
_GameCornerFishingGuruDontNeedMyCoinsText::
	.DB $00
	.STRINGMAP pokemon, "You don't need my"
	.DB $4f
	.STRINGMAP pokemon, "coins!"
	.DB $57
_GameCornerFishingGuruWinsComeAndGoText::
	.DB $00
	.STRINGMAP pokemon, "Wins seem to come"
	.DB $4f
	.STRINGMAP pokemon, "and go."
	.DB $57
_GameCornerMiddleAgedWomanText::
	.DB $00
	.STRINGMAP pokemon, "I'm having a"
	.DB $4f
	.STRINGMAP pokemon, "wonderful time!"
	.DB $57
_GameCornerGymGuideChampInMakingText::
	.DB $00
	.STRINGMAP pokemon, "Hey!"
	.DB $51
	.STRINGMAP pokemon, "You have better"
	.DB $4f
	.STRINGMAP pokemon, "things to do,"
	.DB $55
	.STRINGMAP pokemon, "champ in making!"
	.DB $51
	.STRINGMAP pokemon, "CELADON GYM's"
	.DB $4f
	.STRINGMAP pokemon, "LEADER is ERIKA!"
	.DB $55
	.STRINGMAP pokemon, "She uses grass-"
	.DB $55
	.STRINGMAP pokemon, "type #MON!"
	.DB $51
	.STRINGMAP pokemon, "She might appear"
	.DB $4f
	.STRINGMAP pokemon, "docile, but don't"
	.DB $55
	.STRINGMAP pokemon, "be fooled!"
	.DB $57
_GameCornerGymGuideTheyOfferRarePokemonText::
	.DB $00
	.STRINGMAP pokemon, "They offer rare"
	.DB $4f
	.STRINGMAP pokemon, "#MON that can"
	.DB $55
	.STRINGMAP pokemon, "be exchanged for"
	.DB $55
	.STRINGMAP pokemon, "your coins."
	.DB $51
	.STRINGMAP pokemon, "But, I just can't"
	.DB $4f
	.STRINGMAP pokemon, "seem to win!"
	.DB $57
_GameCornerGamblerText::
	.DB $00
	.STRINGMAP pokemon, "Games are scary!"
	.DB $4f
	.STRINGMAP pokemon, "It's so easy to"
	.DB $55
	.STRINGMAP pokemon, "get hooked!"
	.DB $57
_GameCornerClerk2WantSomeCoinsText::
	.DB $00
	.STRINGMAP pokemon, "What's up? Want"
	.DB $4f
	.STRINGMAP pokemon, "some coins?"
	.DB $58
_GameCornerClerk2Received20CoinsText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "20 coins!@"
	.DB $50
_GameCornerClerk2YouHaveLotsOfCoinsText::
	.DB $00
	.STRINGMAP pokemon, "You have lots of"
	.DB $4f
	.STRINGMAP pokemon, "coins!"
	.DB $57
_GameCornerClerk2INeedMoreCoinsText::
	.DB $00
	.STRINGMAP pokemon, "Darn! I need more"
	.DB $4f
	.STRINGMAP pokemon, "coins for the"
	.DB $55
	.STRINGMAP pokemon, "#MON I want!"
	.DB $57
_GameCornerGentlemanThrowingMeOffText::
	.DB $00
	.STRINGMAP pokemon, "Hey, what? You're"
	.DB $4f
	.STRINGMAP pokemon, "throwing me off!"
	.DB $55
	.STRINGMAP pokemon, "Here are some"
	.DB $55
	.STRINGMAP pokemon, "coins, shoo!"
	.DB $58
_GameCornerGentlemanReceived20CoinsText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "20 coins!@"
	.DB $50
_GameCornerGentlemanYouGotYourOwnCoinsText::
	.DB $00
	.STRINGMAP pokemon, "You've got your"
	.DB $4f
	.STRINGMAP pokemon, "own coins!"
	.DB $57
_GameCornerGentlemanCloselyWatchTheReelsText::
	.DB $00
	.STRINGMAP pokemon, "The trick is to"
	.DB $4f
	.STRINGMAP pokemon, "watch the reels"
	.DB $55
	.STRINGMAP pokemon, "closely!"
	.DB $57
_GameCornerRocketImGuardingThisPosterText::
	.DB $00
	.STRINGMAP pokemon, "I'm guarding this"
	.DB $4f
	.STRINGMAP pokemon, "poster!"
	.DB $55
	.STRINGMAP pokemon, "Go away, or else!"
	.DB $57
_GameCornerRocketBattleEndText::
	.DB $00
	.STRINGMAP pokemon, "Dang!"
	.DB $58
_GameCornerRocketAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Our hideout might"
	.DB $4f
	.STRINGMAP pokemon, "be discovered! I"
	.DB $55
	.STRINGMAP pokemon, "better tell BOSS!"
	.DB $57
_GameCornerPosterSwitchBehindPosterText::
	.DB $00
	.STRINGMAP pokemon, "Hey!"
	.DB $51
	.STRINGMAP pokemon, "A switch behind"
	.DB $4f
	.STRINGMAP pokemon, "the poster!?"
	.DB $55
	.STRINGMAP pokemon, "Let's push it!@"
	.DB $50
_GameCornerOopsForgotCoinCaseText::
	.DB $00
	.STRINGMAP pokemon, "Oops! Forgot the"
	.DB $4f
	.STRINGMAP pokemon, "COIN CASE!"
	.DB $57

; text/CeladonMart5F.asm
_CeladonMart5FGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "#MON ability"
	.DB $4f
	.STRINGMAP pokemon, "enhancers can be"
	.DB $55
	.STRINGMAP pokemon, "bought only here."
	.DB $51
	.STRINGMAP pokemon, "Use CALCIUM to"
	.DB $4f
	.STRINGMAP pokemon, "increase SPECIAL"
	.DB $55
	.STRINGMAP pokemon, "abilities."
	.DB $51
	.STRINGMAP pokemon, "Use CARBOS to"
	.DB $4f
	.STRINGMAP pokemon, "increase SPEED."
	.DB $57
_CeladonMart5FSailorText::
	.DB $00
	.STRINGMAP pokemon, "I'm here for"
	.DB $4f
	.STRINGMAP pokemon, "#MON ability"
	.DB $55
	.STRINGMAP pokemon, "enhancers."
	.DB $51
	.STRINGMAP pokemon, "PROTEIN increases"
	.DB $4f
	.STRINGMAP pokemon, "ATTACK power."
	.DB $51
	.STRINGMAP pokemon, "IRON increases"
	.DB $4f
	.STRINGMAP pokemon, "DEFENSE!"
	.DB $57
_CeladonMart5FCurrentFloorSignText::
	.DB $00
	.STRINGMAP pokemon, "5F: DRUG STORE"
	.DB $57

; text/GameCornerPrizeRoom.asm
_GameCornerPrizeRoomBaldingGuyText::
	.DB $00
	.STRINGMAP pokemon, "I sure do fancy"
	.DB $4f
	.STRINGMAP pokemon, "that PORYGON!"
	.DB $51
	.STRINGMAP pokemon, "But, it's hard to"
	.DB $4f
	.STRINGMAP pokemon, "win at slots!"
	.DB $57
_GameCornerPrizeRoomGamblerText::
	.DB $00
	.STRINGMAP pokemon, "I had a major"
	.DB $4f
	.STRINGMAP pokemon, "haul today!"
	.DB $57

; text/CeladonDiner.asm
_CeladonDinerCookText::
	.DB $00
	.STRINGMAP pokemon, "Hi!"
	.DB $51
	.STRINGMAP pokemon, "We're taking a"
	.DB $4f
	.STRINGMAP pokemon, "break now."
	.DB $57
_CeladonDinerMiddleAgedWomanText::
	.DB $00
	.STRINGMAP pokemon, "My #MON are"
	.DB $4f
	.STRINGMAP pokemon, "weak, so I often"
	.DB $55
	.STRINGMAP pokemon, "have to go to the"
	.DB $55
	.STRINGMAP pokemon, "DRUG STORE."
	.DB $57
_CeladonDinerMiddleAgedManText::
	.DB $00
	.STRINGMAP pokemon, "Psst! There's a"
	.DB $4f
	.STRINGMAP pokemon, "basement under"
	.DB $55
	.STRINGMAP pokemon, "the GAME CORNER."
	.DB $57
_CeladonDinerFisherText::
	.DB $00
	.STRINGMAP pokemon, "Munch..."
	.DB $51
	.STRINGMAP pokemon, "The man at that"
	.DB $4f
	.STRINGMAP pokemon, "table lost it all"
	.DB $55
	.STRINGMAP pokemon, "at the slots."
	.DB $57
_CeladonDinerGymGuideImFlatOutBustedText::
	.DB $00
	.STRINGMAP pokemon, "Go ahead! Laugh!"
	.DB $51
	.STRINGMAP pokemon, "I'm flat out"
	.DB $4f
	.STRINGMAP pokemon, "busted!"
	.DB $51
	.STRINGMAP pokemon, "No more slots for"
	.DB $4f
	.STRINGMAP pokemon, "me! I'm going"
	.DB $55
	.STRINGMAP pokemon, "straight!"
	.DB $51
	.STRINGMAP pokemon, "Here! I won't be"
	.DB $4f
	.STRINGMAP pokemon, "needing this any-"
	.DB $55
	.STRINGMAP pokemon, "more!"
	.DB $58
_CeladonDinerGymGuideReceivedCoinCaseText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "a @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_CeladonDinerGymGuideCoinCaseNoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Make room for"
	.DB $4f
	.STRINGMAP pokemon, "this!"
	.DB $57
_CeladonDinerGymGuideWinItBackText::
	.DB $00
	.STRINGMAP pokemon, "I always thought"
	.DB $4f
	.STRINGMAP pokemon, "I was going to"
	.DB $55
	.STRINGMAP pokemon, "win it back..."
	.DB $57

; text/CeladonChiefHouse.asm
_CeladonChiefHouseChiefText::
	.DB $00
	.STRINGMAP pokemon, "Hehehe! The slots"
	.DB $4f
	.STRINGMAP pokemon, "just reel in the"
	.DB $55
	.STRINGMAP pokemon, "dough, big time!"
	.DB $57
_CeladonChiefHouseRocketText::
	.DB $00
	.STRINGMAP pokemon, "CHIEF!"
	.DB $51
	.STRINGMAP pokemon, "We just shipped"
	.DB $4f
	.STRINGMAP pokemon, "2000 #MON as"
	.DB $55
	.STRINGMAP pokemon, "slot prizes!"
	.DB $57
_CeladonChiefHouseSailorText::
	.DB $00
	.STRINGMAP pokemon, "Don't touch the"
	.DB $4f
	.STRINGMAP pokemon, "poster at the"
	.DB $55
	.STRINGMAP pokemon, "GAME CORNER!"
	.DB $51
	.STRINGMAP pokemon, "There's no secret"
	.DB $4f
	.STRINGMAP pokemon, "switch behind it!"
	.DB $57

; text/CeladonHotel.asm
_CeladonHotelGrannyText::
	.DB $00
	.STRINGMAP pokemon, "#MON? No, this"
	.DB $4f
	.STRINGMAP pokemon, "is a hotel for"
	.DB $55
	.STRINGMAP pokemon, "people."
	.DB $51
	.STRINGMAP pokemon, "We're full up."
	.DB $57
_CeladonHotelBeautyText::
	.DB $00
	.STRINGMAP pokemon, "I'm on vacation"
	.DB $4f
	.STRINGMAP pokemon, "with my brother"
	.DB $55
	.STRINGMAP pokemon, "and boy friend."
	.DB $51
	.STRINGMAP pokemon, "CELADON is such a"
	.DB $4f
	.STRINGMAP pokemon, "pretty city!"
	.DB $57
_CeladonHotelSuperNerdText::
	.DB $00
	.STRINGMAP pokemon, "Why did she bring"
	.DB $4f
	.STRINGMAP pokemon, "her brother?"
	.DB $57

; text/FuchsiaMart.asm
_FuchsiaMartMiddleAgedManText::
	.DB $00
	.STRINGMAP pokemon, "Do you have a"
	.DB $4f
	.STRINGMAP pokemon, "SAFARI ZONE flag?"
	.DB $51
	.STRINGMAP pokemon, "What about cards"
	.DB $4f
	.STRINGMAP pokemon, "or calendars?"
	.DB $57
_FuchsiaMartCooltrainerFText::
	.DB $00
	.STRINGMAP pokemon, "Did you try X"
	.DB $4f
	.STRINGMAP pokemon, "SPEED? It speeds"
	.DB $55
	.STRINGMAP pokemon, "up a #MON in"
	.DB $55
	.STRINGMAP pokemon, "battle!"
	.DB $57

; text/FuchsiaBillsGrandpasHouse.asm
_FuchsiaBillsGrandpasHouseMiddleAgedWomanText::
	.DB $00
	.STRINGMAP pokemon, "SAFARI ZONE's"
	.DB $4f
	.STRINGMAP pokemon, "WARDEN is old,"
	.DB $55
	.STRINGMAP pokemon, "but still active!"
	.DB $51
	.STRINGMAP pokemon, "All his teeth are"
	.DB $4f
	.STRINGMAP pokemon, "false, though."
	.DB $57
_FuchsiaBillsGrandpasHouseBillsGrandpaText::
	.DB $00
	.STRINGMAP pokemon, "Hmm? You've met"
	.DB $4f
	.STRINGMAP pokemon, "BILL?"
	.DB $51
	.STRINGMAP pokemon, "He's my grandson!"
	.DB $51
	.STRINGMAP pokemon, "He always liked"
	.DB $4f
	.STRINGMAP pokemon, "collecting things"
	.DB $55
	.STRINGMAP pokemon, "even as a child!"
	.DB $57
_FuchsiaBillsGrandpasHouseYoungsterText::
	.DB $00
	.STRINGMAP pokemon, "BILL files his"
	.DB $4f
	.STRINGMAP pokemon, "own #MON data"
	.DB $55
	.STRINGMAP pokemon, "on his PC!"
	.DB $51
	.STRINGMAP pokemon, "Did he show you?"
	.DB $57

; text/FuchsiaPokecenter.asm
_FuchsiaPokecenterRockerText::
	.DB $00
	.STRINGMAP pokemon, "You can't win"
	.DB $4f
	.STRINGMAP pokemon, "with just one"
	.DB $55
	.STRINGMAP pokemon, "strong #MON."
	.DB $51
	.STRINGMAP pokemon, "It's tough, but"
	.DB $4f
	.STRINGMAP pokemon, "you have to raise"
	.DB $55
	.STRINGMAP pokemon, "them evenly."
	.DB $57
_FuchsiaPokecenterCooltrainerFText::
	.DB $00
	.STRINGMAP pokemon, "There's a narrow"
	.DB $4f
	.STRINGMAP pokemon, "trail west of"
	.DB $55
	.STRINGMAP pokemon, "VIRIDIAN CITY."
	.DB $51
	.STRINGMAP pokemon, "It goes to #MON"
	.DB $4f
	.STRINGMAP pokemon, "LEAGUE HQ."
	.DB $55
	.STRINGMAP pokemon, "The HQ governs"
	.DB $55
	.STRINGMAP pokemon, "all trainers."
	.DB $57

; text/WardensHouse.asm
_WardensHouseWardenGibberish1Text::
	.DB $00
	.STRINGMAP pokemon, "WARDEN: Hif fuff"
	.DB $4f
	.STRINGMAP pokemon, "hefifoo!"
	.DB $51
	.STRINGMAP pokemon, "Ha lof ha feef ee"
	.DB $4f
	.STRINGMAP pokemon, "hafahi ho. Heff"
	.DB $55
	.STRINGMAP pokemon, "hee fwee!"
	.DB $57
_WardensHouseWardenGibberish2Text::
	.DB $00
	.STRINGMAP pokemon, "Ah howhee ho hoo!"
	.DB $4f
	.STRINGMAP pokemon, "Eef ee hafahi ho!"
	.DB $57
_WardensHouseWardenGibberish3Text::
	.DB $00
	.STRINGMAP pokemon, "Ha? He ohay heh"
	.DB $4f
	.STRINGMAP pokemon, "ha hoo ee haheh!"
	.DB $57
_WardensHouseWardenGaveTheGoldTeethText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> gave the"
	.DB $4f
	.STRINGMAP pokemon, "GOLD TEETH to the"
	.DB $55
	.STRINGMAP pokemon, "WARDEN!@"
	.DB $50
_WardensHouseWardenTeethPoppedInHisTeethText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "The WARDEN popped"
	.DB $4f
	.STRINGMAP pokemon, "in his teeth!"
	.DB $58
_WardensHouseWardenThanksText::
	.DB $00
	.STRINGMAP pokemon, "WARDEN: Thanks,"
	.DB $4f
	.STRINGMAP pokemon, "kid! No one could"
	.DB $55
	.STRINGMAP pokemon, "understand a word"
	.DB $55
	.STRINGMAP pokemon, "that I said."
	.DB $51
	.STRINGMAP pokemon, "I couldn't work"
	.DB $4f
	.STRINGMAP pokemon, "that way."
	.DB $55
	.STRINGMAP pokemon, "Let me give you"
	.DB $55
	.STRINGMAP pokemon, "something for"
	.DB $55
	.STRINGMAP pokemon, "your trouble."
	.DB $58
_WardensHouseWardenReceivedHM04Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_WardensHouseWardenHM04ExplanationText::
	.DB $00
	.STRINGMAP pokemon, "WARDEN: HM04"
	.DB $4f
	.STRINGMAP pokemon, "teaches STRENGTH!"
	.DB $51
	.STRINGMAP pokemon, "It lets #MON"
	.DB $4f
	.STRINGMAP pokemon, "move boulders"
	.DB $55
	.STRINGMAP pokemon, "when you're out-"
	.DB $55
	.STRINGMAP pokemon, "side of battle."
	.DB $51
	.STRINGMAP pokemon, "Oh yes, did you"
	.DB $4f
	.STRINGMAP pokemon, "find SECRET HOUSE"
	.DB $55
	.STRINGMAP pokemon, "in SAFARI ZONE?"
	.DB $51
	.STRINGMAP pokemon, "If you do, you"
	.DB $4f
	.STRINGMAP pokemon, "win an HM!"
	.DB $51
	.STRINGMAP pokemon, "I hear it's the"
	.DB $4f
	.STRINGMAP pokemon, "rare SURF HM."
	.DB $57
_WardensHouseWardenHM04NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Your pack is"
	.DB $4f
	.STRINGMAP pokemon, "stuffed full!"
	.DB $57
_WardensHouseDisplayPhotosAndFossilsText::
	.DB $00
	.STRINGMAP pokemon, "#MON photos"
	.DB $4f
	.STRINGMAP pokemon, "and fossils."
	.DB $57
_WardensHouseDisplayMerchandiseText::
	.DB $00
	.STRINGMAP pokemon, "Old #MON"
	.DB $4f
	.STRINGMAP pokemon, "merchandise."
	.DB $57

; text/SafariZoneGate.asm
_SafariZoneGateSafariZoneWorker1Text::
	.DB $00
	.STRINGMAP pokemon, "Welcome to the"
	.DB $4f
	.STRINGMAP pokemon, "SAFARI ZONE!"
	.DB $57
_SafariZoneGateSafariZoneWorker1WouldYouLikeToJoinText::
	.DB $00
	.STRINGMAP pokemon, "For just ¥500,"
	.DB $4f
	.STRINGMAP pokemon, "you can catch all"
	.DB $55
	.STRINGMAP pokemon, "the #MON you"
	.DB $55
	.STRINGMAP pokemon, "want in the park!"
	.DB $51
	.STRINGMAP pokemon, "Would you like to"
	.DB $4f
	.STRINGMAP pokemon, "join the hunt?@"
	.DB $50
_SafariZoneGateSafariZoneWorker1ThatllBe500PleaseText::
	.DB $00
	.STRINGMAP pokemon, "That'll be ¥500"
	.DB $4f
	.STRINGMAP pokemon, "please!"
	.DB $51
	.STRINGMAP pokemon, "We only use a"
	.DB $4f
	.STRINGMAP pokemon, "special # BALL"
	.DB $55
	.STRINGMAP pokemon, "here."
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "30 SAFARI BALLs!@"
	.DB $50
_SafariZoneGateSafariZoneWorker1CallYouOnThePAText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "We'll call you on"
	.DB $4f
	.STRINGMAP pokemon, "the PA when you"
	.DB $55
	.STRINGMAP pokemon, "run out of time"
	.DB $55
	.STRINGMAP pokemon, "or SAFARI BALLs!"
	.DB $57
_SafariZoneGateSafariZoneWorker1PleaseComeAgainText::
	.DB $00
	.STRINGMAP pokemon, "OK! Please come"
	.DB $4f
	.STRINGMAP pokemon, "again!"
	.DB $57
_SafariZoneGateSafariZoneWorker1NotEnoughMoneyText::
	.DB $00
	.STRINGMAP pokemon, "Oops! Not enough"
	.DB $4f
	.STRINGMAP pokemon, "money!"
	.DB $57
_SafariZoneGateSafariZoneWorker1LeavingEarlyText::
	.DB $00
	.STRINGMAP pokemon, "Leaving early?@"
	.DB $50
_SafariZoneGateSafariZoneWorker1ReturnSafariBallsText::
	.DB $00
	.STRINGMAP pokemon, "Please return any"
	.DB $4f
	.STRINGMAP pokemon, "SAFARI BALLs you"
	.DB $55
	.STRINGMAP pokemon, "have left."
	.DB $57
_SafariZoneGateSafariZoneWorker1GoodLuckText::
	.DB $00
	.STRINGMAP pokemon, "Good Luck!"
	.DB $57
_SafariZoneGateSafariZoneWorker1GoodHaulComeAgainText::
	.DB $00
	.STRINGMAP pokemon, "Did you get a"
	.DB $4f
	.STRINGMAP pokemon, "good haul?"
	.DB $55
	.STRINGMAP pokemon, "Come again!"
	.DB $57
_SafariZoneGateSafariZoneWorker2FirstTimeHereText::
	.DB $00
	.STRINGMAP pokemon, "Hi! Is it your"
	.DB $4f
	.STRINGMAP pokemon, "first time here?"
	.DB $57
_SafariZoneGateSafariZoneWorker2SafariZoneExplanationText::
	.DB $00
	.STRINGMAP pokemon, "SAFARI ZONE has 4"
	.DB $4f
	.STRINGMAP pokemon, "zones in it."
	.DB $51
	.STRINGMAP pokemon, "Each zone has"
	.DB $4f
	.STRINGMAP pokemon, "different kinds"
	.DB $55
	.STRINGMAP pokemon, "of #MON. Use"
	.DB $55
	.STRINGMAP pokemon, "SAFARI BALLs to"
	.DB $55
	.STRINGMAP pokemon, "catch them!"
	.DB $51
	.STRINGMAP pokemon, "When you run out"
	.DB $4f
	.STRINGMAP pokemon, "of time or SAFARI"
	.DB $55
	.STRINGMAP pokemon, "BALLs, it's game"
	.DB $55
	.STRINGMAP pokemon, "over for you!"
	.DB $51
	.STRINGMAP pokemon, "Before you go,"
	.DB $4f
	.STRINGMAP pokemon, "open an unused"
	.DB $55
	.STRINGMAP pokemon, "#MON BOX so"
	.DB $55
	.STRINGMAP pokemon, "there's room for"
	.DB $55
	.STRINGMAP pokemon, "new #MON!"
	.DB $57
_SafariZoneGateSafariZoneWorker2YoureARegularHereText::
	.DB $00
	.STRINGMAP pokemon, "Sorry, you're a"
	.DB $4f
	.STRINGMAP pokemon, "regular here!"
	.DB $57

; text/FuchsiaGym.asm
_FuchsiaGymKogaBeforeBattleText::
	.DB $00
	.STRINGMAP pokemon, "KOGA: Fwahahaha!"
	.DB $51
	.STRINGMAP pokemon, "A mere child like"
	.DB $4f
	.STRINGMAP pokemon, "you dares to"
	.DB $55
	.STRINGMAP pokemon, "challenge me?"
	.DB $51
	.STRINGMAP pokemon, "Very well, I"
	.DB $4f
	.STRINGMAP pokemon, "shall show you"
	.DB $55
	.STRINGMAP pokemon, "true terror as a"
	.DB $55
	.STRINGMAP pokemon, "ninja master!"
	.DB $51
	.STRINGMAP pokemon, "You shall feel"
	.DB $4f
	.STRINGMAP pokemon, "the despair of"
	.DB $55
	.STRINGMAP pokemon, "poison and sleep"
	.DB $55
	.STRINGMAP pokemon, "techniques!"
	.DB $57
_FuchsiaGymKogaReceivedSoulBadgeText::
	.DB $00
	.STRINGMAP pokemon, "Humph!"
	.DB $4f
	.STRINGMAP pokemon, "You have proven"
	.DB $55
	.STRINGMAP pokemon, "your worth!"
	.DB $51
	.STRINGMAP pokemon, "Here! Take the"
	.DB $4f
	.STRINGMAP pokemon, "SOULBADGE!"
	.DB $58

Bank39TextEnd::
