; Generated by convert_text_bank.py from:
;   data/text/text_5.asm
;   text/PalletTown.asm
;   text/ViridianCity.asm
;   text/PewterCity.asm
;   text/CeruleanCity.asm
;   text/LavenderTown.asm
;   text/VermilionCity.asm
;   text/CeladonCity.asm
;   text/FuchsiaCity.asm
;   text/CinnabarIsland.asm
;   text/SaffronCity.asm
;   data/text/text_6.asm
.STRINGMAPTABLE pokemon "wla/pokemon.tbl"

; data/text/text_5.asm
_CableClubNPCPleaseComeAgainText::
	.DB $00
	.STRINGMAP pokemon, "Please come again!"
	.DB $57
_CableClubNPCMakingPreparationsText::
	.DB $00
	.STRINGMAP pokemon, "We're making"
	.DB $4f
	.STRINGMAP pokemon, "preparations."
	.DB $55
	.STRINGMAP pokemon, "Please wait."
	.DB $57
_UsedStrengthText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " used"
	.DB $4f
	.STRINGMAP pokemon, "STRENGTH.@"
	.DB $50
_CanMoveBouldersText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " can"
	.DB $4f
	.STRINGMAP pokemon, "move boulders."
	.DB $58
_CurrentTooFastText::
	.DB $00
	.STRINGMAP pokemon, "The current is"
	.DB $4f
	.STRINGMAP pokemon, "much too fast!"
	.DB $58
_CyclingIsFunText::
	.DB $00
	.STRINGMAP pokemon, "Cycling is fun!"
	.DB $4f
	.STRINGMAP pokemon, "Forget SURFing!"
	.DB $58
_FlashLightsAreaText::
	.DB $00
	.STRINGMAP pokemon, "A blinding FLASH"
	.DB $4f
	.STRINGMAP pokemon, "lights the area!"
	.DB $58
_WarpToLastPokemonCenterText::
	.DB $00
	.STRINGMAP pokemon, "Warp to the last"
	.DB $4f
	.STRINGMAP pokemon, "#MON CENTER."
	.DB $57
_CannotUseTeleportNowText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " can't"
	.DB $4f
	.STRINGMAP pokemon, "use TELEPORT now."
	.DB $58
_CannotFlyHereText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " can't"
	.DB $4f
	.STRINGMAP pokemon, "FLY here."
	.DB $58
_NotHealthyEnoughText::
	.DB $00
	.STRINGMAP pokemon, "Not healthy"
	.DB $4f
	.STRINGMAP pokemon, "enough."
	.DB $58
_NewBadgeRequiredText::
	.DB $00
	.STRINGMAP pokemon, "No! A new BADGE"
	.DB $4f
	.STRINGMAP pokemon, "is required."
	.DB $58
_CannotUseItemsHereText::
	.DB $00
	.STRINGMAP pokemon, "You can't use items"
	.DB $4f
	.STRINGMAP pokemon, "here."
	.DB $58
_CannotGetOffHereText::
	.DB $00
	.STRINGMAP pokemon, "You can't get off"
	.DB $4f
	.STRINGMAP pokemon, "here."
	.DB $58
_GotMonText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> got"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_SentToBoxText::
	.DB $00
	.STRINGMAP pokemon, "There's no more"
	.DB $4f
	.STRINGMAP pokemon, "room for #MON!"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wBoxMonNicks
	.DB $00
	.STRINGMAP pokemon, " was"
	.DB $55
	.STRINGMAP pokemon, "sent to #MON"
	.DB $55
	.STRINGMAP pokemon, "BOX @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, " on PC!"
	.DB $57
_BoxIsFullText::
	.DB $00
	.STRINGMAP pokemon, "There's no more"
	.DB $4f
	.STRINGMAP pokemon, "room for #MON!"
	.DB $51
	.STRINGMAP pokemon, "The #MON BOX"
	.DB $4f
	.STRINGMAP pokemon, "is full and can't"
	.DB $55
	.STRINGMAP pokemon, "accept any more!"
	.DB $51
	.STRINGMAP pokemon, "Change the BOX at"
	.DB $4f
	.STRINGMAP pokemon, "a #MON CENTER!"
	.DB $57

; text/PalletTown.asm
_PalletTownOakHeyWaitDontGoOutText::
	.DB $00
	.STRINGMAP pokemon, "OAK: Hey! Wait!"
	.DB $4f
	.STRINGMAP pokemon, "Don't go out!@"
	.DB $50
_PalletTownOakItsUnsafeText::
	.DB $00
	.STRINGMAP pokemon, "OAK: It's unsafe!"
	.DB $4f
	.STRINGMAP pokemon, "Wild #MON live"
	.DB $55
	.STRINGMAP pokemon, "in tall grass!"
	.DB $51
	.STRINGMAP pokemon, "You need your own"
	.DB $4f
	.STRINGMAP pokemon, "#MON for your"
	.DB $55
	.STRINGMAP pokemon, "protection."
	.DB $55
	.STRINGMAP pokemon, "I know!"
	.DB $51
	.STRINGMAP pokemon, "Here, come with"
	.DB $4f
	.STRINGMAP pokemon, "me!"
	.DB $57
_PalletTownGirlText::
	.DB $00
	.STRINGMAP pokemon, "I'm raising"
	.DB $4f
	.STRINGMAP pokemon, "#MON too!"
	.DB $51
	.STRINGMAP pokemon, "When they get"
	.DB $4f
	.STRINGMAP pokemon, "strong, they can"
	.DB $55
	.STRINGMAP pokemon, "protect me!"
	.DB $57
_PalletTownFisherText::
	.DB $00
	.STRINGMAP pokemon, "Technology is"
	.DB $4f
	.STRINGMAP pokemon, "incredible!"
	.DB $51
	.STRINGMAP pokemon, "You can now store"
	.DB $4f
	.STRINGMAP pokemon, "and recall items"
	.DB $55
	.STRINGMAP pokemon, "and #MON as"
	.DB $55
	.STRINGMAP pokemon, "data via PC!"
	.DB $57
_PalletTownOaksLabSignText::
	.DB $00
	.STRINGMAP pokemon, "OAK #MON"
	.DB $4f
	.STRINGMAP pokemon, "RESEARCH LAB"
	.DB $57
_PalletTownSignText::
	.DB $00
	.STRINGMAP pokemon, "PALLET TOWN"
	.DB $4f
	.STRINGMAP pokemon, "Shades of your"
	.DB $55
	.STRINGMAP pokemon, "journey await!"
	.DB $57
_PalletTownPlayersHouseSignText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER>'s house "
	.DB $57
_PalletTownRivalsHouseSignText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>'s house "
	.DB $57

; text/ViridianCity.asm
_ViridianCityYoungster1Text::
	.DB $00
	.STRINGMAP pokemon, "Those # BALLs"
	.DB $4f
	.STRINGMAP pokemon, "at your waist!"
	.DB $55
	.STRINGMAP pokemon, "You have #MON!"
	.DB $51
	.STRINGMAP pokemon, "It's great that"
	.DB $4f
	.STRINGMAP pokemon, "you can carry and"
	.DB $55
	.STRINGMAP pokemon, "use #MON any"
	.DB $55
	.STRINGMAP pokemon, "time, anywhere!"
	.DB $57
_ViridianCityGambler1GymAlwaysClosedText::
	.DB $00
	.STRINGMAP pokemon, "This #MON GYM"
	.DB $4f
	.STRINGMAP pokemon, "is always closed."
	.DB $51
	.STRINGMAP pokemon, "I wonder who the"
	.DB $4f
	.STRINGMAP pokemon, "LEADER is?"
	.DB $57
_ViridianCityGambler1GymLeaderReturnedText::
	.DB $00
	.STRINGMAP pokemon, "VIRIDIAN GYM's"
	.DB $4f
	.STRINGMAP pokemon, "LEADER returned!"
	.DB $57
_ViridianCityYoungster2YouWantToKnowAboutText::
	.DB $00
	.STRINGMAP pokemon, "You want to know"
	.DB $4f
	.STRINGMAP pokemon, "about the 2 kinds"
	.DB $55
	.STRINGMAP pokemon, "of caterpillar"
	.DB $55
	.STRINGMAP pokemon, "#MON?"
	.DB $57
ViridianCityYoungster2OkThenText::
	.DB $00
	.STRINGMAP pokemon, "Oh, OK then!"
	.DB $57
ViridianCityYoungster2CaterpieAndWeedleDescriptionText::
	.DB $00
	.STRINGMAP pokemon, "CATERPIE has no"
	.DB $4f
	.STRINGMAP pokemon, "poison, but"
	.DB $55
	.STRINGMAP pokemon, "WEEDLE does."
	.DB $51
	.STRINGMAP pokemon, "Watch out for its"
	.DB $4f
	.STRINGMAP pokemon, "POISON STING!"
	.DB $57
_ViridianCityGirlHasntHadHisCoffeeYetText::
	.DB $00
	.STRINGMAP pokemon, "Oh Grandpa! Don't"
	.DB $4f
	.STRINGMAP pokemon, "be so mean!"
	.DB $55
	.STRINGMAP pokemon, "He hasn't had his"
	.DB $55
	.STRINGMAP pokemon, "coffee yet."
	.DB $57
_ViridianCityGirlWhenIGoShopText::
	.DB $00
	.STRINGMAP pokemon, "When I go shop in"
	.DB $4f
	.STRINGMAP pokemon, "PEWTER CITY, I"
	.DB $55
	.STRINGMAP pokemon, "have to take the"
	.DB $55
	.STRINGMAP pokemon, "winding trail in"
	.DB $55
	.STRINGMAP pokemon, "VIRIDIAN FOREST."
	.DB $57
_ViridianCityOldManSleepyPrivatePropertyText::
	.DB $00
	.STRINGMAP pokemon, "You can't go"
	.DB $4f
	.STRINGMAP pokemon, "through here!"
	.DB $51
	.STRINGMAP pokemon, "This is private"
	.DB $4f
	.STRINGMAP pokemon, "property!"
	.DB $57
ViridianCityFisherYouCanHaveThisText::
	.DB $00
	.STRINGMAP pokemon, "Yawn!"
	.DB $4f
	.STRINGMAP pokemon, "I must have dozed"
	.DB $55
	.STRINGMAP pokemon, "off in the sun."
	.DB $51
	.STRINGMAP pokemon, "I had this dream"
	.DB $4f
	.STRINGMAP pokemon, "about a DROWZEE"
	.DB $55
	.STRINGMAP pokemon, "eating my dream."
	.DB $55
	.STRINGMAP pokemon, "What's this?"
	.DB $55
	.STRINGMAP pokemon, "Where did this TM"
	.DB $55
	.STRINGMAP pokemon, "come from?"
	.DB $51
	.STRINGMAP pokemon, "This is spooky!"
	.DB $4f
	.STRINGMAP pokemon, "Here, you can"
	.DB $55
	.STRINGMAP pokemon, "have this TM."
	.DB $58
_ViridianCityFisherReceivedTM42Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "TM42!@"
	.DB $50
_ViridianCityFisherTM42ExplanationText::
	.DB $00
	.STRINGMAP pokemon, "TM42 contains"
	.DB $4f
	.STRINGMAP pokemon, "DREAM EATER..."
	.DB $55
	.STRINGMAP pokemon, "...Snore..."
	.DB $57
_ViridianCityFisherTM42NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You have too much"
	.DB $4f
	.STRINGMAP pokemon, "stuff already."
	.DB $57
_ViridianCityOldManHadMyCoffeeNowText::
	.DB $00
	.STRINGMAP pokemon, "Ahh, I've had my"
	.DB $4f
	.STRINGMAP pokemon, "coffee now and I"
	.DB $55
	.STRINGMAP pokemon, "feel great!"
	.DB $51
	.STRINGMAP pokemon, "Sure you can go"
	.DB $4f
	.STRINGMAP pokemon, "through!"
	.DB $51
	.STRINGMAP pokemon, "Are you in a"
	.DB $4f
	.STRINGMAP pokemon, "hurry?"
	.DB $57
_ViridianCityOldManKnowHowToCatchPokemonText::
	.DB $00
	.STRINGMAP pokemon, "I see you're using"
	.DB $4f
	.STRINGMAP pokemon, "a #DEX."
	.DB $51
	.STRINGMAP pokemon, "When you catch a"
	.DB $4f
	.STRINGMAP pokemon, "#MON, #DEX"
	.DB $55
	.STRINGMAP pokemon, "is automatically"
	.DB $55
	.STRINGMAP pokemon, "updated."
	.DB $51
	.STRINGMAP pokemon, "What? Don't you"
	.DB $4f
	.STRINGMAP pokemon, "know how to catch"
	.DB $55
	.STRINGMAP pokemon, "#MON?"
	.DB $51
	.STRINGMAP pokemon, "I'll show you"
	.DB $4f
	.STRINGMAP pokemon, "how to then."
	.DB $57
_ViridianCityOldManTimeIsMoneyText::
	.DB $00
	.STRINGMAP pokemon, "Time is money..."
	.DB $4f
	.STRINGMAP pokemon, "Go along then."
	.DB $57
_ViridianCityOldManYouNeedToWeakenTheTargetText::
	.DB $00
	.STRINGMAP pokemon, "First, you need"
	.DB $4f
	.STRINGMAP pokemon, "to weaken the"
	.DB $55
	.STRINGMAP pokemon, "target #MON."
	.DB $57
_ViridianCitySignText::
	.DB $00
	.STRINGMAP pokemon, "VIRIDIAN CITY "
	.DB $4f
	.STRINGMAP pokemon, "The Eternally"
	.DB $55
	.STRINGMAP pokemon, "Green Paradise"
	.DB $57
_ViridianCityTrainerTips1Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Catch #MON"
	.DB $4f
	.STRINGMAP pokemon, "and expand your"
	.DB $55
	.STRINGMAP pokemon, "collection!"
	.DB $51
	.STRINGMAP pokemon, "The more you have,"
	.DB $4f
	.STRINGMAP pokemon, "the easier it is"
	.DB $55
	.STRINGMAP pokemon, "to fight!"
	.DB $57
_ViridianCityTrainerTips2Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "The battle moves"
	.DB $4f
	.STRINGMAP pokemon, "of #MON are"
	.DB $55
	.STRINGMAP pokemon, "limited by their"
	.DB $55
	.STRINGMAP pokemon, "POWER POINTs, PP."
	.DB $51
	.STRINGMAP pokemon, "To replenish PP,"
	.DB $4f
	.STRINGMAP pokemon, "rest your tired"
	.DB $55
	.STRINGMAP pokemon, "#MON at a"
	.DB $55
	.STRINGMAP pokemon, "#MON CENTER!"
	.DB $57
_ViridianCityGymSignText::
	.DB $00
	.STRINGMAP pokemon, "VIRIDIAN CITY"
	.DB $4f
	.STRINGMAP pokemon, "#MON GYM"
	.DB $57
_ViridianCityGymLockedText::
	.DB $00
	.STRINGMAP pokemon, "The GYM's doors"
	.DB $4f
	.STRINGMAP pokemon, "are locked..."
	.DB $57

; text/PewterCity.asm
_PewterCityCooltrainerFText::
	.DB $00
	.STRINGMAP pokemon, "It's rumored that"
	.DB $4f
	.STRINGMAP pokemon, "CLEFAIRYs came"
	.DB $55
	.STRINGMAP pokemon, "from the moon!"
	.DB $51
	.STRINGMAP pokemon, "They appeared "
	.DB $4f
	.STRINGMAP pokemon, "after MOON STONE"
	.DB $55
	.STRINGMAP pokemon, "fell on MT.MOON."
	.DB $57
_PewterCityCooltrainerMText::
	.DB $00
	.STRINGMAP pokemon, "There aren't many"
	.DB $4f
	.STRINGMAP pokemon, "serious #MON"
	.DB $55
	.STRINGMAP pokemon, "trainers here!"
	.DB $51
	.STRINGMAP pokemon, "They're all like"
	.DB $4f
	.STRINGMAP pokemon, "BUG CATCHERs,"
	.DB $55
	.STRINGMAP pokemon, "but PEWTER GYM's"
	.DB $55
	.STRINGMAP pokemon, "BROCK is totally"
	.DB $55
	.STRINGMAP pokemon, "into it!"
	.DB $57
_PewterCitySuperNerd1DidYouCheckOutMuseumText::
	.DB $00
	.STRINGMAP pokemon, "Did you check out"
	.DB $4f
	.STRINGMAP pokemon, "the MUSEUM?"
	.DB $57
_PewterCitySuperNerd1WerentThoseFossilsAmazingText::
	.DB $00
	.STRINGMAP pokemon, "Weren't those"
	.DB $4f
	.STRINGMAP pokemon, "fossils from MT."
	.DB $55
	.STRINGMAP pokemon, "MOON amazing?"
	.DB $57
_PewterCitySuperNerd1YouHaveToGoText::
	.DB $00
	.STRINGMAP pokemon, "Really?"
	.DB $4f
	.STRINGMAP pokemon, "You absolutely"
	.DB $55
	.STRINGMAP pokemon, "have to go!"
	.DB $57
_PewterCitySuperNerd1ItsRightHereText::
	.DB $00
	.STRINGMAP pokemon, "It's right here!"
	.DB $4f
	.STRINGMAP pokemon, "You have to pay"
	.DB $55
	.STRINGMAP pokemon, "to get in, but"
	.DB $55
	.STRINGMAP pokemon, "it's worth it!"
	.DB $55
	.STRINGMAP pokemon, "See you around!"
	.DB $57
_PewterCitySuperNerd2DoYouKnowWhatImDoingText::
	.DB $00
	.STRINGMAP pokemon, "Psssst!"
	.DB $4f
	.STRINGMAP pokemon, "Do you know what"
	.DB $55
	.STRINGMAP pokemon, "I'm doing?"
	.DB $57
_PewterCitySuperNerd2ThatsRightText::
	.DB $00
	.STRINGMAP pokemon, "That's right!"
	.DB $4f
	.STRINGMAP pokemon, "It's hard work!"
	.DB $57
_PewterCitySuperNerd2ImSprayingRepelText::
	.DB $00
	.STRINGMAP pokemon, "I'm spraying REPEL"
	.DB $4f
	.STRINGMAP pokemon, "to keep #MON"
	.DB $55
	.STRINGMAP pokemon, "out of my garden!"
	.DB $57
_PewterCityYoungsterYoureATrainerFollowMeText::
	.DB $00
	.STRINGMAP pokemon, "You're a trainer"
	.DB $4f
	.STRINGMAP pokemon, "right? BROCK's"
	.DB $55
	.STRINGMAP pokemon, "looking for new"
	.DB $55
	.STRINGMAP pokemon, "challengers!"
	.DB $55
	.STRINGMAP pokemon, "Follow me!"
	.DB $57
_PewterCityYoungsterGoTakeOnBrockText::
	.DB $00
	.STRINGMAP pokemon, "If you have the"
	.DB $4f
	.STRINGMAP pokemon, "right stuff, go"
	.DB $55
	.STRINGMAP pokemon, "take on BROCK!"
	.DB $57
_PewterCityTrainerTipsText::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Any #MON that"
	.DB $4f
	.STRINGMAP pokemon, "takes part in"
	.DB $55
	.STRINGMAP pokemon, "battle, however"
	.DB $55
	.STRINGMAP pokemon, "short, earns EXP!"
	.DB $57
_PewterCityPoliceNoticeSignText::
	.DB $00
	.STRINGMAP pokemon, "NOTICE!"
	.DB $51
	.STRINGMAP pokemon, "Thieves have been"
	.DB $4f
	.STRINGMAP pokemon, "stealing #MON"
	.DB $55
	.STRINGMAP pokemon, "fossils at MT."
	.DB $55
	.STRINGMAP pokemon, "MOON! Please call"
	.DB $55
	.STRINGMAP pokemon, "PEWTER POLICE"
	.DB $55
	.STRINGMAP pokemon, "with any info!"
	.DB $57
_PewterCityMuseumSignText::
	.DB $00
	.STRINGMAP pokemon, "PEWTER MUSEUM"
	.DB $4f
	.STRINGMAP pokemon, "OF SCIENCE"
	.DB $57
_PewterCityGymSignText::
	.DB $00
	.STRINGMAP pokemon, "PEWTER CITY"
	.DB $4f
	.STRINGMAP pokemon, "#MON GYM"
	.DB $55
	.STRINGMAP pokemon, "LEADER: BROCK"
	.DB $51
	.STRINGMAP pokemon, "The Rock Solid"
	.DB $4f
	.STRINGMAP pokemon, "#MON Trainer!"
	.DB $57
_PewterCitySignText::
	.DB $00
	.STRINGMAP pokemon, "PEWTER CITY"
	.DB $4f
	.STRINGMAP pokemon, "A Stone Gray"
	.DB $55
	.STRINGMAP pokemon, "City"
	.DB $57

; text/CeruleanCity.asm
_CeruleanCityRivalPreBattleText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Yo!"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "You're still"
	.DB $4f
	.STRINGMAP pokemon, "struggling along"
	.DB $55
	.STRINGMAP pokemon, "back here?"
	.DB $51
	.STRINGMAP pokemon, "I'm doing great!"
	.DB $4f
	.STRINGMAP pokemon, "I caught a bunch"
	.DB $55
	.STRINGMAP pokemon, "of strong and"
	.DB $55
	.STRINGMAP pokemon, "smart #MON!"
	.DB $51
	.STRINGMAP pokemon, "Here, let me see"
	.DB $4f
	.STRINGMAP pokemon, "what you caught,"
	.DB $55
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $57
_CeruleanCityRivalDefeatedText::
	.DB $00
	.STRINGMAP pokemon, "Hey!"
	.DB $4f
	.STRINGMAP pokemon, "Take it easy!"
	.DB $55
	.STRINGMAP pokemon, "You won already!"
	.DB $58
_CeruleanCityRivalVictoryText::
	.DB $00
	.STRINGMAP pokemon, "Heh!"
	.DB $4f
	.STRINGMAP pokemon, "You're no match"
	.DB $55
	.STRINGMAP pokemon, "for my genius!"
	.DB $58
_CeruleanCityRivalIWentToBillsText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Hey,"
	.DB $4f
	.STRINGMAP pokemon, "guess what?"
	.DB $51
	.STRINGMAP pokemon, "I went to BILL's"
	.DB $4f
	.STRINGMAP pokemon, "and got him to"
	.DB $55
	.STRINGMAP pokemon, "show me his rare"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $51
	.STRINGMAP pokemon, "That added a lot"
	.DB $4f
	.STRINGMAP pokemon, "of pages to my"
	.DB $55
	.STRINGMAP pokemon, "#DEX!"
	.DB $51
	.STRINGMAP pokemon, "After all, BILL's"
	.DB $4f
	.STRINGMAP pokemon, "world famous as a"
	.DB $55
	.STRINGMAP pokemon, "#MANIAC!"
	.DB $51
	.STRINGMAP pokemon, "He invented the"
	.DB $4f
	.STRINGMAP pokemon, "#MON Storage"
	.DB $55
	.STRINGMAP pokemon, "System on PC!"
	.DB $51
	.STRINGMAP pokemon, "Since you're using"
	.DB $4f
	.STRINGMAP pokemon, "his system, go"
	.DB $55
	.STRINGMAP pokemon, "thank him!"
	.DB $51
	.STRINGMAP pokemon, "Well, I better"
	.DB $4f
	.STRINGMAP pokemon, "get rolling!"
	.DB $55
	.STRINGMAP pokemon, "Smell ya later!"
	.DB $57
_CeruleanCityRocketText::
	.DB $00
	.STRINGMAP pokemon, "Hey! Stay out!"
	.DB $4f
	.STRINGMAP pokemon, "It's not your"
	.DB $55
	.STRINGMAP pokemon, "yard! Huh? Me?"
	.DB $51
	.STRINGMAP pokemon, "I'm an innocent"
	.DB $4f
	.STRINGMAP pokemon, "bystander! Don't"
	.DB $55
	.STRINGMAP pokemon, "you believe me?"
	.DB $57
_CeruleanCityRocketReceivedTM28Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> recovered"
	.DB $4f
	.STRINGMAP pokemon, "TM28!@"
	.DB $50
_CeruleanCityRocketIBetterGetMovingText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "I better get"
	.DB $4f
	.STRINGMAP pokemon, "moving! Bye!@"
	.DB $50
_CeruleanCityRocketTM28NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Make room for"
	.DB $4f
	.STRINGMAP pokemon, "this!"
	.DB $51
	.STRINGMAP pokemon, "I can't run until"
	.DB $4f
	.STRINGMAP pokemon, "I give it to you!"
	.DB $57
_CeruleanCityRocketIGiveUpText::
	.DB $00
	.STRINGMAP pokemon, "Stop!"
	.DB $4f
	.STRINGMAP pokemon, "I give up! I'll"
	.DB $55
	.STRINGMAP pokemon, "leave quietly!"
	.DB $58
_CeruleanCityRocketIllReturnTheTMText::
	.DB $00
	.STRINGMAP pokemon, "OK! I'll return"
	.DB $4f
	.STRINGMAP pokemon, "the TM I stole!"
	.DB $58
_CeruleanCityCooltrainerMText::
	.DB $00
	.STRINGMAP pokemon, "You're a trainer"
	.DB $4f
	.STRINGMAP pokemon, "too? Collecting,"
	.DB $55
	.STRINGMAP pokemon, "fighting, it's a"
	.DB $55
	.STRINGMAP pokemon, "tough life."
	.DB $57
_CeruleanCitySuperNerd1Text::
	.DB $00
	.STRINGMAP pokemon, "That bush in"
	.DB $4f
	.STRINGMAP pokemon, "front of the shop"
	.DB $55
	.STRINGMAP pokemon, "is in the way."
	.DB $51
	.STRINGMAP pokemon, "There might be a"
	.DB $4f
	.STRINGMAP pokemon, "way around."
	.DB $57
_CeruleanCitySuperNerd2Text::
	.DB $00
	.STRINGMAP pokemon, "You're making an"
	.DB $4f
	.STRINGMAP pokemon, "encyclopedia on"
	.DB $55
	.STRINGMAP pokemon, "#MON? That"
	.DB $55
	.STRINGMAP pokemon, "sounds amusing."
	.DB $57
_CeruleanCityGuardText::
	.DB $00
	.STRINGMAP pokemon, "The people here"
	.DB $4f
	.STRINGMAP pokemon, "were robbed."
	.DB $51
	.STRINGMAP pokemon, "It's obvious that"
	.DB $4f
	.STRINGMAP pokemon, "TEAM ROCKET is"
	.DB $55
	.STRINGMAP pokemon, "behind this most"
	.DB $55
	.STRINGMAP pokemon, "heinous crime!"
	.DB $51
	.STRINGMAP pokemon, "Even our POLICE"
	.DB $4f
	.STRINGMAP pokemon, "force has trouble"
	.DB $55
	.STRINGMAP pokemon, "with the ROCKETs!"
	.DB $57
_CeruleanCityCooltrainerF1SlowbroUseSonicboomText::
	.DB $00
	.STRINGMAP pokemon, "OK! SLOWBRO!"
	.DB $4f
	.STRINGMAP pokemon, "Use SONICBOOM!"
	.DB $55
	.STRINGMAP pokemon, "Come on, SLOWBRO"
	.DB $55
	.STRINGMAP pokemon, "pay attention!"
	.DB $57
_CeruleanCityCooltrainerF1SlowbroPunchText::
	.DB $00
	.STRINGMAP pokemon, "SLOWBRO punch!"
	.DB $4f
	.STRINGMAP pokemon, "No! You blew it"
	.DB $55
	.STRINGMAP pokemon, "again!"
	.DB $57
_CeruleanCityCooltrainerF1SlowbroWithdrawText::
	.DB $00
	.STRINGMAP pokemon, "SLOWBRO, WITHDRAW!"
	.DB $4f
	.STRINGMAP pokemon, "No! That's wrong!"
	.DB $51
	.STRINGMAP pokemon, "It's so hard to"
	.DB $4f
	.STRINGMAP pokemon, "control #MON!"
	.DB $51
	.STRINGMAP pokemon, "Your #MON's"
	.DB $4f
	.STRINGMAP pokemon, "obedience depends"
	.DB $55
	.STRINGMAP pokemon, "on your abilities"
	.DB $55
	.STRINGMAP pokemon, "as a trainer!"
	.DB $57
_CeruleanCitySlowbroTookASnoozeText::
	.DB $00
	.STRINGMAP pokemon, "SLOWBRO took a"
	.DB $4f
	.STRINGMAP pokemon, "snooze..."
	.DB $57
_CeruleanCitySlowbroIsLoafingAroundText::
	.DB $00
	.STRINGMAP pokemon, "SLOWBRO is"
	.DB $4f
	.STRINGMAP pokemon, "loafing around..."
	.DB $57
_CeruleanCitySlowbroTurnedAwayText::
	.DB $00
	.STRINGMAP pokemon, "SLOWBRO turned"
	.DB $4f
	.STRINGMAP pokemon, "away..."
	.DB $57
_CeruleanCitySlowbroIgnoredOrdersText::
	.DB $00
	.STRINGMAP pokemon, "SLOWBRO"
	.DB $4f
	.STRINGMAP pokemon, "ignored orders..."
	.DB $57
_CeruleanCityCooltrainerF2Text::
	.DB $00
	.STRINGMAP pokemon, "I want a bright"
	.DB $4f
	.STRINGMAP pokemon, "red BICYCLE!"
	.DB $51
	.STRINGMAP pokemon, "I'll keep it at"
	.DB $4f
	.STRINGMAP pokemon, "home, so it won't"
	.DB $55
	.STRINGMAP pokemon, "get dirty!"
	.DB $57
_CeruleanCitySuperNerd3Text::
	.DB $00
	.STRINGMAP pokemon, "This is CERULEAN"
	.DB $4f
	.STRINGMAP pokemon, "CAVE! Horribly"
	.DB $55
	.STRINGMAP pokemon, "strong #MON"
	.DB $55
	.STRINGMAP pokemon, "live in there!"
	.DB $51
	.STRINGMAP pokemon, "The #MON LEAGUE"
	.DB $4f
	.STRINGMAP pokemon, "champion is the"
	.DB $55
	.STRINGMAP pokemon, "only person who"
	.DB $55
	.STRINGMAP pokemon, "is allowed in!"
	.DB $57
_CeruleanCitySignText::
	.DB $00
	.STRINGMAP pokemon, "CERULEAN CITY"
	.DB $4f
	.STRINGMAP pokemon, "A Mysterious,"
	.DB $55
	.STRINGMAP pokemon, "Blue Aura"
	.DB $55
	.STRINGMAP pokemon, "Surrounds It"
	.DB $57
_CeruleanCityTrainerTipsText::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Pressing B Button"
	.DB $4f
	.STRINGMAP pokemon, "during evolution"
	.DB $55
	.STRINGMAP pokemon, "cancels the whole"
	.DB $55
	.STRINGMAP pokemon, "process."
	.DB $57
_CeruleanCityBikeShopSign::
	.DB $00
	.STRINGMAP pokemon, "Grass and caves"
	.DB $4f
	.STRINGMAP pokemon, "handled easily!"
	.DB $55
	.STRINGMAP pokemon, "BIKE SHOP"
	.DB $57
_CeruleanCityGymSign::
	.DB $00
	.STRINGMAP pokemon, "CERULEAN CITY"
	.DB $4f
	.STRINGMAP pokemon, "#MON GYM"
	.DB $55
	.STRINGMAP pokemon, "LEADER: MISTY"
	.DB $51
	.STRINGMAP pokemon, "The Tomboyish"
	.DB $4f
	.STRINGMAP pokemon, "Mermaid!"
	.DB $57

; text/LavenderTown.asm
_LavenderTownLittleGirlDoYouBelieveInGhostsText::
	.DB $00
	.STRINGMAP pokemon, "Do you believe in"
	.DB $4f
	.STRINGMAP pokemon, "GHOSTs?"
	.DB $57
_LavenderTownLittleGirlSoThereAreBelieversText::
	.DB $00
	.STRINGMAP pokemon, "Really? So there"
	.DB $4f
	.STRINGMAP pokemon, "are believers..."
	.DB $57
_LavenderTownLittleGirlHaHaGuessNotText::
	.DB $00
	.STRINGMAP pokemon, "Hahaha, I guess"
	.DB $4f
	.STRINGMAP pokemon, "not."
	.DB $51
	.STRINGMAP pokemon, "That white hand"
	.DB $4f
	.STRINGMAP pokemon, "on your shoulder,"
	.DB $55
	.STRINGMAP pokemon, "it's not real."
	.DB $57
_LavenderTownCooltrainerMText::
	.DB $00
	.STRINGMAP pokemon, "This town is known"
	.DB $4f
	.STRINGMAP pokemon, "as the grave site"
	.DB $55
	.STRINGMAP pokemon, "of #MON."
	.DB $51
	.STRINGMAP pokemon, "Memorial services"
	.DB $4f
	.STRINGMAP pokemon, "are held in"
	.DB $55
	.STRINGMAP pokemon, "#MON TOWER."
	.DB $57
_LavenderTownSuperNerdText::
	.DB $00
	.STRINGMAP pokemon, "GHOSTs appeared"
	.DB $4f
	.STRINGMAP pokemon, "in #MON TOWER."
	.DB $51
	.STRINGMAP pokemon, "I think they're"
	.DB $4f
	.STRINGMAP pokemon, "the spirits of"
	.DB $55
	.STRINGMAP pokemon, "#MON that the"
	.DB $55
	.STRINGMAP pokemon, "ROCKETs killed."
	.DB $57
_LavenderTownSignText::
	.DB $00
	.STRINGMAP pokemon, "LAVENDER TOWN"
	.DB $4f
	.STRINGMAP pokemon, "The Noble Purple"
	.DB $55
	.STRINGMAP pokemon, "Town"
	.DB $57
_LavenderTownSilphScopeSignText::
	.DB $00
	.STRINGMAP pokemon, "New SILPH SCOPE!"
	.DB $51
	.STRINGMAP pokemon, "Make the Invisible"
	.DB $4f
	.STRINGMAP pokemon, "Plain to See!"
	.DB $51
	.STRINGMAP pokemon, "SILPH CO."
	.DB $57
_LavenderTownPokemonHouseSignText::
	.DB $00
	.STRINGMAP pokemon, "LAVENDER VOLUNTEER"
	.DB $4f
	.STRINGMAP pokemon, "#MON HOUSE"
	.DB $57
_LavenderTownPokemonTowerSignText::
	.DB $00
	.STRINGMAP pokemon, "May the Souls of"
	.DB $4f
	.STRINGMAP pokemon, "#MON Rest Easy"
	.DB $55
	.STRINGMAP pokemon, "#MON TOWER"
	.DB $57

; text/VermilionCity.asm
_VermilionCityBeautyText::
	.DB $00
	.STRINGMAP pokemon, "We're careful"
	.DB $4f
	.STRINGMAP pokemon, "about pollution!"
	.DB $51
	.STRINGMAP pokemon, "We've heard GRIMER"
	.DB $4f
	.STRINGMAP pokemon, "multiplies in"
	.DB $55
	.STRINGMAP pokemon, "toxic sludge!"
	.DB $57
_VermilionCityGambler1DidYouSeeText::
	.DB $00
	.STRINGMAP pokemon, "Did you see S.S."
	.DB $4f
	.STRINGMAP pokemon, "ANNE moored in"
	.DB $55
	.STRINGMAP pokemon, "the harbor?"
	.DB $57
_VermilionCityGambler1SSAnneDepartedText::
	.DB $00
	.STRINGMAP pokemon, "So, S.S.ANNE has"
	.DB $4f
	.STRINGMAP pokemon, "departed!"
	.DB $51
	.STRINGMAP pokemon, "She'll be back in"
	.DB $4f
	.STRINGMAP pokemon, "about a year."
	.DB $57
_VermilionCitySailor1WelcomeToSSAnneText::
	.DB $00
	.STRINGMAP pokemon, "Welcome to S.S."
	.DB $4f
	.STRINGMAP pokemon, "ANNE!"
	.DB $57
_VermilionCitySailor1DoYouHaveATicketText::
	.DB $00
	.STRINGMAP pokemon, "Welcome to S.S."
	.DB $4f
	.STRINGMAP pokemon, "ANNE!"
	.DB $51
	.STRINGMAP pokemon, "Excuse me, do you"
	.DB $4f
	.STRINGMAP pokemon, "have a ticket?"
	.DB $58
_VermilionCitySailor1FlashedTicketText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> flashed"
	.DB $4f
	.STRINGMAP pokemon, "the S.S.TICKET!"
	.DB $51
	.STRINGMAP pokemon, "Great! Welcome to"
	.DB $4f
	.STRINGMAP pokemon, "S.S.ANNE!"
	.DB $57
_VermilionCitySailor1YouNeedATicketText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> doesn't"
	.DB $4f
	.STRINGMAP pokemon, "have the needed"
	.DB $55
	.STRINGMAP pokemon, "S.S.TICKET."
	.DB $51
	.STRINGMAP pokemon, "Sorry!"
	.DB $51
	.STRINGMAP pokemon, "You need a ticket"
	.DB $4f
	.STRINGMAP pokemon, "to get aboard."
	.DB $57
_VermilionCitySailor1ShipSetSailText::
	.DB $00
	.STRINGMAP pokemon, "The ship set sail."
	.DB $57
_VermilionCityGambler2Text::
	.DB $00
	.STRINGMAP pokemon, "I'm putting up a"
	.DB $4f
	.STRINGMAP pokemon, "building on this"
	.DB $55
	.STRINGMAP pokemon, "plot of land."
	.DB $51
	.STRINGMAP pokemon, "My #MON is"
	.DB $4f
	.STRINGMAP pokemon, "tamping the land."
	.DB $57
_VermilionCityMachopText::
	.DB $00
	.STRINGMAP pokemon, "MACHOP: Guoh!"
	.DB $4f
	.STRINGMAP pokemon, "Gogogoh!@"
	.DB $50
_VermilionCityMachopStompingTheLandFlatText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "A MACHOP is"
	.DB $4f
	.STRINGMAP pokemon, "stomping the land"
	.DB $55
	.STRINGMAP pokemon, "flat."
	.DB $57
_VermilionCitySailor2Text::
	.DB $00
	.STRINGMAP pokemon, "S.S.ANNE is a"
	.DB $4f
	.STRINGMAP pokemon, "famous luxury"
	.DB $55
	.STRINGMAP pokemon, "cruise ship."
	.DB $51
	.STRINGMAP pokemon, "We visit VERMILION"
	.DB $4f
	.STRINGMAP pokemon, "once a year."
	.DB $57
_VermilionCitySignText::
	.DB $00
	.STRINGMAP pokemon, "VERMILION CITY"
	.DB $4f
	.STRINGMAP pokemon, "The Port of"
	.DB $55
	.STRINGMAP pokemon, "Exquisite Sunsets"
	.DB $57
_VermilionCityNoticeSignText::
	.DB $00
	.STRINGMAP pokemon, "NOTICE!"
	.DB $51
	.STRINGMAP pokemon, "ROUTE 12 may be"
	.DB $4f
	.STRINGMAP pokemon, "blocked off by a"
	.DB $55
	.STRINGMAP pokemon, "sleeping #MON."
	.DB $51
	.STRINGMAP pokemon, "Detour through"
	.DB $4f
	.STRINGMAP pokemon, "ROCK TUNNEL to"
	.DB $55
	.STRINGMAP pokemon, "LAVENDER TOWN."
	.DB $51
	.STRINGMAP pokemon, "VERMILION POLICE"
	.DB $57
_VermilionCityPokemonFanClubSignText::
	.DB $00
	.STRINGMAP pokemon, "#MON FAN CLUB"
	.DB $4f
	.STRINGMAP pokemon, "All #MON fans"
	.DB $55
	.STRINGMAP pokemon, "welcome!"
	.DB $57
_VermilionCityGymSignText::
	.DB $00
	.STRINGMAP pokemon, "VERMILION CITY"
	.DB $4f
	.STRINGMAP pokemon, "#MON GYM"
	.DB $55
	.STRINGMAP pokemon, "LEADER: LT.SURGE"
	.DB $51
	.STRINGMAP pokemon, "The Lightning "
	.DB $4f
	.STRINGMAP pokemon, "American!"
	.DB $57
_VermilionCityHarborSignText::
	.DB $00
	.STRINGMAP pokemon, "VERMILION HARBOR"
	.DB $57

; text/CeladonCity.asm
_CeladonCityLittleGirlText::
	.DB $00
	.STRINGMAP pokemon, "I got my KOFFING"
	.DB $4f
	.STRINGMAP pokemon, "in CINNABAR!"
	.DB $51
	.STRINGMAP pokemon, "It's nice, but it"
	.DB $4f
	.STRINGMAP pokemon, "breathes poison"
	.DB $55
	.STRINGMAP pokemon, "when it's angry!"
	.DB $57
_CeladonCityGramps1Text::
	.DB $00
	.STRINGMAP pokemon, "Heheh! This GYM"
	.DB $4f
	.STRINGMAP pokemon, "is great! It's"
	.DB $55
	.STRINGMAP pokemon, "full of women!"
	.DB $57
_CeladonCityGirlText::
	.DB $00
	.STRINGMAP pokemon, "The GAME CORNER"
	.DB $4f
	.STRINGMAP pokemon, "is bad for our"
	.DB $55
	.STRINGMAP pokemon, "city's image!"
	.DB $57
_CeladonCityGramps2Text::
	.DB $00
	.STRINGMAP pokemon, "Moan! I blew it"
	.DB $4f
	.STRINGMAP pokemon, "all at the slots!"
	.DB $51
	.STRINGMAP pokemon, "I knew I should"
	.DB $4f
	.STRINGMAP pokemon, "have cashed in my"
	.DB $55
	.STRINGMAP pokemon, "coins for prizes!"
	.DB $57
_CeladonCityGramps3Text::
	.DB $00
	.STRINGMAP pokemon, "Hello, there!"
	.DB $51
	.STRINGMAP pokemon, "I've seen you,"
	.DB $4f
	.STRINGMAP pokemon, "but I never had a"
	.DB $55
	.STRINGMAP pokemon, "chance to talk!"
	.DB $51
	.STRINGMAP pokemon, "Here's a gift for"
	.DB $4f
	.STRINGMAP pokemon, "dropping by!"
	.DB $58
_CeladonCityGramps3ReceivedTM41Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_CeladonCityGramps3TM41ExplanationText::
	.DB $00
	.STRINGMAP pokemon, "TM41 teaches"
	.DB $4f
	.STRINGMAP pokemon, "SOFTBOILED!"
	.DB $51
	.STRINGMAP pokemon, "Only one #MON"
	.DB $4f
	.STRINGMAP pokemon, "can use it!"
	.DB $51
	.STRINGMAP pokemon, "That #MON is"
	.DB $4f
	.STRINGMAP pokemon, "CHANSEY!"
	.DB $57
_CeladonCityGramps3TM41NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Oh, your pack is"
	.DB $4f
	.STRINGMAP pokemon, "full of items!"
	.DB $57
_CeladonCityFisherText::
	.DB $00
	.STRINGMAP pokemon, "This is my trusted"
	.DB $4f
	.STRINGMAP pokemon, "pal, POLIWRATH!"
	.DB $51
	.STRINGMAP pokemon, "It evolved from"
	.DB $4f
	.STRINGMAP pokemon, "POLIWHIRL when I"
	.DB $55
	.STRINGMAP pokemon, "used WATER STONE!"
	.DB $57
_CeladonCityPoliwrathText::
	.DB $00
	.STRINGMAP pokemon, "POLIWRATH: Ribi"
	.DB $4f
	.STRINGMAP pokemon, "ribit!@"
	.DB $50
_CeladonCityRocket1Text::
	.DB $00
	.STRINGMAP pokemon, "What are you"
	.DB $4f
	.STRINGMAP pokemon, "staring at?"
	.DB $57
_CeladonCityRocket2Text::
	.DB $00
	.STRINGMAP pokemon, "Keep out of TEAM"
	.DB $4f
	.STRINGMAP pokemon, "ROCKET's way!"
	.DB $57
_CeladonCityTrainerTips1Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "X ACCURACY boosts"
	.DB $4f
	.STRINGMAP pokemon, "the accuracy of"
	.DB $55
	.STRINGMAP pokemon, "techniques!"
	.DB $51
	.STRINGMAP pokemon, "DIRE HIT jacks up"
	.DB $4f
	.STRINGMAP pokemon, "the likelihood of"
	.DB $55
	.STRINGMAP pokemon, "critical hits!"
	.DB $51
	.STRINGMAP pokemon, "Get your items at"
	.DB $4f
	.STRINGMAP pokemon, "CELADON DEPT."
	.DB $55
	.STRINGMAP pokemon, "STORE!"
	.DB $57
_CeladonCitySignText::
	.DB $00
	.STRINGMAP pokemon, "CELADON CITY"
	.DB $4f
	.STRINGMAP pokemon, "The City of"
	.DB $55
	.STRINGMAP pokemon, "Rainbow Dreams"
	.DB $57
_CeladonCityGymSignText::
	.DB $00
	.STRINGMAP pokemon, "CELADON CITY"
	.DB $4f
	.STRINGMAP pokemon, "#MON GYM"
	.DB $55
	.STRINGMAP pokemon, "LEADER: ERIKA"
	.DB $51
	.STRINGMAP pokemon, "The Nature Loving"
	.DB $4f
	.STRINGMAP pokemon, "Princess!"
	.DB $57
_CeladonCityMansionSignText::
	.DB $00
	.STRINGMAP pokemon, "CELADON MANSION"
	.DB $57
_CeladonCityDeptStoreSignText::
	.DB $00
	.STRINGMAP pokemon, "Find what you"
	.DB $4f
	.STRINGMAP pokemon, "need at CELADON"
	.DB $55
	.STRINGMAP pokemon, "DEPT. STORE!"
	.DB $57
_CeladonCityTrainerTips2Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "GUARD SPEC."
	.DB $4f
	.STRINGMAP pokemon, "protects #MON"
	.DB $55
	.STRINGMAP pokemon, "against SPECIAL"
	.DB $55
	.STRINGMAP pokemon, "attacks such as"
	.DB $55
	.STRINGMAP pokemon, "fire and water!"
	.DB $51
	.STRINGMAP pokemon, "Get your items at"
	.DB $4f
	.STRINGMAP pokemon, "CELADON DEPT."
	.DB $55
	.STRINGMAP pokemon, "STORE!"
	.DB $57
_CeladonCityPrizeExchangeSignText::
	.DB $00
	.STRINGMAP pokemon, "Coins exchanged"
	.DB $4f
	.STRINGMAP pokemon, "for prizes!"
	.DB $55
	.STRINGMAP pokemon, "PRIZE EXCHANGE"
	.DB $57
_CeladonCityGameCornerSignText::
	.DB $00
	.STRINGMAP pokemon, "ROCKET GAME CORNER"
	.DB $4f
	.STRINGMAP pokemon, "The playground"
	.DB $55
	.STRINGMAP pokemon, "for grown-ups!"
	.DB $57

; text/FuchsiaCity.asm
_FuchsiaCityYoungster1Text::
	.DB $00
	.STRINGMAP pokemon, "Did you try the"
	.DB $4f
	.STRINGMAP pokemon, "SAFARI GAME? Some"
	.DB $55
	.STRINGMAP pokemon, "#MON can only"
	.DB $55
	.STRINGMAP pokemon, "be caught there."
	.DB $57
_FuchsiaCityGamblerText::
	.DB $00
	.STRINGMAP pokemon, "SAFARI ZONE has a"
	.DB $4f
	.STRINGMAP pokemon, "zoo in front of"
	.DB $55
	.STRINGMAP pokemon, "the entrance."
	.DB $51
	.STRINGMAP pokemon, "Out back is the"
	.DB $4f
	.STRINGMAP pokemon, "SAFARI GAME for"
	.DB $55
	.STRINGMAP pokemon, "catching #MON."
	.DB $57
_FuchsiaCityErikText::
	.DB $00
	.STRINGMAP pokemon, "ERIK: Where's"
	.DB $4f
	.STRINGMAP pokemon, "SARA? I said I'd"
	.DB $55
	.STRINGMAP pokemon, "meet her here."
	.DB $57
_FuchsiaCityYoungster2Text::
	.DB $00
	.STRINGMAP pokemon, "That item ball in"
	.DB $4f
	.STRINGMAP pokemon, "there is really a"
	.DB $55
	.STRINGMAP pokemon, "#MON."
	.DB $57
_FuchsiaCityPokemonText::
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_FuchsiaCitySignText::
	.DB $00
	.STRINGMAP pokemon, "FUCHSIA CITY"
	.DB $4f
	.STRINGMAP pokemon, "Behold! It's"
	.DB $55
	.STRINGMAP pokemon, "Passion Pink!"
	.DB $57
_FuchsiaCitySafariGameSignText::
	.DB $00
	.STRINGMAP pokemon, "SAFARI GAME"
	.DB $4f
	.STRINGMAP pokemon, "#MON-U-CATCH!"
	.DB $57
_FuchsiaCityWardensHomeSignText::
	.DB $00
	.STRINGMAP pokemon, "SAFARI ZONE"
	.DB $4f
	.STRINGMAP pokemon, "WARDEN's HOME"
	.DB $57
_FuchsiaCitySafariZoneSignText::
	.DB $00
	.STRINGMAP pokemon, "#MON PARADISE"
	.DB $4f
	.STRINGMAP pokemon, "SAFARI ZONE"
	.DB $57
_FuchsiaCityGymSignText::
	.DB $00
	.STRINGMAP pokemon, "FUCHSIA CITY"
	.DB $4f
	.STRINGMAP pokemon, "#MON GYM"
	.DB $55
	.STRINGMAP pokemon, "LEADER: KOGA"
	.DB $51
	.STRINGMAP pokemon, "The Poisonous"
	.DB $4f
	.STRINGMAP pokemon, "Ninja Master"
	.DB $57
_FuchsiaCityChanseySignText::
	.DB $00
	.STRINGMAP pokemon, "Name: CHANSEY"
	.DB $51
	.STRINGMAP pokemon, "Catching one is"
	.DB $4f
	.STRINGMAP pokemon, "all up to chance."
	.DB $58
_FuchsiaCityVoltorbSignText::
	.DB $00
	.STRINGMAP pokemon, "Name: VOLTORB"
	.DB $51
	.STRINGMAP pokemon, "The very image of"
	.DB $4f
	.STRINGMAP pokemon, "a # BALL."
	.DB $58
_FuchsiaCityKangaskhanSignText::
	.DB $00
	.STRINGMAP pokemon, "Name: KANGASKHAN"
	.DB $51
	.STRINGMAP pokemon, "A maternal #MON"
	.DB $4f
	.STRINGMAP pokemon, "that raises its"
	.DB $55
	.STRINGMAP pokemon, "young in a pouch"
	.DB $55
	.STRINGMAP pokemon, "on its belly."
	.DB $58
_FuchsiaCitySlowpokeSignText::
	.DB $00
	.STRINGMAP pokemon, "Name: SLOWPOKE"
	.DB $51
	.STRINGMAP pokemon, "Friendly and very"
	.DB $4f
	.STRINGMAP pokemon, "slow moving."
	.DB $58
_FuchsiaCityLaprasSignText::
	.DB $00
	.STRINGMAP pokemon, "Name: LAPRAS"
	.DB $51
	.STRINGMAP pokemon, "A.K.A. the king"
	.DB $4f
	.STRINGMAP pokemon, "of the seas."
	.DB $58
_FuchsiaCityFossilSignOmanyteText::
	.DB $00
	.STRINGMAP pokemon, "Name: OMANYTE"
	.DB $51
	.STRINGMAP pokemon, "A #MON that"
	.DB $4f
	.STRINGMAP pokemon, "was resurrected"
	.DB $55
	.STRINGMAP pokemon, "from a fossil."
	.DB $58
_FuchsiaCityFossilSignKabutoText::
	.DB $00
	.STRINGMAP pokemon, "Name: KABUTO"
	.DB $51
	.STRINGMAP pokemon, "A #MON that"
	.DB $4f
	.STRINGMAP pokemon, "was resurrected"
	.DB $55
	.STRINGMAP pokemon, "from a fossil."
	.DB $58
_FuchsiaCityFossilSignUndeterminedText::
	.DB $00
	.STRINGMAP pokemon, "..."
	.DB $57

; text/CinnabarIsland.asm
_CinnabarIslandDoorIsLockedText::
	.DB $00
	.STRINGMAP pokemon, "The door is"
	.DB $4f
	.STRINGMAP pokemon, "locked..."
	.DB $57
_CinnabarIslandGirlText::
	.DB $00
	.STRINGMAP pokemon, "CINNABAR GYM's"
	.DB $4f
	.STRINGMAP pokemon, "BLAINE is an odd"
	.DB $55
	.STRINGMAP pokemon, "man who has lived"
	.DB $55
	.STRINGMAP pokemon, "here for decades."
	.DB $57
_CinnabarIslandGamblerText::
	.DB $00
	.STRINGMAP pokemon, "Scientists conduct"
	.DB $4f
	.STRINGMAP pokemon, "experiments in"
	.DB $55
	.STRINGMAP pokemon, "the burned out"
	.DB $55
	.STRINGMAP pokemon, "building."
	.DB $57
_CinnabarIslandSignText::
	.DB $00
	.STRINGMAP pokemon, "CINNABAR ISLAND"
	.DB $4f
	.STRINGMAP pokemon, "The Fiery Town of"
	.DB $55
	.STRINGMAP pokemon, "Burning Desire"
	.DB $57
_CinnabarIslandPokemonLabSignText::
	.DB $00
	.STRINGMAP pokemon, "#MON LAB"
	.DB $57
_CinnabarIslandGymSignText::
	.DB $00
	.STRINGMAP pokemon, "CINNABAR ISLAND"
	.DB $4f
	.STRINGMAP pokemon, "#MON GYM"
	.DB $55
	.STRINGMAP pokemon, "LEADER: BLAINE"
	.DB $51
	.STRINGMAP pokemon, "The Hot-Headed"
	.DB $4f
	.STRINGMAP pokemon, "Quiz Master!"
	.DB $57

; text/SaffronCity.asm
_SaffronCityRocket1Text::
	.DB $00
	.STRINGMAP pokemon, "What do you want?"
	.DB $4f
	.STRINGMAP pokemon, "Get lost!"
	.DB $57
_SaffronCityRocket2Text::
	.DB $00
	.STRINGMAP pokemon, "BOSS said he'll"
	.DB $4f
	.STRINGMAP pokemon, "take this town!"
	.DB $57
_SaffronCityRocket3Text::
	.DB $00
	.STRINGMAP pokemon, "Get out of the"
	.DB $4f
	.STRINGMAP pokemon, "way!"
	.DB $57
_SaffronCityRocket4Text::
	.DB $00
	.STRINGMAP pokemon, "SAFFRON belongs"
	.DB $4f
	.STRINGMAP pokemon, "to TEAM ROCKET!"
	.DB $57
_SaffronCityRocket5Text::
	.DB $00
	.STRINGMAP pokemon, "Being evil makes"
	.DB $4f
	.STRINGMAP pokemon, "me feel so alive!"
	.DB $57
_SaffronCityRocket6Text::
	.DB $00
	.STRINGMAP pokemon, "Ow! Watch where"
	.DB $4f
	.STRINGMAP pokemon, "you're walking!"
	.DB $57
_SaffronCityRocket7Text::
	.DB $00
	.STRINGMAP pokemon, "With SILPH under"
	.DB $4f
	.STRINGMAP pokemon, "control, we can"
	.DB $55
	.STRINGMAP pokemon, "exploit #MON"
	.DB $55
	.STRINGMAP pokemon, "around the world!"
	.DB $57
_SaffronCityScientistText::
	.DB $00
	.STRINGMAP pokemon, "You beat TEAM"
	.DB $4f
	.STRINGMAP pokemon, "ROCKET all alone?"
	.DB $55
	.STRINGMAP pokemon, "That's amazing!"
	.DB $57
_SaffronCitySilphWorkerMText::
	.DB $00
	.STRINGMAP pokemon, "Yeah! TEAM ROCKET"
	.DB $4f
	.STRINGMAP pokemon, "is gone!"
	.DB $55
	.STRINGMAP pokemon, "It's safe to go"
	.DB $55
	.STRINGMAP pokemon, "out again!"
	.DB $57
_SaffronCitySilphWorkerFText::
	.DB $00
	.STRINGMAP pokemon, "People should be"
	.DB $4f
	.STRINGMAP pokemon, "flocking back to"
	.DB $55
	.STRINGMAP pokemon, "SAFFRON now."
	.DB $57
_SaffronCityGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "I flew here on my"
	.DB $4f
	.STRINGMAP pokemon, "PIDGEOT when I"
	.DB $55
	.STRINGMAP pokemon, "read about SILPH."
	.DB $51
	.STRINGMAP pokemon, "It's already over?"
	.DB $4f
	.STRINGMAP pokemon, "I missed the"
	.DB $55
	.STRINGMAP pokemon, "media action."
	.DB $57
_SaffronCityPidgeotText::
	.DB $00
	.STRINGMAP pokemon, "PIDGEOT: Bi bibii!@"
	.DB $50
_SaffronCityRockerText::
	.DB $00
	.STRINGMAP pokemon, "I saw ROCKET"
	.DB $4f
	.STRINGMAP pokemon, "BOSS escaping"
	.DB $55
	.STRINGMAP pokemon, "SILPH's building."
	.DB $57
_SaffronCityRocket8Text::
	.DB $00
	.STRINGMAP pokemon, "I'm a security"
	.DB $4f
	.STRINGMAP pokemon, "guard."
	.DB $51
	.STRINGMAP pokemon, "Suspicious kids I"
	.DB $4f
	.STRINGMAP pokemon, "don't allow in!"
	.DB $57
_SaffronCityRocket9Text::
	.DB $00
	.STRINGMAP pokemon, "..."
	.DB $4f
	.STRINGMAP pokemon, "Snore..."
	.DB $51
	.STRINGMAP pokemon, "Hah! He's taking"
	.DB $4f
	.STRINGMAP pokemon, "a snooze!"
	.DB $57
_SaffronCitySignText::
	.DB $00
	.STRINGMAP pokemon, "SAFFRON CITY"
	.DB $4f
	.STRINGMAP pokemon, "Shining, Golden"
	.DB $55
	.STRINGMAP pokemon, "Land of Commerce"
	.DB $57
_SaffronCityFightingDojoSignText::
	.DB $00
	.STRINGMAP pokemon, "FIGHTING DOJO"
	.DB $57
_SaffronCityGymSignText::
	.DB $00
	.STRINGMAP pokemon, "SAFFRON CITY"
	.DB $4f
	.STRINGMAP pokemon, "#MON GYM"
	.DB $55
	.STRINGMAP pokemon, "LEADER: SABRINA"
	.DB $51
	.STRINGMAP pokemon, "The Master of"
	.DB $4f
	.STRINGMAP pokemon, "Psychic #MON!"
	.DB $57
_SaffronCityTrainerTips1Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "FULL HEAL cures"
	.DB $4f
	.STRINGMAP pokemon, "all ailments like"
	.DB $55
	.STRINGMAP pokemon, "sleep and burns."
	.DB $51
	.STRINGMAP pokemon, "It costs a bit"
	.DB $4f
	.STRINGMAP pokemon, "more, but it's"
	.DB $55
	.STRINGMAP pokemon, "more convenient."
	.DB $57
_SaffronCityTrainerTips2Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "New GREAT BALL"
	.DB $4f
	.STRINGMAP pokemon, "offers improved"
	.DB $55
	.STRINGMAP pokemon, "capture rates."
	.DB $51
	.STRINGMAP pokemon, "Try it on those"
	.DB $4f
	.STRINGMAP pokemon, "hard-to-catch"
	.DB $55
	.STRINGMAP pokemon, "#MON."
	.DB $57
_SaffronCitySilphCoSignText::
	.DB $00
	.STRINGMAP pokemon, "SILPH CO."
	.DB $4f
	.STRINGMAP pokemon, "OFFICE BUILDING"
	.DB $57
_SaffronCityMrPsychicsHouseSignText::
	.DB $00
	.STRINGMAP pokemon, "MR.PSYCHIC's"
	.DB $4f
	.STRINGMAP pokemon, "HOUSE"
	.DB $57
_SaffronCitySilphCoLatestProductSignText::
	.DB $00
	.STRINGMAP pokemon, "SILPH's latest"
	.DB $4f
	.STRINGMAP pokemon, "product!"
	.DB $51
	.STRINGMAP pokemon, "Release to be"
	.DB $4f
	.STRINGMAP pokemon, "determined..."
	.DB $57

; data/text/text_6.asm
_ItemUseBallText00::
	.DB $00
	.STRINGMAP pokemon, "It dodged the"
	.DB $4f
	.STRINGMAP pokemon, "thrown BALL!"
	.DB $51
	.STRINGMAP pokemon, "This #MON"
	.DB $4f
	.STRINGMAP pokemon, "can't be caught!"
	.DB $58
_ItemUseBallText01::
	.DB $00
	.STRINGMAP pokemon, "You missed the"
	.DB $4f
	.STRINGMAP pokemon, "#MON!"
	.DB $58
_ItemUseBallText02::
	.DB $00
	.STRINGMAP pokemon, "Darn! The #MON"
	.DB $4f
	.STRINGMAP pokemon, "broke free!"
	.DB $58
_ItemUseBallText03::
	.DB $00
	.STRINGMAP pokemon, "Aww! It appeared"
	.DB $4f
	.STRINGMAP pokemon, "to be caught! "
	.DB $58
_ItemUseBallText04::
	.DB $00
	.STRINGMAP pokemon, "Shoot! It was so"
	.DB $4f
	.STRINGMAP pokemon, "close too!"
	.DB $58
_ItemUseBallText05::
	.DB $00
	.STRINGMAP pokemon, "All right!"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.STRINGMAP pokemon, " was"
	.DB $55
	.STRINGMAP pokemon, "caught!@"
	.DB $50
_ItemUseBallText07::
	.DB $01
	.DW wBoxMonNicks
	.DB $00
	.STRINGMAP pokemon, " was"
	.DB $4f
	.STRINGMAP pokemon, "transferred to"
	.DB $55
	.STRINGMAP pokemon, "BILL's PC!"
	.DB $58
_ItemUseBallText08::
	.DB $01
	.DW wBoxMonNicks
	.DB $00
	.STRINGMAP pokemon, " was"
	.DB $4f
	.STRINGMAP pokemon, "transferred to"
	.DB $55
	.STRINGMAP pokemon, "someone's PC!"
	.DB $58
_ItemUseBallText06::
	.DB $00
	.STRINGMAP pokemon, "New #DEX data"
	.DB $4f
	.STRINGMAP pokemon, "will be added for"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_SurfingGotOnText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> got on"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $58
_SurfingNoPlaceToGetOffText::
	.DB $00
	.STRINGMAP pokemon, "There's no place"
	.DB $4f
	.STRINGMAP pokemon, "to get off!"
	.DB $58
_VitaminStatRoseText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "'s"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, " rose."
	.DB $58
_VitaminNoEffectText::
	.DB $00
	.STRINGMAP pokemon, "It won't have any"
	.DB $4f
	.STRINGMAP pokemon, "effect."
	.DB $58
_ThrewBaitText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> threw"
	.DB $4f
	.STRINGMAP pokemon, "some BAIT."
	.DB $57
_ThrewRockText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> threw a"
	.DB $4f
	.STRINGMAP pokemon, "ROCK."
	.DB $57
_PlayedFluteNoEffectText::
	.DB $00
	.STRINGMAP pokemon, "Played the #"
	.DB $4f
	.STRINGMAP pokemon, "FLUTE."
	.DB $51
	.STRINGMAP pokemon, "Now, that's a"
	.DB $4f
	.STRINGMAP pokemon, "catchy tune!"
	.DB $58
_FluteWokeUpText::
	.DB $00
	.STRINGMAP pokemon, "All sleeping"
	.DB $4f
	.STRINGMAP pokemon, "#MON woke up."
	.DB $58
_PlayedFluteHadEffectText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> played the"
	.DB $4f
	.STRINGMAP pokemon, "# FLUTE.@"
	.DB $50
_CoinCaseNumCoinsText::
	.DB $00
	.STRINGMAP pokemon, "Coins"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $02
	.DW wPlayerCoins
	.DB $c2
	.DB $00
	.STRINGMAP pokemon, " "
	.DB $58
_ItemfinderFoundItemText::
	.DB $00
	.STRINGMAP pokemon, "Yes! ITEMFINDER"
	.DB $4f
	.STRINGMAP pokemon, "indicates there's"
	.DB $55
	.STRINGMAP pokemon, "an item nearby."
	.DB $58
_ItemfinderFoundNothingText::
	.DB $00
	.STRINGMAP pokemon, "Nope! ITEMFINDER"
	.DB $4f
	.STRINGMAP pokemon, "isn't responding."
	.DB $58
_RaisePPWhichTechniqueText::
	.DB $00
	.STRINGMAP pokemon, "Raise PP of which"
	.DB $4f
	.STRINGMAP pokemon, "technique?"
	.DB $57
_RestorePPWhichTechniqueText::
	.DB $00
	.STRINGMAP pokemon, "Restore PP of"
	.DB $4f
	.STRINGMAP pokemon, "which technique?"
	.DB $57
_PPMaxedOutText::
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "'s PP"
	.DB $4f
	.STRINGMAP pokemon, "is maxed out."
	.DB $58
_PPIncreasedText::
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "'s PP"
	.DB $4f
	.STRINGMAP pokemon, "increased."
	.DB $58
_PPRestoredText::
	.DB $00
	.STRINGMAP pokemon, "PP was restored."
	.DB $58
_BootedUpTMText::
	.DB $00
	.STRINGMAP pokemon, "Booted up a TM!"
	.DB $58
_BootedUpHMText::
	.DB $00
	.STRINGMAP pokemon, "Booted up an HM!"
	.DB $58
_TeachMachineMoveText::
	.DB $00
	.STRINGMAP pokemon, "It contained"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $51
	.STRINGMAP pokemon, "Teach @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "to a #MON?"
	.DB $57
_MonCannotLearnMachineMoveText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " is not"
	.DB $4f
	.STRINGMAP pokemon, "compatible with"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $51
	.STRINGMAP pokemon, "It can't learn"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $58
_ItemUseNotTimeText::
	.DB $00
	.STRINGMAP pokemon, "OAK: <PLAYER>!"
	.DB $4f
	.STRINGMAP pokemon, "This isn't the"
	.DB $55
	.STRINGMAP pokemon, "time to use that! "
	.DB $58
_ItemUseNotYoursToUseText::
	.DB $00
	.STRINGMAP pokemon, "This isn't yours"
	.DB $4f
	.STRINGMAP pokemon, "to use!"
	.DB $58
_ItemUseNoEffectText::
	.DB $00
	.STRINGMAP pokemon, "It won't have any"
	.DB $4f
	.STRINGMAP pokemon, "effect."
	.DB $58
_ThrowBallAtTrainerMonText1::
	.DB $00
	.STRINGMAP pokemon, "The trainer"
	.DB $4f
	.STRINGMAP pokemon, "blocked the BALL!"
	.DB $58
_ThrowBallAtTrainerMonText2::
	.DB $00
	.STRINGMAP pokemon, "Don't be a thief!"
	.DB $58
_NoCyclingAllowedHereText::
	.DB $00
	.STRINGMAP pokemon, "No cycling"
	.DB $4e
	.STRINGMAP pokemon, "allowed here."
	.DB $58
_NoSurfingHereText::
	.DB $00
	.STRINGMAP pokemon, "No SURFing on"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " here!"
	.DB $58
_BoxFullCannotThrowBallText::
	.DB $00
	.STRINGMAP pokemon, "The #MON BOX"
	.DB $4f
	.STRINGMAP pokemon, "is full! Can't"
	.DB $55
	.STRINGMAP pokemon, "use that item!"
	.DB $58

Bank41TextEnd::
