; Generated by convert_text_bank.py from:
;   text/FuchsiaGym_2.asm
;   text/FuchsiaMeetingRoom.asm
;   text/FuchsiaGoodRodHouse.asm
;   text/PokemonMansion1F.asm
;   text/CinnabarGym.asm
;   text/CinnabarLab.asm
;   text/CinnabarLabTradeRoom.asm
;   text/CinnabarLabMetronomeRoom.asm
;   text/CinnabarLabFossilRoom.asm
;   text/CinnabarPokecenter.asm
;   text/CinnabarMart.asm
;   text/IndigoPlateauLobby.asm
;   text/CopycatsHouse1F.asm
;   text/CopycatsHouse2F.asm
;   text/FightingDojo.asm
;   text/SaffronGym.asm
;   text/SaffronPidgeyHouse.asm
;   text/SaffronMart.asm
;   text/SilphCo1F.asm
;   text/SaffronPokecenter.asm
;   text/MrPsychicsHouse.asm
;   data/text/text_4.asm
.STRINGMAPTABLE pokemon "wla/pokemon.tbl"

; text/FuchsiaGym_2.asm
_FuchsiaGymKogaPostBattleAdviceText::
	.DB $00
	.STRINGMAP pokemon, "When afflicted by"
	.DB $4f
	.STRINGMAP pokemon, "TOXIC, #MON"
	.DB $55
	.STRINGMAP pokemon, "suffer more and"
	.DB $55
	.STRINGMAP pokemon, "more as battle"
	.DB $55
	.STRINGMAP pokemon, "progresses!"
	.DB $51
	.STRINGMAP pokemon, "It will surely"
	.DB $4f
	.STRINGMAP pokemon, "terrorize foes!"
	.DB $57
_FuchsiaGymKogaSoulBadgeInfoText::
	.DB $00
	.STRINGMAP pokemon, "Now that you have"
	.DB $4f
	.STRINGMAP pokemon, "the SOULBADGE,"
	.DB $55
	.STRINGMAP pokemon, "the DEFENSE of"
	.DB $55
	.STRINGMAP pokemon, "your #MON"
	.DB $55
	.STRINGMAP pokemon, "increases!"
	.DB $51
	.STRINGMAP pokemon, "It also lets you"
	.DB $4f
	.STRINGMAP pokemon, "SURF outside of"
	.DB $55
	.STRINGMAP pokemon, "battle!"
	.DB $51
	.STRINGMAP pokemon, "Ah! Take this"
	.DB $4f
	.STRINGMAP pokemon, "too!"
	.DB $57
_FuchsiaGymKogaReceivedTM06Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_FuchsiaGymKogaTM06ExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "TM06 contains"
	.DB $4f
	.STRINGMAP pokemon, "TOXIC!"
	.DB $51
	.STRINGMAP pokemon, "It is a secret"
	.DB $4f
	.STRINGMAP pokemon, "technique over"
	.DB $55
	.STRINGMAP pokemon, "400 years old!"
	.DB $57
_FuchsiaGymKogaTM06NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Make space for"
	.DB $4f
	.STRINGMAP pokemon, "this, child!"
	.DB $57
_FuchsiaGymRocker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Strength isn't"
	.DB $4f
	.STRINGMAP pokemon, "the key for"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $51
	.STRINGMAP pokemon, "It's strategy!"
	.DB $51
	.STRINGMAP pokemon, "I'll show you how"
	.DB $4f
	.STRINGMAP pokemon, "strategy can beat"
	.DB $55
	.STRINGMAP pokemon, "brute strength!"
	.DB $57
_FuchsiaGymRocker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "What?"
	.DB $4f
	.STRINGMAP pokemon, "Extraordinary!"
	.DB $58
_FuchsiaGymRocker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "So, you mix brawn"
	.DB $4f
	.STRINGMAP pokemon, "with brains?"
	.DB $55
	.STRINGMAP pokemon, "Good strategy!"
	.DB $57
_FuchsiaGymRocker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I wanted to become"
	.DB $4f
	.STRINGMAP pokemon, "a ninja, so I"
	.DB $55
	.STRINGMAP pokemon, "joined this GYM!"
	.DB $57
_FuchsiaGymRocker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm done"
	.DB $4f
	.STRINGMAP pokemon, "for!"
	.DB $58
_FuchsiaGymRocker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I will keep on"
	.DB $4f
	.STRINGMAP pokemon, "training under"
	.DB $55
	.STRINGMAP pokemon, "KOGA, my ninja"
	.DB $55
	.STRINGMAP pokemon, "master!"
	.DB $57
_FuchsiaGymRocker3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Let's see you"
	.DB $4f
	.STRINGMAP pokemon, "beat my special"
	.DB $55
	.STRINGMAP pokemon, "techniques!"
	.DB $57
_FuchsiaGymRocker3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "had me fooled!"
	.DB $58
_FuchsiaGymRocker3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I like poison and"
	.DB $4f
	.STRINGMAP pokemon, "sleep techniques,"
	.DB $55
	.STRINGMAP pokemon, "as they linger"
	.DB $55
	.STRINGMAP pokemon, "after battle!"
	.DB $57
_FuchsiaGymRocker4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Stop right there!"
	.DB $51
	.STRINGMAP pokemon, "Our invisible"
	.DB $4f
	.STRINGMAP pokemon, "walls have you"
	.DB $55
	.STRINGMAP pokemon, "frustrated?"
	.DB $57
_FuchsiaGymRocker4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whoa!"
	.DB $4f
	.STRINGMAP pokemon, "He's got it!"
	.DB $58
_FuchsiaGymRocker4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You impressed me!"
	.DB $4f
	.STRINGMAP pokemon, "Here's a hint!"
	.DB $51
	.STRINGMAP pokemon, "Look very closely"
	.DB $4f
	.STRINGMAP pokemon, "for gaps in the"
	.DB $55
	.STRINGMAP pokemon, "invisible walls!"
	.DB $57
_FuchsiaGymRocker5BattleText::
	.DB $00
	.STRINGMAP pokemon, "I also study the"
	.DB $4f
	.STRINGMAP pokemon, "way of the ninja"
	.DB $55
	.STRINGMAP pokemon, "with master KOGA!"
	.DB $51
	.STRINGMAP pokemon, "Ninja have a long"
	.DB $4f
	.STRINGMAP pokemon, "history of using"
	.DB $55
	.STRINGMAP pokemon, "animals!"
	.DB $57
_FuchsiaGymRocker5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Awoo!"
	.DB $58
_FuchsiaGymRocker5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I still have much"
	.DB $4f
	.STRINGMAP pokemon, "to learn!"
	.DB $57
_FuchsiaGymRocker6BattleText::
	.DB $00
	.STRINGMAP pokemon, "Master KOGA comes"
	.DB $4f
	.STRINGMAP pokemon, "from a long line"
	.DB $55
	.STRINGMAP pokemon, "of ninjas!"
	.DB $51
	.STRINGMAP pokemon, "What did you"
	.DB $4f
	.STRINGMAP pokemon, "descend from?"
	.DB $57
_FuchsiaGymRocker6EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Dropped"
	.DB $4f
	.STRINGMAP pokemon, "my balls!"
	.DB $58
_FuchsiaGymRocker6AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Where there is"
	.DB $4f
	.STRINGMAP pokemon, "light, there is"
	.DB $55
	.STRINGMAP pokemon, "shadow!"
	.DB $51
	.STRINGMAP pokemon, "Light and shadow!"
	.DB $4f
	.STRINGMAP pokemon, "Which do you"
	.DB $55
	.STRINGMAP pokemon, "choose?"
	.DB $57
_FuchsiaGymGymGuideChampInMakingText::
	.DB $00
	.STRINGMAP pokemon, "Yo! Champ in"
	.DB $4f
	.STRINGMAP pokemon, "making!"
	.DB $51
	.STRINGMAP pokemon, "FUCHSIA GYM is"
	.DB $4f
	.STRINGMAP pokemon, "riddled with"
	.DB $55
	.STRINGMAP pokemon, "invisible walls!"
	.DB $51
	.STRINGMAP pokemon, "KOGA might appear"
	.DB $4f
	.STRINGMAP pokemon, "close, but he's"
	.DB $55
	.STRINGMAP pokemon, "blocked off!"
	.DB $51
	.STRINGMAP pokemon, "You have to find"
	.DB $4f
	.STRINGMAP pokemon, "gaps in the walls"
	.DB $55
	.STRINGMAP pokemon, "to reach him!"
	.DB $57
_FuchsiaGymGymGuideBeatKogaText::
	.DB $00
	.STRINGMAP pokemon, "It's amazing how"
	.DB $4f
	.STRINGMAP pokemon, "ninja can terrify"
	.DB $55
	.STRINGMAP pokemon, "even now!"
	.DB $57

; text/FuchsiaMeetingRoom.asm
_FuchsiaMeetingRoomSafariZoneWorker1::
	.DB $00
	.STRINGMAP pokemon, "We nicknamed the"
	.DB $4f
	.STRINGMAP pokemon, "WARDEN SLOWPOKE."
	.DB $51
	.STRINGMAP pokemon, "He and SLOWPOKE"
	.DB $4f
	.STRINGMAP pokemon, "both look vacant!"
	.DB $57
_FuchsiaMeetingRoomSafariZoneWorker2::
	.DB $00
	.STRINGMAP pokemon, "SLOWPOKE is very"
	.DB $4f
	.STRINGMAP pokemon, "knowledgeable"
	.DB $55
	.STRINGMAP pokemon, "about #MON!"
	.DB $51
	.STRINGMAP pokemon, "He even has some"
	.DB $4f
	.STRINGMAP pokemon, "fossils of rare,"
	.DB $55
	.STRINGMAP pokemon, "extinct #MON!"
	.DB $57
_FuchsiaMeetingRoomSafariZoneWorker3::
	.DB $00
	.STRINGMAP pokemon, "SLOWPOKE came in,"
	.DB $4f
	.STRINGMAP pokemon, "but I couldn't"
	.DB $55
	.STRINGMAP pokemon, "understand him."
	.DB $51
	.STRINGMAP pokemon, "I think he's got"
	.DB $4f
	.STRINGMAP pokemon, "a speech problem!"
	.DB $57

; text/FuchsiaGoodRodHouse.asm
_FuchsiaGoodRodHouseFishingGuruText::
	.DB $00
	.STRINGMAP pokemon, "I'm the FISHING"
	.DB $4f
	.STRINGMAP pokemon, "GURU's older"
	.DB $55
	.STRINGMAP pokemon, "brother!"
	.DB $51
	.STRINGMAP pokemon, "I simply Looove"
	.DB $4f
	.STRINGMAP pokemon, "fishing!"
	.DB $51
	.STRINGMAP pokemon, "Do you like to"
	.DB $4f
	.STRINGMAP pokemon, "fish?"
	.DB $57
_FuchsiaGoodRodHouseFishingGuruReceivedGoodRodText::
	.DB $00
	.STRINGMAP pokemon, "Grand! I like"
	.DB $4f
	.STRINGMAP pokemon, "your style!"
	.DB $51
	.STRINGMAP pokemon, "Take this and"
	.DB $4f
	.STRINGMAP pokemon, "fish, young one!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "a @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_FuchsiaGoodRodHouseFishingGuruThatsSoDisappointingText::
	.DB $00
	.STRINGMAP pokemon, "Oh... That's so"
	.DB $4f
	.STRINGMAP pokemon, "disappointing..."
	.DB $57
_FuchsiaGoodRodHouseFishingGuruHowAreTheFishText::
	.DB $00
	.STRINGMAP pokemon, "Hello there,"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "How are the fish"
	.DB $4f
	.STRINGMAP pokemon, "biting?"
	.DB $57
_FuchsiaGoodRodHouseFishingGuruNoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Oh no!"
	.DB $51
	.STRINGMAP pokemon, "You have no room"
	.DB $4f
	.STRINGMAP pokemon, "for my gift!"
	.DB $57

; text/PokemonMansion1F.asm
_PokemonMansion1FScientistBattleText::
	.DB $00
	.STRINGMAP pokemon, "Who are you? There"
	.DB $4f
	.STRINGMAP pokemon, "shouldn't be"
	.DB $55
	.STRINGMAP pokemon, "anyone here."
	.DB $57
_PokemonMansion1FScientistEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ouch!"
	.DB $58
_PokemonMansion1FScientistAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "A key? I don't"
	.DB $4f
	.STRINGMAP pokemon, "know what you're"
	.DB $55
	.STRINGMAP pokemon, "talking about."
	.DB $57
_PokemonMansion1FSwitchText::
	.DB $00
	.STRINGMAP pokemon, "A secret switch!"
	.DB $51
	.STRINGMAP pokemon, "Press it?"
	.DB $57
_PokemonMansion1FSwitchPressedText::
	.DB $00
	.STRINGMAP pokemon, "Who wouldn't?"
	.DB $58
_PokemonMansion1FSwitchNotPressedText::
	.DB $00
	.STRINGMAP pokemon, "Not quite yet!"
	.DB $57

; text/CinnabarGym.asm
_CinnabarGymBlainePreBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hah!"
	.DB $51
	.STRINGMAP pokemon, "I am BLAINE! I"
	.DB $4f
	.STRINGMAP pokemon, "am the LEADER of"
	.DB $55
	.STRINGMAP pokemon, "CINNABAR GYM!"
	.DB $51
	.STRINGMAP pokemon, "My fiery #MON"
	.DB $4f
	.STRINGMAP pokemon, "will incinerate"
	.DB $55
	.STRINGMAP pokemon, "all challengers!"
	.DB $51
	.STRINGMAP pokemon, "Hah! You better"
	.DB $4f
	.STRINGMAP pokemon, "have BURN HEAL!"
	.DB $57
_CinnabarGymBlaineReceivedVolcanoBadgeText::
	.DB $00
	.STRINGMAP pokemon, "I have"
	.DB $4f
	.STRINGMAP pokemon, "burnt out!"
	.DB $51
	.STRINGMAP pokemon, "You have earned"
	.DB $4f
	.STRINGMAP pokemon, "the VOLCANOBADGE!@"
	.DB $50
_CinnabarGymBlainePostBattleAdviceText::
	.DB $00
	.STRINGMAP pokemon, "FIRE BLAST is the"
	.DB $4f
	.STRINGMAP pokemon, "ultimate fire"
	.DB $55
	.STRINGMAP pokemon, "technique!"
	.DB $51
	.STRINGMAP pokemon, "Don't waste it on"
	.DB $4f
	.STRINGMAP pokemon, "water #MON!"
	.DB $57
_CinnabarGymBlaineVolcanoBadgeInfoText::
	.DB $00
	.STRINGMAP pokemon, "Hah!"
	.DB $51
	.STRINGMAP pokemon, "The VOLCANOBADGE"
	.DB $4f
	.STRINGMAP pokemon, "heightens the"
	.DB $55
	.STRINGMAP pokemon, "SPECIAL abilities"
	.DB $55
	.STRINGMAP pokemon, "of your #MON!"
	.DB $51
	.STRINGMAP pokemon, "Here, you can"
	.DB $4f
	.STRINGMAP pokemon, "have this too!"
	.DB $57
_CinnabarGymBlaineReceivedTM38Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_CinnabarGymBlaineTM38ExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "TM38 contains"
	.DB $4f
	.STRINGMAP pokemon, "FIRE BLAST!"
	.DB $51
	.STRINGMAP pokemon, "Teach it to fire-"
	.DB $4f
	.STRINGMAP pokemon, "type #MON!"
	.DB $51
	.STRINGMAP pokemon, "CHARMELEON or"
	.DB $4f
	.STRINGMAP pokemon, "PONYTA would be"
	.DB $55
	.STRINGMAP pokemon, "good bets!"
	.DB $57
_CinnabarGymBlaineTM38NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Make room for my"
	.DB $4f
	.STRINGMAP pokemon, "gift!"
	.DB $57
_CinnabarGymSuperNerd1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Do you know how"
	.DB $4f
	.STRINGMAP pokemon, "hot #MON fire"
	.DB $55
	.STRINGMAP pokemon, "breath can get?"
	.DB $57
_CinnabarGymSuperNerd1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Yow!"
	.DB $4f
	.STRINGMAP pokemon, "Hot, hot, hot!"
	.DB $58
_CinnabarGymSuperNerd1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Fire, or to be"
	.DB $4f
	.STRINGMAP pokemon, "more precise,"
	.DB $55
	.STRINGMAP pokemon, "combustion..."
	.DB $51
	.STRINGMAP pokemon, "Blah, blah, blah,"
	.DB $4f
	.STRINGMAP pokemon, "blah..."
	.DB $57
_CinnabarGymSuperNerd2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I was a thief, but"
	.DB $4f
	.STRINGMAP pokemon, "I became straight"
	.DB $55
	.STRINGMAP pokemon, "as a trainer!"
	.DB $57
_CinnabarGymSuperNerd2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "surrender!"
	.DB $58
_CinnabarGymSuperNerd2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I can't help"
	.DB $4f
	.STRINGMAP pokemon, "stealing other"
	.DB $55
	.STRINGMAP pokemon, "people's #MON!"
	.DB $57
_CinnabarGymSuperNerd3BattleText::
	.DB $00
	.STRINGMAP pokemon, "You can't win!"
	.DB $4f
	.STRINGMAP pokemon, "I have studied"
	.DB $55
	.STRINGMAP pokemon, "#MON totally!"
	.DB $57
_CinnabarGymSuperNerd3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Waah!"
	.DB $4f
	.STRINGMAP pokemon, "My studies!"
	.DB $58
_CinnabarGymSuperNerd3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "My theories are"
	.DB $4f
	.STRINGMAP pokemon, "too complicated"
	.DB $55
	.STRINGMAP pokemon, "for you!"
	.DB $57
_CinnabarGymSuperNerd4BattleText::
	.DB $00
	.STRINGMAP pokemon, "I just like using"
	.DB $4f
	.STRINGMAP pokemon, "fire #MON!"
	.DB $57
_CinnabarGymSuperNerd4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Too hot"
	.DB $4f
	.STRINGMAP pokemon, "to handle!"
	.DB $58
_CinnabarGymSuperNerd4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I wish there was"
	.DB $4f
	.STRINGMAP pokemon, "a thief #MON!"
	.DB $55
	.STRINGMAP pokemon, "I'd use that!"
	.DB $57
_CinnabarGymSuperNerd5BattleText::
	.DB $00
	.STRINGMAP pokemon, "I know why BLAINE"
	.DB $4f
	.STRINGMAP pokemon, "became a trainer!"
	.DB $57
_CinnabarGymSuperNerd5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ow!"
	.DB $58
_CinnabarGymSuperNerd5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "BLAINE was lost"
	.DB $4f
	.STRINGMAP pokemon, "in the mountains"
	.DB $55
	.STRINGMAP pokemon, "when a fiery bird"
	.DB $55
	.STRINGMAP pokemon, "#MON appeared."
	.DB $51
	.STRINGMAP pokemon, "Its light enabled"
	.DB $4f
	.STRINGMAP pokemon, "BLAINE to find"
	.DB $55
	.STRINGMAP pokemon, "his way down!"
	.DB $57
_CinnabarGymSuperNerd6BattleText::
	.DB $00
	.STRINGMAP pokemon, "I've been to many"
	.DB $4f
	.STRINGMAP pokemon, "GYMs, but this is"
	.DB $55
	.STRINGMAP pokemon, "my favorite!"
	.DB $57
_CinnabarGymSuperNerd6EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Yowza!"
	.DB $4f
	.STRINGMAP pokemon, "Too hot!"
	.DB $58
_CinnabarGymSuperNerd6AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Us fire #MON"
	.DB $4f
	.STRINGMAP pokemon, "fans like PONYTA"
	.DB $55
	.STRINGMAP pokemon, "and NINETALES!"
	.DB $57
_CinnabarGymSuperNerd7BattleText::
	.DB $00
	.STRINGMAP pokemon, "Fire is weak"
	.DB $4f
	.STRINGMAP pokemon, "against H2O!"
	.DB $57
_CinnabarGymSuperNerd7EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh!"
	.DB $4f
	.STRINGMAP pokemon, "Snuffed out!"
	.DB $58
_CinnabarGymSuperNerd7AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Water beats fire!"
	.DB $4f
	.STRINGMAP pokemon, "But, fire melts"
	.DB $55
	.STRINGMAP pokemon, "ice #MON!"
	.DB $57
_CinnabarGymGymGuideChampInMakingText::
	.DB $00
	.STRINGMAP pokemon, "Yo! Champ in"
	.DB $4f
	.STRINGMAP pokemon, "making!"
	.DB $51
	.STRINGMAP pokemon, "The hot-headed"
	.DB $4f
	.STRINGMAP pokemon, "BLAINE is a fire"
	.DB $55
	.STRINGMAP pokemon, "#MON pro!"
	.DB $51
	.STRINGMAP pokemon, "Douse his spirits"
	.DB $4f
	.STRINGMAP pokemon, "with water!"
	.DB $51
	.STRINGMAP pokemon, "You better take"
	.DB $4f
	.STRINGMAP pokemon, "some BURN HEALs!"
	.DB $57
_CinnabarGymGymGuideBeatBlaineText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER>! You beat"
	.DB $4f
	.STRINGMAP pokemon, "that fire brand!"
	.DB $57

; text/CinnabarLab.asm
_CinnabarLabFishingGuruText::
	.DB $00
	.STRINGMAP pokemon, "We study #MON"
	.DB $4f
	.STRINGMAP pokemon, "extensively here."
	.DB $51
	.STRINGMAP pokemon, "People often bring"
	.DB $4f
	.STRINGMAP pokemon, "us rare #MON"
	.DB $55
	.STRINGMAP pokemon, "for examination."
	.DB $57
_CinnabarLabPhotoText::
	.DB $00
	.STRINGMAP pokemon, "A photo of the"
	.DB $4f
	.STRINGMAP pokemon, "LAB's founder,"
	.DB $55
	.STRINGMAP pokemon, "DR.FUJI!"
	.DB $57
_CinnabarLabMeetingRoomSignText::
	.DB $00
	.STRINGMAP pokemon, "#MON LAB"
	.DB $4f
	.STRINGMAP pokemon, "Meeting Room"
	.DB $57
_CinnabarLabRAndDSignText::
	.DB $00
	.STRINGMAP pokemon, "#MON LAB"
	.DB $4f
	.STRINGMAP pokemon, "R-and-D Room"
	.DB $57
_CinnabarLabTestingRoomSignText::
	.DB $00
	.STRINGMAP pokemon, "#MON LAB"
	.DB $4f
	.STRINGMAP pokemon, "Testing Room"
	.DB $57

; text/CinnabarLabTradeRoom.asm
_CinnabarLabTradeRoomSuperNerdText::
	.DB $00
	.STRINGMAP pokemon, "I found this very"
	.DB $4f
	.STRINGMAP pokemon, "strange fossil in"
	.DB $55
	.STRINGMAP pokemon, "MT.MOON!"
	.DB $51
	.STRINGMAP pokemon, "I think it's a"
	.DB $4f
	.STRINGMAP pokemon, "rare, prehistoric"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $57

; text/CinnabarLabMetronomeRoom.asm
_CinnabarLabMetronomeRoomScientist1Text::
	.DB $00
	.STRINGMAP pokemon, "Tch-tch-tch!"
	.DB $4f
	.STRINGMAP pokemon, "I made a cool TM!"
	.DB $51
	.STRINGMAP pokemon, "It can cause all"
	.DB $4f
	.STRINGMAP pokemon, "kinds of fun!"
	.DB $58
_CinnabarLabMetronomeRoomScientist1ReceivedTM35Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received "
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_CinnabarLabMetronomeRoomScientist1TM35ExplanationText::
	.DB $00
	.STRINGMAP pokemon, "Tch-tch-tch!"
	.DB $4f
	.STRINGMAP pokemon, "That's the sound"
	.DB $55
	.STRINGMAP pokemon, "of a METRONOME!"
	.DB $51
	.STRINGMAP pokemon, "It tweaks your"
	.DB $4f
	.STRINGMAP pokemon, "#MON's brain"
	.DB $55
	.STRINGMAP pokemon, "into using moves"
	.DB $55
	.STRINGMAP pokemon, "it doesn't know!"
	.DB $57
_CinnabarLabMetronomeRoomScientist1TM35NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Your pack is"
	.DB $4f
	.STRINGMAP pokemon, "crammed full!"
	.DB $57
_CinnabarLabMetronomeRoomScientist2Text::
	.DB $00
	.STRINGMAP pokemon, "EEVEE can evolve"
	.DB $4f
	.STRINGMAP pokemon, "into 1 of 3 kinds"
	.DB $55
	.STRINGMAP pokemon, "of #MON."
	.DB $57
_CinnabarLabMetronomeRoomPCText::
	.DB $00
	.STRINGMAP pokemon, "There's an e-mail"
	.DB $4f
	.STRINGMAP pokemon, "message!"
	.DB $51
	.STRINGMAP pokemon, "..."
	.DB $51
	.STRINGMAP pokemon, "The 3 legendary"
	.DB $4f
	.STRINGMAP pokemon, "bird #MON are"
	.DB $55
	.STRINGMAP pokemon, "ARTICUNO, ZAPDOS"
	.DB $55
	.STRINGMAP pokemon, "and MOLTRES."
	.DB $51
	.STRINGMAP pokemon, "Their whereabouts"
	.DB $4f
	.STRINGMAP pokemon, "are unknown."
	.DB $51
	.STRINGMAP pokemon, "We plan to explore"
	.DB $4f
	.STRINGMAP pokemon, "the cavern close"
	.DB $55
	.STRINGMAP pokemon, "to CERULEAN."
	.DB $51
	.STRINGMAP pokemon, "From: #MON"
	.DB $4f
	.STRINGMAP pokemon, "RESEARCH TEAM"
	.DB $51
	.STRINGMAP pokemon, "..."
	.DB $57
_CinnabarLabMetronomeRoomAmberPipeText::
	.DB $00
	.STRINGMAP pokemon, "An amber pipe!"
	.DB $57

; text/CinnabarLabFossilRoom.asm
_CinnabarLabFossilRoomScientist1Text::
	.DB $00
	.STRINGMAP pokemon, "Hiya!"
	.DB $51
	.STRINGMAP pokemon, "I am important"
	.DB $4f
	.STRINGMAP pokemon, "doctor!"
	.DB $51
	.STRINGMAP pokemon, "I study here rare"
	.DB $4f
	.STRINGMAP pokemon, "#MON fossils!"
	.DB $51
	.STRINGMAP pokemon, "You! Have you a"
	.DB $4f
	.STRINGMAP pokemon, "fossil for me?"
	.DB $58
_CinnabarLabFossilRoomScientist1NoFossilsText::
	.DB $00
	.STRINGMAP pokemon, "No! Is too bad!"
	.DB $57
_CinnabarLabFossilRoomScientist1GoForAWalkText::
	.DB $00
	.STRINGMAP pokemon, "I take a little"
	.DB $4f
	.STRINGMAP pokemon, "time!"
	.DB $51
	.STRINGMAP pokemon, "You go for walk a"
	.DB $4f
	.STRINGMAP pokemon, "little while!"
	.DB $57
_CinnabarLabFossilRoomScientist1FossilIsBackToLifeText::
	.DB $00
	.STRINGMAP pokemon, "Where were you?"
	.DB $51
	.STRINGMAP pokemon, "Your fossil is"
	.DB $4f
	.STRINGMAP pokemon, "back to life!"
	.DB $51
	.STRINGMAP pokemon, "It was @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "like I think!"
	.DB $58
_CinnabarLabFossilRoomScientist1SeesFossilText::
	.DB $00
	.STRINGMAP pokemon, "Oh! That is"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $51
	.STRINGMAP pokemon, "It is fossil of"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, ", a"
	.DB $55
	.STRINGMAP pokemon, "#MON that is"
	.DB $55
	.STRINGMAP pokemon, "already extinct!"
	.DB $51
	.STRINGMAP pokemon, "My Resurrection"
	.DB $4f
	.STRINGMAP pokemon, "Machine will make"
	.DB $55
	.STRINGMAP pokemon, "that #MON live"
	.DB $55
	.STRINGMAP pokemon, "again!"
	.DB $57
_CinnabarLabFossilRoomScientist1TakesFossilText::
	.DB $00
	.STRINGMAP pokemon, "So! You hurry and"
	.DB $4f
	.STRINGMAP pokemon, "give me that!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> handed"
	.DB $4f
	.STRINGMAP pokemon, "over @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $58
_CinnabarLabFossilRoomScientist1GoForAWalkText2::
	.DB $00
	.STRINGMAP pokemon, "I take a little"
	.DB $4f
	.STRINGMAP pokemon, "time!"
	.DB $51
	.STRINGMAP pokemon, "You go for walk a"
	.DB $4f
	.STRINGMAP pokemon, "little while!"
	.DB $57
_CinnabarLabFossilRoomScientist1ComeAgainText::
	.DB $00
	.STRINGMAP pokemon, "Aiyah! You come"
	.DB $4f
	.STRINGMAP pokemon, "again!"
	.DB $57

; text/CinnabarPokecenter.asm
_CinnabarPokecenterCooltrainerFText::
	.DB $00
	.STRINGMAP pokemon, "You can cancel"
	.DB $4f
	.STRINGMAP pokemon, "evolution."
	.DB $51
	.STRINGMAP pokemon, "When a #MON is"
	.DB $4f
	.STRINGMAP pokemon, "evolving, you can"
	.DB $55
	.STRINGMAP pokemon, "stop it and leave"
	.DB $55
	.STRINGMAP pokemon, "it the way it is."
	.DB $57
_CinnabarPokecenterGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "Do you have any"
	.DB $4f
	.STRINGMAP pokemon, "friends?"
	.DB $51
	.STRINGMAP pokemon, "#MON you get"
	.DB $4f
	.STRINGMAP pokemon, "in trades grow"
	.DB $55
	.STRINGMAP pokemon, "very quickly."
	.DB $51
	.STRINGMAP pokemon, "I think it's"
	.DB $4f
	.STRINGMAP pokemon, "worth a try!"
	.DB $57

; text/CinnabarMart.asm
_CinnabarMartSilphWorkerFText::
	.DB $00
	.STRINGMAP pokemon, "Don't they have X"
	.DB $4f
	.STRINGMAP pokemon, "ATTACK? It's good"
	.DB $55
	.STRINGMAP pokemon, "for battles!"
	.DB $57
_CinnabarMartScientistText::
	.DB $00
	.STRINGMAP pokemon, "It never hurts to"
	.DB $4f
	.STRINGMAP pokemon, "have extra items!"
	.DB $57

; text/IndigoPlateauLobby.asm
_IndigoPlateauLobbyGymGuideText::
	.DB $00
	.STRINGMAP pokemon, "Yo! Champ in"
	.DB $4f
	.STRINGMAP pokemon, "making!"
	.DB $51
	.STRINGMAP pokemon, "At #MON LEAGUE,"
	.DB $4f
	.STRINGMAP pokemon, "you have to face"
	.DB $55
	.STRINGMAP pokemon, "the ELITE FOUR in"
	.DB $55
	.STRINGMAP pokemon, "succession."
	.DB $51
	.STRINGMAP pokemon, "If you lose, you"
	.DB $4f
	.STRINGMAP pokemon, "have to start all"
	.DB $55
	.STRINGMAP pokemon, "over again! This"
	.DB $55
	.STRINGMAP pokemon, "is it! Go for it!"
	.DB $57
_IndigoPlateauLobbyCooltrainerFText::
	.DB $00
	.STRINGMAP pokemon, "From here on, you"
	.DB $4f
	.STRINGMAP pokemon, "face the ELITE"
	.DB $55
	.STRINGMAP pokemon, "FOUR one by one!"
	.DB $51
	.STRINGMAP pokemon, "If you win, a"
	.DB $4f
	.STRINGMAP pokemon, "door opens to the"
	.DB $55
	.STRINGMAP pokemon, "next trainer!"
	.DB $55
	.STRINGMAP pokemon, "Good luck!"
	.DB $57

; text/CopycatsHouse1F.asm
_CopycatsHouse1FMiddleAgedWomanText::
	.DB $00
	.STRINGMAP pokemon, "My daughter is so"
	.DB $4f
	.STRINGMAP pokemon, "self-centered."
	.DB $55
	.STRINGMAP pokemon, "She only has a"
	.DB $55
	.STRINGMAP pokemon, "few friends."
	.DB $57
_CopycatsHouse1FMiddleAgedManText::
	.DB $00
	.STRINGMAP pokemon, "My daughter likes"
	.DB $4f
	.STRINGMAP pokemon, "to mimic people."
	.DB $51
	.STRINGMAP pokemon, "Her mimicry has"
	.DB $4f
	.STRINGMAP pokemon, "earned her the"
	.DB $55
	.STRINGMAP pokemon, "nickname COPYCAT"
	.DB $55
	.STRINGMAP pokemon, "around here!"
	.DB $57
_CopycatsHouse1FChanseyText::
	.DB $00
	.STRINGMAP pokemon, "CHANSEY: Chaan!"
	.DB $4f
	.STRINGMAP pokemon, "Sii!@"
	.DB $50

; text/CopycatsHouse2F.asm
_CopycatsHouse2FCopycatDoYouLikePokemonText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER>: Hi! Do"
	.DB $4f
	.STRINGMAP pokemon, "you like #MON?"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>: Uh no, I"
	.DB $4f
	.STRINGMAP pokemon, "just asked you."
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>: Huh?"
	.DB $4f
	.STRINGMAP pokemon, "You're strange!"
	.DB $51
	.STRINGMAP pokemon, "COPYCAT: Hmm?"
	.DB $4f
	.STRINGMAP pokemon, "Quit mimicking?"
	.DB $51
	.STRINGMAP pokemon, "But, that's my"
	.DB $4f
	.STRINGMAP pokemon, "favorite hobby!"
	.DB $58
_CopycatsHouse2FCopycatTM31PreReceiveText::
	.DB $00
	.STRINGMAP pokemon, "Oh wow!"
	.DB $4f
	.STRINGMAP pokemon, "A # DOLL!"
	.DB $51
	.STRINGMAP pokemon, "For me?"
	.DB $4f
	.STRINGMAP pokemon, "Thank you!"
	.DB $51
	.STRINGMAP pokemon, "You can have"
	.DB $4f
	.STRINGMAP pokemon, "this, then!"
	.DB $58
_CopycatsHouse2FCopycatReceivedTM31Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_CopycatsHouse2FCopycatTM31Explanation1Text::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "TM31 contains my"
	.DB $4f
	.STRINGMAP pokemon, "favorite, MIMIC!"
	.DB $51
	.STRINGMAP pokemon, "Use it on a good"
	.DB $4f
	.STRINGMAP pokemon, "#MON!@"
	.DB $50
_CopycatsHouse2FCopycatTM31Explanation2Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER>: Hi!"
	.DB $4f
	.STRINGMAP pokemon, "Thanks for TM31!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>: Pardon?"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>: Is it"
	.DB $4f
	.STRINGMAP pokemon, "that fun to mimic"
	.DB $55
	.STRINGMAP pokemon, "my every move?"
	.DB $51
	.STRINGMAP pokemon, "COPYCAT: You bet!"
	.DB $4f
	.STRINGMAP pokemon, "It's a scream!"
	.DB $57
_CopycatsHouse2FCopycatTM31NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Don't you want"
	.DB $4f
	.STRINGMAP pokemon, "this?@"
	.DB $50
_CopycatsHouse2FDoduoText::
	.DB $00
	.STRINGMAP pokemon, "DODUO: Giiih!"
	.DB $51
	.STRINGMAP pokemon, "MIRROR MIRROR ON"
	.DB $4f
	.STRINGMAP pokemon, "THE WALL, WHO IS"
	.DB $55
	.STRINGMAP pokemon, "THE FAIREST ONE"
	.DB $55
	.STRINGMAP pokemon, "OF ALL?"
	.DB $57
_CopycatsHouse2FRareDollText::
	.DB $00
	.STRINGMAP pokemon, "This is a rare"
	.DB $4f
	.STRINGMAP pokemon, "#MON! Huh?"
	.DB $55
	.STRINGMAP pokemon, "It's only a doll!"
	.DB $57
_CopycatsHouse2FSNESText::
	.DB $00
	.STRINGMAP pokemon, "A game with MARIO"
	.DB $4f
	.STRINGMAP pokemon, "wearing a bucket"
	.DB $55
	.STRINGMAP pokemon, "on his head!"
	.DB $57
_CopycatsHouse2FPCMySecretsText::
	.DB $00
	.STRINGMAP pokemon, "..."
	.DB $51
	.STRINGMAP pokemon, "My Secrets!"
	.DB $51
	.STRINGMAP pokemon, "Skill: Mimicry!"
	.DB $4f
	.STRINGMAP pokemon, "Hobby: Collecting"
	.DB $55
	.STRINGMAP pokemon, "dolls!"
	.DB $55
	.STRINGMAP pokemon, "Favorite #MON:"
	.DB $55
	.STRINGMAP pokemon, "CLEFAIRY!"
	.DB $57
_CopycatsHouse2FPCCantSeeText::
	.DB $00
	.STRINGMAP pokemon, "Huh? Can't see!"
	.DB $57

; text/FightingDojo.asm
_FightingDojoKarateMasterText::
	.DB $00
	.STRINGMAP pokemon, "Grunt!"
	.DB $51
	.STRINGMAP pokemon, "I am the KARATE"
	.DB $4f
	.STRINGMAP pokemon, "MASTER! I am the"
	.DB $55
	.STRINGMAP pokemon, "LEADER here!"
	.DB $51
	.STRINGMAP pokemon, "You wish to"
	.DB $4f
	.STRINGMAP pokemon, "challenge us?"
	.DB $55
	.STRINGMAP pokemon, "Expect no mercy!"
	.DB $51
	.STRINGMAP pokemon, "Fwaaa!"
	.DB $57
_FightingDojoKarateMasterDefeatedText::
	.DB $00
	.STRINGMAP pokemon, "Hwa!"
	.DB $4f
	.STRINGMAP pokemon, "Arrgh! Beaten!"
	.DB $58
_FightingDojoKarateMasterIWillGiveYouAPokemonText::
	.DB $00
	.STRINGMAP pokemon, "Indeed, I have"
	.DB $4f
	.STRINGMAP pokemon, "lost!"
	.DB $51
	.STRINGMAP pokemon, "But, I beseech"
	.DB $4f
	.STRINGMAP pokemon, "you, do not take"
	.DB $55
	.STRINGMAP pokemon, "our emblem as"
	.DB $55
	.STRINGMAP pokemon, "your trophy!"
	.DB $51
	.STRINGMAP pokemon, "In return, I will"
	.DB $4f
	.STRINGMAP pokemon, "give you a prized"
	.DB $55
	.STRINGMAP pokemon, "fighting #MON!"
	.DB $51
	.STRINGMAP pokemon, "Choose whichever"
	.DB $4f
	.STRINGMAP pokemon, "one you like!"
	.DB $57
_FightingDojoKarateMasterStayAndTrainWithUsText::
	.DB $00
	.STRINGMAP pokemon, "Ho!"
	.DB $51
	.STRINGMAP pokemon, "Stay and train at"
	.DB $4f
	.STRINGMAP pokemon, "Karate with us!"
	.DB $57
_FightingDojoBlackbelt1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hoargh! Take your"
	.DB $4f
	.STRINGMAP pokemon, "shoes off!"
	.DB $57
_FightingDojoBlackbelt1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I give"
	.DB $4f
	.STRINGMAP pokemon, "up!"
	.DB $58
_FightingDojoBlackbelt1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You wait 'til you"
	.DB $4f
	.STRINGMAP pokemon, "see our Master!"
	.DB $51
	.STRINGMAP pokemon, "I'm a small fry"
	.DB $4f
	.STRINGMAP pokemon, "compared to him!"
	.DB $57
_FightingDojoBlackbelt2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I hear you're"
	.DB $4f
	.STRINGMAP pokemon, "good! Show me!"
	.DB $57
_FightingDojoBlackbelt2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Judge!"
	.DB $4f
	.STRINGMAP pokemon, "1 point!"
	.DB $58
_FightingDojoBlackbelt2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Our Master is a"
	.DB $4f
	.STRINGMAP pokemon, "pro fighter!"
	.DB $57
_FightingDojoBlackbelt3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Nothing tough"
	.DB $4f
	.STRINGMAP pokemon, "frightens me!"
	.DB $51
	.STRINGMAP pokemon, "I break boulders"
	.DB $4f
	.STRINGMAP pokemon, "for training!"
	.DB $57
_FightingDojoBlackbelt3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Yow!"
	.DB $4f
	.STRINGMAP pokemon, "Stubbed fingers!"
	.DB $58
_FightingDojoBlackbelt3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The only thing"
	.DB $4f
	.STRINGMAP pokemon, "that frightens us"
	.DB $55
	.STRINGMAP pokemon, "is psychic power!"
	.DB $57
_FightingDojoBlackbelt4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hoohah!"
	.DB $51
	.STRINGMAP pokemon, "You're trespassing"
	.DB $4f
	.STRINGMAP pokemon, "in our FIGHTING"
	.DB $55
	.STRINGMAP pokemon, "DOJO!"
	.DB $57
_FightingDojoBlackbelt4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oof!"
	.DB $4f
	.STRINGMAP pokemon, "I give up!"
	.DB $58
_FightingDojoBlackbelt4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The prime fighters"
	.DB $4f
	.STRINGMAP pokemon, "across the land"
	.DB $55
	.STRINGMAP pokemon, "train here."
	.DB $57
_FightingDojoHitmonleePokeBallText::
	.DB $00
	.STRINGMAP pokemon, "You want the"
	.DB $4f
	.STRINGMAP pokemon, "hard kicking"
	.DB $55
	.STRINGMAP pokemon, "HITMONLEE?"
	.DB $57
_FightingDojoHitmonchanPokeBallText::
	.DB $00
	.STRINGMAP pokemon, "You want the"
	.DB $4f
	.STRINGMAP pokemon, "piston punching"
	.DB $55
	.STRINGMAP pokemon, "HITMONCHAN?"
	.DB $57
_FightingDojoBetterNotGetGreedyText::
	.DB $00
	.STRINGMAP pokemon, "Better not get"
	.DB $4f
	.STRINGMAP pokemon, "greedy..."
	.DB $57

; text/SaffronGym.asm
_SaffronGymSabrinaText::
	.DB $00
	.STRINGMAP pokemon, "I had a vision of"
	.DB $4f
	.STRINGMAP pokemon, "your arrival!"
	.DB $51
	.STRINGMAP pokemon, "I have had psychic"
	.DB $4f
	.STRINGMAP pokemon, "powers since I"
	.DB $55
	.STRINGMAP pokemon, "was a child."
	.DB $51
	.STRINGMAP pokemon, "I first learned"
	.DB $4f
	.STRINGMAP pokemon, "to bend spoons"
	.DB $55
	.STRINGMAP pokemon, "with my mind."
	.DB $51
	.STRINGMAP pokemon, "I dislike fight-"
	.DB $4f
	.STRINGMAP pokemon, "ing, but if you"
	.DB $55
	.STRINGMAP pokemon, "wish, I will show"
	.DB $55
	.STRINGMAP pokemon, "you my powers!"
	.DB $57
_SaffronGymSabrinaReceivedMarshBadgeText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "shocked!"
	.DB $55
	.STRINGMAP pokemon, "But, a loss is a"
	.DB $55
	.STRINGMAP pokemon, "loss."
	.DB $51
	.STRINGMAP pokemon, "I admit I didn't"
	.DB $4f
	.STRINGMAP pokemon, "work hard enough"
	.DB $55
	.STRINGMAP pokemon, "to win!"
	.DB $51
	.STRINGMAP pokemon, "You earned the"
	.DB $4f
	.STRINGMAP pokemon, "MARSHBADGE!@"
	.DB $50
_SaffronGymSabrinaPostBattleAdviceText::
	.DB $00
	.STRINGMAP pokemon, "Everyone has"
	.DB $4f
	.STRINGMAP pokemon, "psychic power!"
	.DB $55
	.STRINGMAP pokemon, "People just don't"
	.DB $55
	.STRINGMAP pokemon, "realize it!"
	.DB $57
_SaffronGymSabrinaMarshBadgeInfoText::
	.DB $00
	.STRINGMAP pokemon, "The MARSHBADGE"
	.DB $4f
	.STRINGMAP pokemon, "makes #MON up"
	.DB $55
	.STRINGMAP pokemon, "to L70 obey you!"
	.DB $51
	.STRINGMAP pokemon, "Stronger #MON"
	.DB $4f
	.STRINGMAP pokemon, "will become wild,"
	.DB $55
	.STRINGMAP pokemon, "ignoring your"
	.DB $55
	.STRINGMAP pokemon, "orders in battle!"
	.DB $51
	.STRINGMAP pokemon, "Just don't raise"
	.DB $4f
	.STRINGMAP pokemon, "your #MON too"
	.DB $55
	.STRINGMAP pokemon, "much!"
	.DB $51
	.STRINGMAP pokemon, "Wait, please take"
	.DB $4f
	.STRINGMAP pokemon, "this TM with you!"
	.DB $57
_SaffronGymSabrinaReceivedTM46Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "TM46!@"
	.DB $50
_TM46ExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "TM46 is PSYWAVE!"
	.DB $4f
	.STRINGMAP pokemon, "It uses powerful"
	.DB $55
	.STRINGMAP pokemon, "psychic waves to"
	.DB $55
	.STRINGMAP pokemon, "inflict damage!"
	.DB $57
_SaffronGymSabrinaTM46NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Your pack is full"
	.DB $4f
	.STRINGMAP pokemon, "of other items!"
	.DB $57
_SaffronGymGuideChampInMakingText::
	.DB $00
	.STRINGMAP pokemon, "Yo! Champ in"
	.DB $4f
	.STRINGMAP pokemon, "making!"
	.DB $51
	.STRINGMAP pokemon, "SABRINA's #MON"
	.DB $4f
	.STRINGMAP pokemon, "use psychic power"
	.DB $55
	.STRINGMAP pokemon, "instead of force!"
	.DB $51
	.STRINGMAP pokemon, "Fighting #MON"
	.DB $4f
	.STRINGMAP pokemon, "are weak against"
	.DB $55
	.STRINGMAP pokemon, "psychic #MON!"
	.DB $51
	.STRINGMAP pokemon, "They get creamed"
	.DB $4f
	.STRINGMAP pokemon, "before they can"
	.DB $55
	.STRINGMAP pokemon, "even aim a punch!"
	.DB $57
_SaffronGymGuideBeatSabrinaText::
	.DB $00
	.STRINGMAP pokemon, "Psychic power,"
	.DB $4f
	.STRINGMAP pokemon, "huh?"
	.DB $51
	.STRINGMAP pokemon, "If I had that,"
	.DB $4f
	.STRINGMAP pokemon, "I'd make a bundle"
	.DB $55
	.STRINGMAP pokemon, "at the slots!"
	.DB $57
_SaffronGymChanneler1BattleText::
	.DB $00
	.STRINGMAP pokemon, "SABRINA is younger"
	.DB $4f
	.STRINGMAP pokemon, "than I, but I"
	.DB $55
	.STRINGMAP pokemon, "respect her!"
	.DB $57
_SaffronGymChanneler1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Not"
	.DB $4f
	.STRINGMAP pokemon, "good enough!"
	.DB $58
_SaffronGymChanneler1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "In a battle of"
	.DB $4f
	.STRINGMAP pokemon, "equals, the one"
	.DB $55
	.STRINGMAP pokemon, "with the stronger"
	.DB $55
	.STRINGMAP pokemon, "will wins!"
	.DB $51
	.STRINGMAP pokemon, "If you wish"
	.DB $4f
	.STRINGMAP pokemon, "to beat SABRINA,"
	.DB $55
	.STRINGMAP pokemon, "focus on winning!"
	.DB $57
_SaffronGymYoungster1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Does our unseen"
	.DB $4f
	.STRINGMAP pokemon, "power scare you?"
	.DB $57
_SaffronGymYoungster1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I never"
	.DB $4f
	.STRINGMAP pokemon, "foresaw this!"
	.DB $58
_SaffronGymYoungster1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Psychic #MON"
	.DB $4f
	.STRINGMAP pokemon, "fear only ghosts"
	.DB $55
	.STRINGMAP pokemon, "and bugs!"
	.DB $57
_SaffronGymChanneler2BattleText::
	.DB $00
	.STRINGMAP pokemon, "#MON take on"
	.DB $4f
	.STRINGMAP pokemon, "the appearance of"
	.DB $55
	.STRINGMAP pokemon, "their trainers."
	.DB $51
	.STRINGMAP pokemon, "Your #MON must"
	.DB $4f
	.STRINGMAP pokemon, "be tough, then!"
	.DB $57
_SaffronGymChanneler2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I knew"
	.DB $4f
	.STRINGMAP pokemon, "it!"
	.DB $58
_SaffronGymChanneler2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I must teach"
	.DB $4f
	.STRINGMAP pokemon, "better techniques"
	.DB $55
	.STRINGMAP pokemon, "to my #MON!"
	.DB $57
_SaffronGymYoungster2BattleText::
	.DB $00
	.STRINGMAP pokemon, "You know that"
	.DB $4f
	.STRINGMAP pokemon, "power alone isn't"
	.DB $55
	.STRINGMAP pokemon, "enough!"
	.DB $57
_SaffronGymYoungster2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I don't"
	.DB $4f
	.STRINGMAP pokemon, "believe this!"
	.DB $58
_SaffronGymYoungster2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "SABRINA just wiped"
	.DB $4f
	.STRINGMAP pokemon, "out the KARATE"
	.DB $55
	.STRINGMAP pokemon, "MASTER next door!"
	.DB $57
_SaffronGymChanneler3BattleText::
	.DB $00
	.STRINGMAP pokemon, "You and I, our"
	.DB $4f
	.STRINGMAP pokemon, "#MON shall"
	.DB $55
	.STRINGMAP pokemon, "fight!"
	.DB $57
_SaffronGymChanneler3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I lost"
	.DB $4f
	.STRINGMAP pokemon, "after all!"
	.DB $58
_SaffronGymChanneler3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I knew that this"
	.DB $4f
	.STRINGMAP pokemon, "was going to take"
	.DB $55
	.STRINGMAP pokemon, "place."
	.DB $57
_SaffronGymYoungster3BattleText::
	.DB $00
	.STRINGMAP pokemon, "SABRINA is young,"
	.DB $4f
	.STRINGMAP pokemon, "but she's also"
	.DB $55
	.STRINGMAP pokemon, "our LEADER!"
	.DB $51
	.STRINGMAP pokemon, "You won't reach"
	.DB $4f
	.STRINGMAP pokemon, "her easily!"
	.DB $57
_SaffronGymYoungster3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I lost"
	.DB $4f
	.STRINGMAP pokemon, "my concentration!"
	.DB $58
_SaffronGymYoungster3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "There used to be"
	.DB $4f
	.STRINGMAP pokemon, "2 #MON GYMs in"
	.DB $55
	.STRINGMAP pokemon, "SAFFRON."
	.DB $51
	.STRINGMAP pokemon, "The FIGHTING DOJO"
	.DB $4f
	.STRINGMAP pokemon, "next door lost"
	.DB $55
	.STRINGMAP pokemon, "its GYM status"
	.DB $55
	.STRINGMAP pokemon, "when we went and"
	.DB $55
	.STRINGMAP pokemon, "creamed them!"
	.DB $57
_SaffronGymYoungster4BattleText::
	.DB $00
	.STRINGMAP pokemon, "SAFFRON #MON"
	.DB $4f
	.STRINGMAP pokemon, "GYM is famous for"
	.DB $55
	.STRINGMAP pokemon, "its psychics!"
	.DB $51
	.STRINGMAP pokemon, "You want to see"
	.DB $4f
	.STRINGMAP pokemon, "SABRINA!"
	.DB $55
	.STRINGMAP pokemon, "I can tell!"
	.DB $57
_SaffronGymYoungster4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Arrrgh!"
	.DB $58
_SaffronGymYoungster4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "That's right! I"
	.DB $4f
	.STRINGMAP pokemon, "used telepathy to"
	.DB $55
	.STRINGMAP pokemon, "read your mind!"
	.DB $57

; text/SaffronPidgeyHouse.asm
_SaffronPidgeyHouseBrunetteGirlText::
	.DB $00
	.STRINGMAP pokemon, "Thank you for"
	.DB $4f
	.STRINGMAP pokemon, "writing. I hope"
	.DB $55
	.STRINGMAP pokemon, "to see you soon!"
	.DB $51
	.STRINGMAP pokemon, "Hey! Don't look"
	.DB $4f
	.STRINGMAP pokemon, "at my letter!"
	.DB $57
_SaffronPidgeyHousePidgeyText::
	.DB $00
	.STRINGMAP pokemon, "PIDGEY: Kurukkoo!@"
	.DB $50
_SaffronPidgeyHouseYoungsterText::
	.DB $00
	.STRINGMAP pokemon, "The COPYCAT is"
	.DB $4f
	.STRINGMAP pokemon, "cute! I'm getting"
	.DB $55
	.STRINGMAP pokemon, "her a # DOLL!"
	.DB $57
_SaffronPidgeyHousePaperText::
	.DB $00
	.STRINGMAP pokemon, "I was given a PP"
	.DB $4f
	.STRINGMAP pokemon, "UP as a gift."
	.DB $51
	.STRINGMAP pokemon, "It's used for"
	.DB $4f
	.STRINGMAP pokemon, "increasing the PP"
	.DB $55
	.STRINGMAP pokemon, "of techniques!"
	.DB $57

; text/SaffronMart.asm
_SaffronMartSuperNerdText::
	.DB $00
	.STRINGMAP pokemon, "MAX REPEL lasts"
	.DB $4f
	.STRINGMAP pokemon, "longer than SUPER"
	.DB $55
	.STRINGMAP pokemon, "REPEL for keeping"
	.DB $55
	.STRINGMAP pokemon, "weaker #MON"
	.DB $55
	.STRINGMAP pokemon, "away!"
	.DB $57
_SaffronMartCooltrainerFText::
	.DB $00
	.STRINGMAP pokemon, "REVIVE is costly,"
	.DB $4f
	.STRINGMAP pokemon, "but it revives"
	.DB $55
	.STRINGMAP pokemon, "fainted #MON!"
	.DB $57

; text/SilphCo1F.asm
_SilphCo1FLinkReceptionistText::
	.DB $00
	.STRINGMAP pokemon, "Welcome!"
	.DB $51
	.STRINGMAP pokemon, "The PRESIDENT is"
	.DB $4f
	.STRINGMAP pokemon, "in the boardroom"
	.DB $55
	.STRINGMAP pokemon, "on 11F!"
	.DB $57

; text/SaffronPokecenter.asm
_SaffronPokecenterBeautyText::
	.DB $00
	.STRINGMAP pokemon, "#MON growth"
	.DB $4f
	.STRINGMAP pokemon, "rates differ from"
	.DB $55
	.STRINGMAP pokemon, "specie to specie."
	.DB $57
_SaffronPokecenterGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "SILPH CO. is very"
	.DB $4f
	.STRINGMAP pokemon, "famous. That's"
	.DB $55
	.STRINGMAP pokemon, "why it attracted"
	.DB $55
	.STRINGMAP pokemon, "TEAM ROCKET!"
	.DB $57

; text/MrPsychicsHouse.asm
_MrPsychicsHouseMrPsychicYouWantedThisText::
	.DB $00
	.STRINGMAP pokemon, "...Wait! Don't"
	.DB $4f
	.STRINGMAP pokemon, "say a word!"
	.DB $51
	.STRINGMAP pokemon, "You wanted this!"
	.DB $58
_MrPsychicsHouseMrPsychicReceivedTM29Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_MrPsychicsHouseMrPsychicTM29ExplanationText::
	.DB $00
	.STRINGMAP pokemon, "TM29 is PSYCHIC!"
	.DB $51
	.STRINGMAP pokemon, "It can lower the"
	.DB $4f
	.STRINGMAP pokemon, "target's SPECIAL"
	.DB $55
	.STRINGMAP pokemon, "abilities."
	.DB $57
_MrPsychicsHouseMrPsychicTM29NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Where do you plan"
	.DB $4f
	.STRINGMAP pokemon, "to put this?"
	.DB $57

; data/text/text_4.asm
_PokemartGreetingText::
	.DB $00
	.STRINGMAP pokemon, "Hi there!"
	.DB $4e
	.STRINGMAP pokemon, "May I help you?"
	.DB $57
_PokemonFaintedText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "fainted!"
	.DB $57
_PlayerBlackedOutText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> is out of"
	.DB $4f
	.STRINGMAP pokemon, "useable #MON!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> blacked"
	.DB $4f
	.STRINGMAP pokemon, "out!"
	.DB $58
_RepelWoreOffText::
	.DB $00
	.STRINGMAP pokemon, "REPEL's effect"
	.DB $4f
	.STRINGMAP pokemon, "wore off."
	.DB $57
_PokemartBuyingGreetingText::
	.DB $00
	.STRINGMAP pokemon, "Take your time."
	.DB $57
_PokemartTellBuyPriceText::
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "?"
	.DB $4f
	.STRINGMAP pokemon, "That will be"
	.DB $55
	.STRINGMAP pokemon, "¥@"
	.DB $02
	.DW hMoney
	.DB $c3
	.DB $00
	.STRINGMAP pokemon, ". OK?"
	.DB $57
_PokemartBoughtItemText::
	.DB $00
	.STRINGMAP pokemon, "Here you are!"
	.DB $4f
	.STRINGMAP pokemon, "Thank you!"
	.DB $58
_PokemartNotEnoughMoneyText::
	.DB $00
	.STRINGMAP pokemon, "You don't have"
	.DB $4f
	.STRINGMAP pokemon, "enough money."
	.DB $58
_PokemartItemBagFullText::
	.DB $00
	.STRINGMAP pokemon, "You can't carry"
	.DB $4f
	.STRINGMAP pokemon, "any more items."
	.DB $58
_PokemonSellingGreetingText::
	.DB $00
	.STRINGMAP pokemon, "What would you"
	.DB $4f
	.STRINGMAP pokemon, "like to sell?"
	.DB $57
_PokemartTellSellPriceText::
	.DB $00
	.STRINGMAP pokemon, "I can pay you"
	.DB $4f
	.STRINGMAP pokemon, "¥@"
	.DB $02
	.DW hMoney
	.DB $c3
	.DB $00
	.STRINGMAP pokemon, " for that."
	.DB $57
_PokemartItemBagEmptyText::
	.DB $00
	.STRINGMAP pokemon, "You don't have"
	.DB $4f
	.STRINGMAP pokemon, "anything to sell."
	.DB $58
_PokemartUnsellableItemText::
	.DB $00
	.STRINGMAP pokemon, "I can't put a"
	.DB $4f
	.STRINGMAP pokemon, "price on that."
	.DB $58
_PokemartThankYouText::
	.DB $00
	.STRINGMAP pokemon, "Thank you!"
	.DB $57
_PokemartAnythingElseText::
	.DB $00
	.STRINGMAP pokemon, "Is there anything"
	.DB $4f
	.STRINGMAP pokemon, "else I can do?"
	.DB $57
_LearnedMove1Text::
	.DB $01
	.DW wLearnMoveMonName
	.DB $00
	.STRINGMAP pokemon, " learned"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_WhichMoveToForgetText::
	.DB $00
	.STRINGMAP pokemon, "Which move should"
	.DB $4e
	.STRINGMAP pokemon, "be forgotten?"
	.DB $57
_AbandonLearningText::
	.DB $00
	.STRINGMAP pokemon, "Abandon learning"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "?"
	.DB $57
_DidNotLearnText::
	.DB $01
	.DW wLearnMoveMonName
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "did not learn"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $58
_TryingToLearnText::
	.DB $01
	.DW wLearnMoveMonName
	.DB $00
	.STRINGMAP pokemon, " is"
	.DB $4f
	.STRINGMAP pokemon, "trying to learn"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $51
	.STRINGMAP pokemon, "But, @"
	.DB $01
	.DW wLearnMoveMonName
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "can't learn more"
	.DB $55
	.STRINGMAP pokemon, "than 4 moves!"
	.DB $51
	.STRINGMAP pokemon, "Delete an older"
	.DB $4f
	.STRINGMAP pokemon, "move to make room"
	.DB $55
	.STRINGMAP pokemon, "for @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "?"
	.DB $57
_OneTwoAndText::
	.DB $00
	.STRINGMAP pokemon, "1, 2 and...@"
	.DB $50
_PoofText::
	.DB $00
	.STRINGMAP pokemon, " Poof!@"
	.DB $50
_ForgotAndText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wLearnMoveMonName
	.DB $00
	.STRINGMAP pokemon, " forgot"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $51
	.STRINGMAP pokemon, "And..."
	.DB $58
_HMCantDeleteText::
	.DB $00
	.STRINGMAP pokemon, "HM techniques"
	.DB $4f
	.STRINGMAP pokemon, "can't be deleted!"
	.DB $58
_PokemonCenterWelcomeText::
	.DB $00
	.STRINGMAP pokemon, "Welcome to our"
	.DB $4f
	.STRINGMAP pokemon, "#MON CENTER!"
	.DB $51
	.STRINGMAP pokemon, "We heal your"
	.DB $4f
	.STRINGMAP pokemon, "#MON back to"
	.DB $55
	.STRINGMAP pokemon, "perfect health!"
	.DB $58
_ShallWeHealYourPokemonText::
	.DB $00
	.STRINGMAP pokemon, "Shall we heal your"
	.DB $4f
	.STRINGMAP pokemon, "#MON?"
	.DB $57
_NeedYourPokemonText::
	.DB $00
	.STRINGMAP pokemon, "OK. We'll need"
	.DB $4f
	.STRINGMAP pokemon, "your #MON."
	.DB $57
_PokemonFightingFitText::
	.DB $00
	.STRINGMAP pokemon, "Thank you!"
	.DB $4f
	.STRINGMAP pokemon, "Your #MON are"
	.DB $55
	.STRINGMAP pokemon, "fighting fit!"
	.DB $58
_PokemonCenterFarewellText::
	.DB $00
	.STRINGMAP pokemon, "We hope to see"
	.DB $4f
	.STRINGMAP pokemon, "you again!"
	.DB $57
_CableClubNPCAreaReservedFor2FriendsLinkedByCableText::
	.DB $00
	.STRINGMAP pokemon, "This area is"
	.DB $4f
	.STRINGMAP pokemon, "reserved for 2"
	.DB $55
	.STRINGMAP pokemon, "friends who are"
	.DB $55
	.STRINGMAP pokemon, "linked by cable."
	.DB $57
_CableClubNPCWelcomeText::
	.DB $00
	.STRINGMAP pokemon, "Welcome to the"
	.DB $4f
	.STRINGMAP pokemon, "Cable Club!"
	.DB $57
_CableClubNPCPleaseApplyHereHaveToSaveText::
	.DB $00
	.STRINGMAP pokemon, "Please apply here."
	.DB $51
	.STRINGMAP pokemon, "Before opening"
	.DB $4f
	.STRINGMAP pokemon, "the link, we have"
	.DB $55
	.STRINGMAP pokemon, "to save the game."
	.DB $57
_CableClubNPCPleaseWaitText::
	.DB $00
	.STRINGMAP pokemon, "Please wait.@"
	.DB $50
_CableClubNPCLinkClosedBecauseOfInactivityText::
	.DB $00
	.STRINGMAP pokemon, "The link has been"
	.DB $4f
	.STRINGMAP pokemon, "closed because of"
	.DB $55
	.STRINGMAP pokemon, "inactivity."
	.DB $51
	.STRINGMAP pokemon, "Please contact"
	.DB $4f
	.STRINGMAP pokemon, "your friend and"
	.DB $55
	.STRINGMAP pokemon, "come again!"
	.DB $57

Bank40TextEnd::
