; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	dba Music_Nothing
	dba Music_RBYPalletTown
	dba Music_Pokecenter
	dba Music_RBYGym
	dba Music_Cities1
	dba Music_Cities2
	dba Music_Celadon
	dba Music_Cinnabar
	dba Music_Vermilion
	dba Music_Lavender
	dba Music_SSAnne
	dba Music_MeetProfOak
	dba Music_MeetRival
	dba Music_MuseumGuy
	dba Music_SafariZone
	dba Music_PkmnHealed
	dba Music_Routes1
	dba Music_Routes2
	dba Music_Routes3
	dba Music_Routes4
	dba Music_RBYIndigoPlateau
	dba Music_GymLeaderBattle
	dba Music_TrainerBattle
	dba Music_WildBattle
	dba Music_FinalBattle
	dba Music_DefeatedTrainer
	dba Music_DefeatedWildMon
	dba Music_DefeatedGymLeader
	dba Music_RBYTitleScreen
	dba Music_RBYCredits
	dba Music_RBYHallOfFame
	dba Music_OaksLab
	dba Music_JigglypuffSong
	dba Music_BikeRiding
	dba Music_Surfing
	dba Music_RBYGameCorner
	dba Music_IntroBattle
	dba Music_Dungeon1
	dba Music_Dungeon2
	dba Music_Dungeon3
	dba Music_CinnabarMansion
	dba Music_PokemonTower
	dba Music_SilphCo
	dba Music_MeetEvilTrainer
	dba Music_MeetFemaleTrainer
	dba Music_MeetMaleTrainer
