; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	dba Music_Nothing
	dba Music_TitleScreen
	dba Music_Route1
	dba Music_Route3
	dba Music_Route12
	dba Music_MagnetTrain
	dba Music_KantoGymBattle
	dba Music_KantoTrainerBattle
	dba Music_KantoWildBattle
	dba Music_PokemonCenter
	dba Music_LookHiker
	dba Music_LookLass
	dba Music_LookOfficer
	dba Music_HealPokemon
	dba Music_LavenderTown
	dba Music_Route2
	dba Music_MtMoon
	dba Music_ShowMeAround
	dba Music_GameCorner
	dba Music_Bicycle
	dba Music_HallOfFame
	dba Music_ViridianCity
	dba Music_CeladonCity
	dba Music_TrainerVictory
	dba Music_WildPokemonVictory
	dba Music_GymLeaderVictory
	dba Music_MtMoonSquare
	dba Music_Gym
	dba Music_PalletTown
	dba Music_ProfOaksPokemonTalk
	dba Music_ProfOak
	dba Music_LookRival
	dba Music_AfterTheRivalFight
	dba Music_Surf
	dba Music_Evolution
	dba Music_NationalPark
	dba Music_Credits
	dba Music_AzaleaTown
	dba Music_CherrygroveCity
	dba Music_LookKimonoGirl
	dba Music_UnionCave
	dba Music_JohtoWildBattle
	dba Music_JohtoTrainerBattle
	dba Music_Route30
	dba Music_EcruteakCity
	dba Music_VioletCity
	dba Music_JohtoGymBattle
	dba Music_ChampionBattle
	dba Music_RivalBattle
	dba Music_RocketBattle
	dba Music_ElmsLab
	dba Music_DarkCave
	dba Music_Route29
	dba Music_Route36
	dba Music_SSAqua
	dba Music_LookYoungster
	dba Music_LookBeauty
	dba Music_LookRocket
	dba Music_LookPokemaniac
	dba Music_LookSage
	dba Music_NewBarkTown
	dba Music_GoldenrodCity
	dba Music_VermilionCity
	dba Music_PokemonChannel
	dba Music_PokeFluteChannel
	dba Music_TinTower
	dba Music_SproutTower
	dba Music_BurnedTower
	dba Music_Lighthouse
	dba Music_LakeOfRage
	dba Music_IndigoPlateau
	dba Music_Route37
	dba Music_RocketHideout
	dba Music_DragonsDen
	dba Music_JohtoWildBattleNight
	dba Music_RuinsOfAlphRadio
	dba Music_SuccessfulCapture
	dba Music_Route26
	dba Music_Mom
	dba Music_VictoryRoad
	dba Music_PokemonLullaby
	dba Music_PokemonMarch
	dba Music_GoldSilverOpening
	dba Music_GoldSilverOpening2
	dba Music_MainMenu
	dba Music_RuinsOfAlphInterior
	dba Music_RocketTheme
	dba Music_DancingHall
	dba Music_ContestResults
	dba Music_BugCatchingContest
	dba Music_LakeOfRageRocketRadio
	dba Music_Printer
	dba Music_PostCredits
; new to Crystal
	dba Music_Clair
	dba Music_MobileAdapterMenu
	dba Music_MobileAdapter
	dba Music_BuenasPassword
	dba Music_LookMysticalMan
	dba Music_CrystalOpening
	dba Music_BattleTowerTheme
	dba Music_SuicuneBattle
	dba Music_BattleTowerLobby
	dba Music_MobileCenter
