tbp: MACRO
	dbw BANK(\1), \1
	ENDM

	tbp Music_Nothing
	tbp Music_RBYPalletTown
	tbp Music_Pokecenter
	tbp Music_RBYGym
	tbp Music_Cities1
	tbp Music_Cities2
	tbp Music_Celadon
	tbp Music_Cinnabar
	tbp Music_Vermilion
	tbp Music_Lavender
	tbp Music_SSAnne
	tbp Music_MeetProfOak
	tbp Music_MeetRival
	tbp Music_MuseumGuy
	tbp Music_SafariZone
	tbp Music_PkmnHealed
	tbp Music_Routes1
	tbp Music_Routes2
	tbp Music_Routes3
	tbp Music_Routes4
	tbp Music_RBYIndigoPlateau
	tbp Music_GymLeaderBattle
	tbp Music_TrainerBattle
	tbp Music_WildBattle
	tbp Music_FinalBattle
	tbp Music_DefeatedTrainer
	tbp Music_DefeatedWildMon
	tbp Music_DefeatedGymLeader
	tbp Music_RBYTitleScreen
	tbp Music_RBYCredits
	tbp Music_RBYHallOfFame
	tbp Music_OaksLab
	tbp Music_JigglypuffSong
	tbp Music_BikeRiding
	tbp Music_Surfing
	tbp Music_RBYGameCorner
	tbp Music_IntroBattle
	tbp Music_Dungeon1
	tbp Music_Dungeon2
	tbp Music_Dungeon3
	tbp Music_CinnabarMansion
	tbp Music_PokemonTower
	tbp Music_SilphCo
	tbp Music_MeetEvilTrainer
	tbp Music_MeetFemaleTrainer
	tbp Music_MeetMaleTrainer
