SFX:
; entries correspond to SFX_* constants
	dbw 0, 0
	dba SFX_Get_Item1_1

	dba SFX_Get_Item2_1
	dba SFX_Tink_1
	dba SFX_Heal_HP_1
	dba SFX_Heal_Ailment_1
	dba SFX_Start_Menu_1
	dba SFX_Press_AB_1

	dba SFX_Pokedex_Rating_1
	dba SFX_Get_Key_Item_1
	dba SFX_Poisoned_1
	dba SFX_Trade_Machine_1
	dba SFX_Turn_On_PC_1
	dba SFX_Turn_Off_PC_1
	dba SFX_Enter_PC_1
	dba SFX_Shrink_1
	dba SFX_Switch_1
	dba SFX_Healing_Machine_1
	dba SFX_Teleport_Exit1_1
	dba SFX_Teleport_Enter1_1
	dba SFX_Teleport_Exit2_1
	dba SFX_Ledge_1
	dba SFX_Teleport_Enter2_1
	dba SFX_Fly_1
	dba SFX_Denied_1
	dba SFX_Arrow_Tiles_1
	dba SFX_Push_Boulder_1
	dba SFX_SS_Anne_Horn_1
	dba SFX_Withdraw_Deposit_1
	dba SFX_Cut_1
	dba SFX_Go_Inside_1
	dba SFX_Swap_1
	dba SFX_59_1
	dba SFX_Purchase_1
	dba SFX_Collision_1
	dba SFX_Go_Outside_1
	dba SFX_Save_1

	dba SFX_Pokeflute
	dba SFX_Safari_Zone_PA

	dba SFX_Level_Up

	dba SFX_Ball_Toss
	dba SFX_Ball_Poof
	dba SFX_Faint_Thud
	dba SFX_Run
	dba SFX_Dex_Page_Added
	dba SFX_Caught_Mon
	dba SFX_Peck
	dba SFX_Faint_Fall
	dba SFX_Battle_09
	dba SFX_Pound
	dba SFX_Battle_0B
	dba SFX_Battle_0C
	dba SFX_Battle_0D
	dba SFX_Battle_0E
	dba SFX_Battle_0F
	dba SFX_Damage
	dba SFX_Not_Very_Effective
	dba SFX_Battle_12
	dba SFX_Battle_13
	dba SFX_Battle_14
	dba SFX_Vine_Whip
	dba SFX_Battle_16
	dba SFX_Battle_17
	dba SFX_Battle_18
	dba SFX_Battle_19
	dba SFX_Super_Effective
	dba SFX_Battle_1B
	dba SFX_Battle_1C
	dba SFX_Doubleslap
	dba SFX_Battle_1E
	dba SFX_Horn_Drill
	dba SFX_Battle_20
	dba SFX_Battle_21
	dba SFX_Battle_22
	dba SFX_Battle_23
	dba SFX_Battle_24
	dba SFX_Battle_25
	dba SFX_Battle_26
	dba SFX_Battle_27
	dba SFX_Battle_28
	dba SFX_Battle_29
	dba SFX_Battle_2A
	dba SFX_Battle_2B
	dba SFX_Battle_2C
	dba SFX_Psybeam
	dba SFX_Battle_2E
	dba SFX_Battle_2F
	dba SFX_Psychic_M
	dba SFX_Battle_31
	dba SFX_Battle_32
	dba SFX_Battle_33
	dba SFX_Battle_34
	dba SFX_Battle_35
	dba SFX_Battle_36
	dba SFX_Silph_Scope

	dba SFX_Intro_Lunge
	dba SFX_Intro_Hip
	dba SFX_Intro_Hop
	dba SFX_Intro_Raise
	dba SFX_Intro_Crash
	dba SFX_Intro_Whoosh
	dba SFX_Slots_Stop_Wheel
	dba SFX_Slots_Reward
	dba SFX_Slots_New_Spin
	dba SFX_Shooting_Star

	dba SFX_PokefluteInBattle
