; These are all the asm constants needed to make the red_vc patch.

; [FPA 001 Begin]
EXPORT DEF M_CHAR EQU "M"
EXPORT DEF E_CHAR EQU "E"
EXPORT DEF G_CHAR EQU "G"
EXPORT DEF A_CHAR EQU "A"
EXPORT DEF P_CHAR EQU "P"
EXPORT DEF S_CHAR EQU "S"
EXPORT DEF L_CHAR EQU "L"
EXPORT DEF F_CHAR EQU "F"
EXPORT DEF D_CHAR EQU "D"
EXPORT DEF X_CHAR EQU "X"
EXPORT MEGA_PUNCH

; [FPA 002 Begin]
EXPORT DEF U_CHAR EQU "U"
EXPORT DEF I_CHAR EQU "I"
EXPORT GUILLOTINE

; [FPA 003 Begin]
EXPORT DEF K_CHAR EQU "K"
EXPORT MEGA_KICK

; [FPA 004 Begin]
EXPORT DEF B_CHAR EQU "B"
EXPORT BUBBLEBEAM

; [FPA 005 Begin]
EXPORT DEF H_CHAR EQU "H"
EXPORT DEF Y_CHAR EQU "Y"
EXPORT HYPER_BEAM

; [FPA 006 Begin]
EXPORT DEF T_CHAR EQU "T"
EXPORT DEF N_CHAR EQU "N"
EXPORT THUNDERBOLT

; [FPA 007 Begin]
EXPORT DEF R_CHAR EQU "R"
EXPORT REFLECT

; [FPA 008 Begin]
EXPORT DREAM_EATER

; [FPA 008 End]
EXPORT DEF Z_CHAR EQU "Z"
EXPORT BLIZZARD

; [FPA 009 Begin]
EXPORT DEF O_CHAR EQU "O"
EXPORT SPORE

; [FPA 010 Begin]
EXPORT DEF C_CHAR EQU "C"
EXPORT ROCK_SLIDE

; [FPA 010 End]
EXPORT SELFDESTRUCT
EXPORT EXPLOSION

; [FPA conf Begin]
EXPORT CONFUSION

; [FPA phy Begin]
EXPORT PSYCHIC_M
