FuchsiaMeetingRoom_Script:
	call EnableAutoTextBoxDrawing
	ret

FuchsiaMeetingRoom_TextPointers:
	def_text_pointers
	dw_const FuchsiaMeetingRoomSafariZoneWorker1, TEXT_FUCHSIAMEETINGROOM_SAFARI_ZONE_WORKER1
	dw_const FuchsiaMeetingRoomSafariZoneWorker2, TEXT_FUCHSIAMEETINGROOM_SAFARI_ZONE_WORKER2
	dw_const FuchsiaMeetingRoomSafariZoneWorker3, TEXT_FUCHSIAMEETINGROOM_SAFARI_ZONE_WORKER3

FuchsiaMeetingRoomSafariZoneWorker1:
	text_far _FuchsiaMeetingRoomSafariZoneWorker1
	text_end

FuchsiaMeetingRoomSafariZoneWorker2:
	text_far _FuchsiaMeetingRoomSafariZoneWorker2
	text_end

FuchsiaMeetingRoomSafariZoneWorker3:
	text_far _FuchsiaMeetingRoomSafariZoneWorker3
	text_end
