SafariZoneEastRestHouse_Script:
	call EnableAutoTextBoxDrawing
	ret

SafariZoneEastRestHouse_TextPointers:
	def_text_pointers
	dw_const SafariZoneEastRestHouseScientistText,   TEXT_SAFARIZONEEASTRESTHOUSE_SCIENTIST
	dw_const SafariZoneEastRestHouseRockerText,      TEXT_SAFARIZONEEASTRESTHOUSE_ROCKER
	dw_const SafariZoneEastRestHouseSiphWorkerMText, TEXT_SAFARIZONEEASTRESTHOUSE_SIPH_WORKER_M

SafariZoneEastRestHouseScientistText:
	text_far _SafariZoneEastRestHouseScientistText
	text_end

SafariZoneEastRestHouseRockerText:
	text_far _SafariZoneEastRestHouseRockerText
	text_end

SafariZoneEastRestHouseSiphWorkerMText:
	text_far _SafariZoneEastRestHouseSiphWorkerMText
	text_end
