UndergroundPathRoute7Copy_Script:
	ld a, ROUTE_7
	ld [wLastMap], a
	ret

UndergroundPathRoute7Copy_TextPointers:
	dw UGPathRoute7EntranceUnusedText_5d773
	dw UGPathRoute7EntranceUnusedText_5d77d

UGPathRoute7EntranceUnusedText_5d773:
	text_far _UGPathRoute7EntranceUnusedText_5d773
	text_end

UGPathRoute7EntranceUnusedText_5d778:
	text_far _UGPathRoute7EntranceUnusedText_5d778
	text_end

UGPathRoute7EntranceUnusedText_5d77d:
	text_far _UGPathRoute7EntranceUnusedText_5d77d
	text_end

UGPathRoute7EntranceUnusedText_5d782:
	text_far _UGPathRoute7EntranceUnusedText_5d782
	text_end
